= Build Phase Image Scanning
:revdate: 2025-01-10
:page-revdate: {revdate}
:page-opendocs-origin: /06.scanning/03.build/03.build.md
:page-opendocs-slug:  /scanning/build

== CI/CD Build Phase Schwachstellen-Scanning

Scannen Sie während der Build-Phase der Pipeline mit Plug-ins wie https://plugins.jenkins.io/neuvector-vulnerability-scanner/[Azure Devops] Jenkins, https://github.com/neuvector/azure-vsts[Action], https://github.com/neuvector/scan-action[CircleCI] Github, https://gitlab.com/neuvector/gitlab-plugin[] gitlab, Bamboo und https://github.com/neuvector/circleci-orb[] oder verwenden Sie die REST-API. {product-name} unterstützt zwei Arten von Scans in der Build-Phase: Registry und Local. Für das Scannen der Registrierung müssen der {product-name} Controller und der Scanner in der Lage sein, eine Verbindung zur Registrierung herzustellen, um das Bild abzurufen.

Um einen Build-Phase-Scan auszulösen, muss das Plug-in (z. B. Jenkins) in der Lage sein, sich mit dem Controller oder Allinone zu verbinden. Anmerkung: Der Standard-REST-API-Port für Plug-ins zum Aufrufen des Scanners ist 10443. Dieser Port muss durch den Allinone oder Controller über einen Dienst in Kubernetes oder eine Port-Map (z. B. - 10443:10443) in der Docker-Run- oder Compose-Datei offengelegt werden.

Vergewissern Sie sich, dass ein {product-name} Scanner-Container installiert und richtig konfiguriert ist, um eine Verbindung zum Allinone oder Controller herzustellen. Ab Version 4.0 muss der neuvector/scanner-Container getrennt vom allinone oder Controller bereitgestellt werden und ist in den yaml-Beispieldateien enthalten.

Sie können das Plug-in über den Jenkins Plug-in Manager herunterladen. Andere Plug-ins sind über die Kataloge des Build-Tools oder über die https://github.com/neuvector[Github-Seite]  Der Bamboo Scanner ist unter https://github.com/neuvector/bamboo-plugin/releases/tag/1.0.1. erhältlich. Der CircleCI ORB ist unter https://github.com/neuvector/circleci-orb und über den CircleCI ORB Katalog erhältlich.

=== Lokales Scannen in der Bauphase

Beim lokalen Scannen versucht der {product-name} Scanner, das Image auf einem lokalen Host zu scannen (oder auf einem Host, der über den Docker-Befehl "Remote Host" erreichbar ist).

Für Kubernetes- oder OpenShift-basiertes lokales Scannen entfernen Sie den auskommentierten Abschnitt der Beispiel-Scanner-Deployment-Yaml-Datei, wie in den Abschnitten xref:kubernetes.adoc#_deploy_using_kubernetes[Deploying {product-name}] gezeigt. Der auskommentierte Abschnitt sieht wie folgt aus:

[,yaml]
----
          env:
# Commented out sections are required only for local build-phase scanning
#            - name: SCANNER_DOCKER_URL
#              value: tcp://192.168.1.10:2376
            - name: CLUSTER_JOIN_ADDR
              value: neuvector-svc-controller.neuvector
            - name: CLUSTER_ADVERTISED_ADDR
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CLUSTER_BIND_ADDR
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
#          volumeMounts:
#            - mountPath: /var/run/docker.sock
#              name: docker-sock
#              readOnly: true
#      volumes:
#        - name: docker-sock
#          hostPath:
#            path: /var/run/docker.sock
      restartPolicy: Always
----

Für lokales Scannen mit Docker befolgen Sie die Anweisungen für Docker-Scanner-Einsätze im Abschnitt xref:docker.adoc#_deploy_the_suse_security_scanner_container[Docker-Produktionseinsätze] für den Scanner.

=== Lokales Scannen in der Build-Phase - nur Scanner (kein Controller erforderlich)

{product-name} unterstützt Standalone-Scanner-Einsätze für lokales Scannen von Bildern (für die kein Controller erforderlich ist). Bestimmte Plug-ins, wie z. B. der CircleCI ORB, bieten die Möglichkeit, einen Scanner dynamisch einzusetzen, wenn ein Bauauftrag das Scannen von Bildern erfordert, und den Scanner zu entfernen, wenn die Ergebnisse über den ORB zurückgesendet werden. Diese dynamischen Scanner-Einsätze werden automatisch über das Plug-in aufgerufen, sofern sie unterstützt werden.

Weitere Informationen zu eigenständigen Scannern finden Sie im xref:scanners.adoc[Abschnitt über Scanner].
