= Integrationen und andere Komponenten
:revdate: 2024-09-27
:page-revdate: {revdate}
:page-opendocs-origin: /14.releasenotes/02.other/02.other.md
:page-opendocs-slug:  /releasenotes/other

== Versionshinweise für Integrationsmodule, Plug-Ins und andere Komponenten

=== Github-Aktionen

* Github-Aktionen für Schwachstellen-Scans jetzt veröffentlicht unter https://github.com/neuvector/neuvector-image-scan-action.

=== Helm Chart 1.8.9

* Helm Chart v1.8.9 wurde für 5.0.0-Einsätze veröffentlicht. Wenn Sie dies mit der Vorschauversion von 5.0.0 verwenden, sollten die folgenden Änderungen an values.yml vorgenommen werden:
** Aktualisieren Sie die Registry auf docker.io
** Aktualisierung der Image-Namen/Tags auf die Vorschauversion im Docker-Hub
** Lassen Sie das Feld imagePullSecrets leer

=== Splunk App veröffentlicht

* Neue Splunk-App für {product-name} ist veröffentlicht unter https://splunkbase.splunk.com/app/6205/

=== Helm Chart Update 1.8.7

* Unterstützung von Affinitäts- und Toleranzanpassungen für Controller, Scanner und Manager.
* Hinzufügen von nodeSelector-Unterstützung für Controller-, Manager-, Scanner- und Updater-Pods.
* Unterstützung von benutzerdefinierten Umgebungsvariablen für Controller-Container.

=== Community Operator v1.2.7 für Helm Chart 1.8.2

* Benutzer können die Versionsnummer {product-name} angeben.
* Verwendet die neueste CVE-db-Version des Scanners
* Container-Operator-Image-Speicherort nach registry.neuvector.com/public verschoben
* {product-name} Der Instanzname ist standardmäßig neuvector (vorher war es example-neuvector)
* Readme-Dokument auf der Installationsseite aktualisiert und Link zu den Versionshinweisen hinzugefügt

=== Helm Chart 1.8.2

* Hinzufügen von Controller-Eingangs- und Routing-Host-Optionen.

=== Certified Operator v1.2.8 für {product-name} v4.3.1

* Unterstützt Steuerkarte Version 1.8.2
* Setzt {product-name} Version 4.3.1 ein
* Setzt Scanner db Version 2.360 ein
* andere Änderungen gegenüber der vorherigen Version 1.2.7
** Der Name der neuvector-Instanz lautet standardmäßig neuvector, vorher war es example-neuvector
** Readme-Dokument auf der Installationsseite aktualisiert
** Problem mit der Anzeige des {product-name} Logos behoben
* Bekannte Probleme
** Beim Upgrade von 1.2.7 auf 1.2.8 wird die Scanner-DB nicht aktualisiert. Abhilfe: Aktualisieren Sie das Scanner-Image auf registry.connect.redhat.com/neuvector/scanner@sha256:a802c012eee80444d9deea8c4402a1d977cf57d7b2b2044f90c9acc0e7ca3e06 bei der Scanner-Bereitstellung
** Readme-Dokument auf der Installationsseite nicht richtig ausgerichtet
** Die Scanner-Datenbank wird vom Updater nicht aktualisiert

=== Helm Chart Update 1.8.0 Juli 2021

* Helm Chart v1.8.0 wurde aktualisiert, um registry.neuvector.com als Standardregistrierung zu verwenden. HINWEIS: Sie müssen das Versionskennzeichen manuell angeben.
* Hinzufügen konfigurierbarer Parameter wie Controller-API-Anmerkungen im Helm-Diagramm. Verfügbar ab Version 1.7.6+.
* Community Operator 1.2.6, Certified Operator 1.2.7 aktualisiert, um Helm-Diagrammaktualisierungen widerzuspiegeln, einschließlich des Hinzufügens einer OpenShift-Route, wenn controller.apisvc.type aktiviert ist.

=== Sonstige Integrationen Juli 2021

* Hinzufügen eines HTML-Ausgabeformats für Scanergebnisse in Jenkins-Pipeline-Scanergebnissen.
* Hinzufügen des Namespace des betroffenen Workloads in Prometheus-Exporter-Warnungen. Jetzt unterstützt in neuvector/prometheus-exporter:4.2.2 und später.

=== Helm Chart Update 1.7.5 Mai 2021

* Unterstützungsänderungen für die neue Bildregistrierung registry.neuvector.com erforderlich.  Änderungen daran führen zu Bildpfaden (z.B. Neuvektor aus dem Pfad von Neuvektor/Controller zu Controller entfernen).

=== Helm Chart Update 1.7.2 April 2021

* Hinzufügen von Unterstützung für separate Komponenten-Ressourcenanforderungen und -begrenzungen, z.B. Controller, Enforcer cpu, Speicheranforderungen.

=== Jenkins Plug-In Aktualisierung v1.13 April 2021

* Behebung des Scan-Fehlers, der auftritt, wenn mehrere Scanner gleichzeitig ausgeführt werden.
* Anzeige der Red Hat-Schwachstellenbewertung im Scanergebnis für Red Hat-basierte Images.

=== Betreiber-Updates April 2021

* OpenShift operator/helm soll selbstsignierte Zertifikate ersetzen können. Helm Chart ist 1.7.1. Community Operator ist 1.2.4, und Certified Operator ist 1.2.3.

=== Jenkins Plug-In v1.12 März 2021

* Überschreiben Sie den Schweregrad der Schwachstelle nach Punkten. Bearbeiten können, welcher Schwachstellenbereich (CVE) für hohe und mittlere Einstufungen verwendet wird. Auf diese Weise können Sie festlegen, welche Bewertung für fehlgeschlagene Builds in der Pipeline verwendet werden kann.
* Hinzufügen von Fehlermeldungen zu den JAVA-Ausnahmen hudson.AbortException. Aktivieren Sie eine bessere Fehlermeldung von {product-name}, wenn ein Fehler auftritt.

=== Aktualisierung von Helm Chart auf 1.7.1 März 2021

* Hinzufügen von Managerdienst Loadbalancer ip und Anmerkungen.
* Fügen Sie eine Einstellung hinzu, um die pvc-Kapazität festzulegen.
* Hinzufügen von Runtime-Socket-Einstellungen für k3s und AWS bottlerocket.
* Fügen Sie Einstellungen zum Ersetzen von Controller- und Manager-Zertifikaten hinzu.

=== Scanner Februar 2021

* Behebung von CVE-2020-1938, das während des Scans in den Scanner-Versionen 1.191 und früher nicht entdeckt wurde. Aktualisieren Sie auf die neueste Scanner-Version nach 1.191.

=== Jenkins Plug-In v1.11 Februar 2021

==== Erweiterungen

* Hinzufügen von Unterstützung für den Einsatz des eigenständigen Scanners {product-name}. Dies erfordert keinen Controller und muss auf demselben Host wie die Jenkins-Installation bereitgestellt werden. Docker muss ebenfalls auf dem Host installiert sein. Derzeit wird nur die Linux-Version von Jenkins unterstützt (nicht die Container-Version). Fügen Sie außerdem den Benutzer _jenkins_ zur _Docker-Gruppe_ hinzu.

[,bash]
----
sudo usermod -aG docker jenkins
----

Referenzen:
https://plugins.jenkins.io/neuvector-vulnerability-scanner/
https://github.com/jenkinsci/neuvector-vulnerability-scanner-plugin/releases/tag/neuvector-vulnerability-scanner-1.11

=== Rancher Katalog Updates Januar 2021

* Aktualisierung von {product-name} im Rancher-Katalog zur Unterstützung von 4.x

=== Helm Chart Updates Januar 2021

* Erstellen der erforderlichen {product-name} CRDs bei der Bereitstellung
* Behebung eines Fehlers bei der Einstellung von Controller-Ingress auf true

=== Betreiber-Updates Januar 2021

* Aktualisierung der Operatoren (Gemeinschaft, zertifiziert) zur Unterstützung von 4.x

=== Steuerkartenänderungen Dezember 2020

* Erlaubt dem Benutzer, die Prioritätsklasse des Managers/Controllers/Enforcers/Scanners anzupassen. Wir empfehlen, {product-name} Containern eine höhere Priorität einzuräumen, um sicherzustellen, dass die Sicherheitsrichtlinien durchgesetzt werden, wenn die Knotenressourcen unter Druck stehen oder während eines Cluster-Upgrade-Prozesses.

=== Wichtige Helm Chart Update November 2020

[IMPORTANT]
====
Änderungen in der Struktur der Steuerkarte
====

* Das Verzeichnis für das Diagramm {product-name} hat sich von ./neuvector-helm/ zu ./neuvector-helm/charts/core/ geändert.

Wenn Sie Helm für das Upgrade verwenden, aktualisieren Sie bitte den Speicherort auf den oben angegebenen Pfad.
