= Retrait ou réinitialisation {product-name}
:revdate1: 2024-09-27
:page-revdate: {revdate}
:page-opendocs-origin: /02.deploying/10.remove/10.remove.md
:page-opendocs-slug: /déploiement/suppression

== Suppression de {product-name} Deployment / Containers

Pour supprimer le déploiement de {product-name} sur Kubernetes, utilisez le même fichier yaml pour le déploiement dans la commande delete.

[,shell]
----
kubectl delete -f neuvector.yaml
----

Cela supprimera les services et les déploiements de conteneurs de {product-name}. Vous pouvez également supprimer l'espace de noms neuvector, le volume persistant, les rôles de cluster et les liens de rôle de cluster créés lors des étapes de déploiement.

Si vous avez déployé {product-name} à l'aide d'une carte Helm ou d'un opérateur, vous devez supprimer {product-name} à l'aide de Helm ou de la commande appropriée de l'opérateur.

== Réinitialisation de {product-name} à un état initial

Outre la suppression comme indiqué ci-dessus et le redéploiement de {product-name}, les étapes suivantes peuvent être suivies dans Kubernetes pour réinitialiser {product-name}, ce qui supprimera les règles, les groupes et les autres configurations apprises, mais laissera le déploiement de {product-name} intact.

. Réduire le déploiement des contrôleurs à 0.
. (Facultatif) si un volume persistant est utilisé, supprimer la sauvegarde du volume persistant et les dossiers de registre créés.
. Faire passer le déploiement des contrôleurs à 3.

== Réinitialisation du mot de passe administrateur

Le mot de passe admin est la clé qui permet d'administrer le déploiement de {product-name} et de visualiser les activités du réseau du cluster.  Il est important de modifier le mot de passe lors de l'installation et de le conserver précieusement.  Parfois, le mot de passe est trop bien gardé et se perd ou l'administrateur quitte l'entreprise.  Si vous avez un accès kubectl au cluster, vous pouvez réinitialiser le mot de passe de l'administrateur en suivant les étapes suivantes.

Exec dans l'un des contrôleurs.

[,shell]
----
kubectl exec -it <controller> -n neuvector -- sh
----

Vérifiez que l'entrée admin existe et sauvegardez le json de sortie quelque part pour le conserver.

[,shell]
----
consul kv get object/config/user/admin
----

Prenez la sortie de la commande kv get ci-dessus et remplacez la chaîne password_hash par la chaîne ci-dessous.

[,shell]
----
c7ad44cbad762a5da0a452f9e854fdc1e0e7a52a38015f23f3eab1d80b931dd472634dfac71cd34ebc35d16ab7fb8a90c81f975113d6c7538dc69dd8de9077ec
----

Réinitialiser le mot de passe du compte administrateur à sa valeur par défaut. (REMPLACER <UPDATED_consul_kv_get_output_with_new_password_hash> AVANT L'EXÉCUTION !!!)

[,shell]
----
consul kv put object/config/user/admin '<UPDATED_consul_kv_get_output_with_new_password_hash>'
----

[WARNING]
.EXEMPLE CI-DESSOUS : (NE PAS EXÉCUTER SANS REMPLACER PAR LE RÉSULTAT)
====
[,shell]
----
consul kv put object/config/user/admin '{"fullname":"admin","username":"admin","password_hash":"c7ad44cbad762a5da0a452f9e854fdc1e0e7a52a38015f23f3eab1d80b931dd472634dfac71cd34ebc35d16ab7fb8a90c81f975113d6c7538dc69dd8de9077ec","pwd_reset_time":"2022-03-24T20:50:15.341074451Z","pwd_hash_history":null,"domain":"","server":"","email":"","role":"admin","role_oride":false,"timeout":300,"locale":"en","role_domains":{},"last_login_at":"2022-03-24T20:49:32.577877044Z","login_count":1,"failed_login_count":0,"block_login_since":"0001-01-01T00:00:00Z"}'
----

Réponse :

[,shell]
----
Success! Data written to: object/config/user/admin
----

Se connecter avec admin/admin et changer le mot de passe.
====
