= 5.xリリースノート
:revdate: 2025-08-26
:page-revdate: {revdate}
:page-opendocs-origin: /14.releasenotes/01.5x/01.5x.md
:page-opendocs-slug:  /releasenotes/5x

== 5.x のリリースノート

[NOTE]
====
新しいリリースの通知をメールで受け取るには、このSUSEメーリングリストに登録してください: https://lists.suse.com/mailman/listinfo/neuvector-updates
====

=== 5.4.6 August 2025

==== 新機能

* *NVSHAS-6733*:CRDとして応答ルールをエクスポートします。
* *NVSHAS-9899*:Javaサービス用のNeuVector Process Profile Alertsには機密データが含まれています。
* *NVSHAS-9990*:ユーザーパスワードに新しいハッシュアルゴリズムを採用。
* *NVSHAS-9968*:デフォルトの管理者アカウントのデフォルトパスワードの設定をサポート。

==== バグの修正

* *NVSHAS-10062*:初回ログイン時に管理者パスワードの作成に失敗した場合、マネージャにエラーが表示されない。
* *NVSHAS-10041*:ConfigMapによるフェデレーションの設定時にフェデレーション操作が「無効なデータ」で失敗しました。
* *NVSHAS-10018*:NeuvectorはGitLab Registryのすべての画像をスキャンしているわけではありません。
* *NVSHAS-10017*:許可されたプロセスに関連するフォールスポジティブセキュリティ警告。
* *NVSHAS-10001*:保護/監視の強制はグループ削除後に「長引く」。
* *NVSHAS-9985*:	NeuVector (Fed Master) は、外部からのすべてのリクエストに対して問題を作成します。
* *NVSHAS-9981*:	セキュリティイベントは、グループ内で新しい「プロセスプロファイルルール」が追加または変更されるたびにトリガーされます。

==== セキュリティアドバイザリ

* https://github.com/neuvector/neuvector/security/advisories/GHSA-8pxw-9c75-6w56[管理者アカウントのデフォルトパスワードが安全でない]
* https://github.com/neuvector/neuvector/security/advisories/GHSA-8ff6-pc43-jwv3[安全でないパスワード管理に虹攻撃の脆弱性]
* https://github.com/neuvector/neuvector/security/advisories/GHSA-w54x-xfxg-4gxq[デリケートな引数を持つプロセスはリークにつながる]

詳細については、xref:cve.adoc[セキュリティアドバイザリとCVE]のマニュアルを参照してください。

=== 5.4.5 2025年7月

==== 新機能

* *NVSHAS-9776*:ヘルムチャートにetcdトレランスを追加。

==== バグ修正

* *NVSHAS-9507*:OCIコンテナがスキャンされません。
* *NVSHAS-9787*:不要なマネージャログを削除します。
* *NVSHAS-9788*:証明書を生成するアルゴリズムの改良。
* *NVSHAS-9789*:リモートレジストリ設定の不要なマネージャログを削除します。
* *NVSHAS-9867*:NeuVectorは 、 `. NET Library System.Formats.Asn1 v8.013`がCVE 2024-38095の影響を受けることを明らかにした。
* *NVSHAS-9883* : [ quay.io] Dockerレジストリでワイルドカードフィルタが機能しない。
* *NVSHAS-9911*:REST APIを使用してレポジトリをスキャンすると、正しくない「メッセージ」が表示されます。
* *NVSHAS-9930*:CVE-2018-20796 for `glibc/libc-bin :2.36-9+deb12u10` – 誤検出。
* *NVSHAS-9933*:スキャン中にターゲットレジストリのエラーを表示するレジストリアダプタ機能（ハーバー）。
* *NVSHAS-9934*:ゼロドリフト機能の誤作動の疑い。
* *NVSHAS-9940*:NVスキャンJFrogサブドメインモードの問題。
* *NVSHAS-9942*:顧客イメージのイメージスキャンが失敗しています。
* *NVSHAS-9945*:プロセス名が長すぎると、適切なプロセスプロファイルルールの作成方法を決定するのが困難になります。
* *NVSHAS-9946*:クレデンシャルタイプのアドミッションコントロールアラートの表示問題。
* *NVSHAS-9947* : [ UI-ext] Rancher NeuVectorでコンプライアンスチャートに「手動」ステータスがない。
* *NVSHAS-9948*:`5.4.3`へのアップグレード後、NeuVectorの設定が失われました。
* *NVSHAS-9949* : [ Harbor ] [ Incorrect user/pw] 誤ったユーザー/pw入力でも画像をスキャンします。
* *NVSHAS-9952*:NVがライセンスキーを発行/チェックしなくなったため、使用状況レポートから「署名」を削除。
* *NVSHAS-9953*:Pods Enforcerが再起動し続ける。
* *NVSHAS-9954*:重複したメトリックを生成するNeuVector Prometheusエクスポータ。
* *NVSHAS-9958*:ネットワークルールの適用には長い時間がかかります。
* *NVSHAS-9960*:スキャナが動作しません。
* *NVSHAS-9969*:致命的エラー：マップの同時書き込みにより、Enforcerコンポーネントが再起動します。
* *NVSHAS-9971*:NV UI about `Get Bootstrap Password`.
* *NVSHAS-9975* : [ Manager] TypeError: `this.mousemoveListener`はNV GUIで見られる関数ではありません。
* *NVSHAS-9986*:プロセスとファイルのアクセスルールは、連合ポリシーグループビューで編集または削除できません。
* *NVSHAS-9988*:UI:グループページが2,000グループ以上になると、すべてのグループが表示されるわけではありません。
* *NVSHAS-9991*:UIにグループ`nv.gatekeeper-controller-manager.openshift-azure-guardrails`がありません。
* *NVSHAS-9993*:MD5をSHA256に置き換えます。
* *NVSHAS-9994*:エンフォーサーポッドが再起動し続ける。
* *NVSHAS-9996*:ヘルムチャートは、エンフォーサーポッドの非特権モードを許可する必要があります。
* *NVSHAS-9998*:NeuVector連携マスターからグループをエクスポートできません。
* *NVSHAS-10000*:NVをBCI 15.7にアップグレードします。
* *NVSHAS-10003*:Rancher UIが開いている間、リロードページがスタンドアロンNVページで動作しない。
* *NVSHAS-10008*:レジストリスキャン–スキャンした画像の表示メニューが壊れています。
* *NVSHAS-10010*:TCP SYN フラッドは入力をブロックするため、完全な入力トラフィック ブロックになります。

=== 5.4.4 2025年5月

==== 新機能

* **NVSHAS-9915**:ハーバースキャナーモジュールからのスキャン結果をNeuVector UIに表示する。
* **NVSHAS-9904**:各コンポーネントの`values.yaml`に`imagePullPolicy`を公開します。
* **NVSHAS-9869**:UI:DDoSコントロールをグループペインに移動します。
* **NVSHAS-9840** : [ GCP] NeuVector AutopilotをGCPに対応。
* **NVSHAS-9248**:未使用のプロセス/ネットワークルールをカウンタと`最終使用`タイムスタンプとともに表示します。
* **NVSHAS-8160** : [ コントローラ] セキュリティリスクスコアの計算用に一部の項目を調整しました。
* **NVSHAS-4673**:グループをエクスポートする前にメッセージを追加する提案。

==== バグ修正

* **NVSHAS-9931**:マルチクラスタでNeuVector製品のバージョンに矛盾がある場合に警告を追加する。
* **NVSHAS-9925**:レジストリページの`/v1/scan/asset/images` APIが失敗する。
* **NVSHAS-9913**:ワークロード:XYZグループに関連するいくつかのネットワークルールの削除に関する問題。
* **NVSHAS-9912**:コントローラサービスアカウントに必要ないくつかのK8s RBACパーミッションについて、Helmを更新します。
* **NVSHAS-9909**:NeuVector Rancher NavLink使用時に表示される「サインアウト - 読み込みページへ」のメッセージ
* **NVSHAS-9898**:連携環境では、お客様が作成したFeed . * グループ（例：feed.core-systems）の条件を変更しても機能しません。
* **NVSHAS-9894**:[Enforcer]コントローラの準備プローブコマンド`cat /tmp/ready`が`Nv.protect`によって拒否される。
* **NVSHAS-9886**:ネットワークアクティビティでカスタム外部グループ接続のドメイン名が解決されない。
* **NVSHAS-9884**:[ノードスキャン][コンテナスキャン]スキャンが失敗します。
* **NVSHAS-9873**:NeuVector 5.4.2におけるUI Advanced Filter検索の問題。
* **NVSHAS-9865**:エクスポートされるネットワークポリシーは、選択順序（同じグループが選択されている）によって異なります。
* **NVSHAS-9828** : [ Enforcer: process] NeuVector Enforcerが短寿命ポッド（5秒未満のもの）を検出できない。
* **NVSHAS-9783**:icmpパケットを拒否するネットワークポリシーを追加した後、NeuVectorに`セキュリティイベント`のアラートが表示されない。
* **NVSHAS-9176**:名前空間 `rt_scan:w` ロールを持つユーザ権限がログインしている場合、[セキュリティリスク]> [**脆弱性]** ページにスクリプトエラーを表示します。

=== 5.4.3 2025年3月

==== 新機能

* **NVSHAS-9793**:ConfigMap と Secret を通じて NeuVector を展開する場合、LDAP/userinitcfg で Fed Global ロールを許可する。
* **NVSHAS-9764** : [ RFE ] 「 Remote Repository Configuration」にAzureのサポートを追加。
* **NVSHAS-9759**:Ingress-Exposure Reportに日付の詳細を追加します。
* **NVSHAS-9755**:シークレットのアラートで環境変数名を値と一緒に表示するように要求します。
* **NVSHAS-9748** : [ Helm] CRDの共通グループの名前紹介をサポートするNeuVector Helmアップデート（NVSHAS0-4717 ） 。
* **NVSHAS-9426**:ヘルムチャートにスキャナーのhostPathを追加します。
* **NVSHAS-9326**:NeuVector - Harbor Pluggable Scanner Module.
* **NVSHAS-9835**:ノードの自動スキャンを無効にするUI。
* **NVSHAS-7997**:ghcr.io用スキャナーコネクター。
* **NVSHAS-7982**:フェデレーションマスターからWAFセンサーを割り当てます。

==== バグ修正

* **NVSHAS-9849**:エンフォーサーがコントローラに登録されていません。
* **NVSHAS-9847**:Dockerレジストリでワイルドカードフィルタが機能しません。
* **NVSHAS-9833**:Rancherの導入で設定の復元に失敗する。
* **NVSHAS-9832**:Workloadグループを使用してネットワークルールを作成する際の問題。
* **NVSHAS-9821**:プロセス利益ルールアラートのコマンドラインからプロセス名が一致しません。
* **NVSHAS-9817**:NvClusterSecurityRule CRDを作成すると、正常に作成されたことが示されますが、プロセスルールエントリが重複しているため、実際には作成されていません。
* **NVSHAS-9812**:NeuVector prometheus-exporterのメトリックが間違っています。
* **NVSHAS-9811** : [ Manager] シークレットにルートCAと中間CAを設定したカスタム証明書（CA）を使用するとGUIにアクセスできない。
* **NVSHAS-9801**:FIPSモード + `manager.env.ssl=false` の場合、Manager はエラーアウトします。
* **NVSHAS-9792**:コンスコンの最大ボディサイズを超えたため、フェデレーションポリシーの同期に失敗します。
* **NVSHAS-9784**:Jfrogの画像リポジトリスキャン中に404を返すNeuVector。
* **NVSHAS-9783**:icmpパケットを拒否するネットワークポリシーを追加した後 、 「 セキュリティイベント」にアラートが表示されない。
* **NVSHAS-9780**:Rancher NavLinkと連携していないNeuVectorのシングルサインオン。
* **NVSHAS-9777**:「レベル」キーが重複したWebhook JSON。
* **NVSHAS-9770**:ゼロドリフトモード後に自動切り替えで誤ったポリシーが切り替わる。
* **NVSHAS-9765**:保護モードでファイルアクセスが完全にブロックされない。
* **NVSHAS-9756**:Enforcer が最大 CPU に達し、メモリ圧力に関する警告がいくつか表示されます。
* **NVSHAS-9668**:RKE2 でコンプライアンス テストに失敗しました。
* **NVSHAS-9265**:PRE PCI環境における不完全で不正な脆弱性スキャンの結果。
* **NVSHAS-9227**:レジストリスキャンがスキャン処理の途中で止まって「アイドル」状態になります。
* **NVSHAS-9729**:名前空間に「同じ名前」を持つ複数のステートフルセットをプロジェクトに展開した場合、誤った脆弱性カウントが観測されます。
* **NVSHAS-9810**:NeuVectorコントローラが応答せず、UIにアクセスできません。

=== 5.4.2 2025年1月

==== 新機能

* **NVSHAS-9726**:モニタがプロキシURLを渡すようになりました。
* **NVSHAS-9719**:組み込み証明書の廃止を発表。
* **NVSHAS-9715**:コントローラとマネージャでノードポートを設定するためのヘルムチャート値のサポート。
* **NVSHAS-9710**:**「脆弱性**」タブにソート可能な`feed_rating`列を含めます。
* **NVSHAS-9669**:REST APIによる総合的なセキュリティスコア。
* **NVSHAS-9590**:すべての資産について、どの脆弱性スコアを選択する機能。
* **NVSHAS-7555**:[セキュリティイベント]に[自動更新]オプションを含める。

==== バグ修正

* **NVSHAS-9662**:Helmチャート2.8.2のロール/ロールバインディングロジックに一貫性がない。
* **NVSHAS-9652**:splunkでsyslog形式の違いを確認。
* **NVSHAS-9649**:コンテナリンクがセキュリティイベントで404応答コードを生成します。
* **NVSHAS-9613**:NeuVector Manager Podエラー/NeuVector Web UIが利用できません。
* **NVSHAS-9507**:OCIコンテナがスキャンされません。
* **NVSHAS-9443**:ArgoCD によるアップグレード/インストールは leases.coordination.k8s.io オブジェクトを作成できないため失敗します。
* **NVSHAS-9436**:CVE-2024-7347に対するCVE偽陰性の可能性。
* **NVSHAS-8386**:秘密鍵と自己署名証明書はまだ複数のイメージで出荷されています。
* **NVSHAS-9754** : [ UI]Prevent RancherがSSOのユーザー無効化に関連するOpenShiftまたはRancherのRBACの認証。
* **NVSHAS-9751** : [ ランタイムプロテクション] 監視モード＋ゼロドリフトで子プロセス実行時にアラートが発生しない。
* **NVSHAS-9721**:UIは、ユーザーが間違ったレジストリ名を入力すると、適切なエラーメッセージをポップアップするはずです。
* **NVSHAS-9696**:脆弱性ページのアセットの色表示が一貫していない。
* **NVSHAS-9686**:Neuvector Helmチャートのレジストリアダプタ証明書のハードコードされた名前空間。
* **NVSHAS-9678**:リンタ変更後の過剰なエラートレース。
* **NVSHAS-9670**:マネージャ:sbt run のプレーンテキストレスポンスのダブルクォート問題と java の名前なしライブラリ問題。
* **NVSHAS-9667**:`CTRL_PATH_DEBUG`環境変数をコントローラ展開でエラーに設定しても機能しません。
* **NVSHAS-9665**:ファイルアクセス規則：事前定義されたルールを削除すると"setRowData"エラーが生成される。
* **NVSHAS-9664**:ポリシーグループ:カスタムスクリプトを削除すると"setRowData" TypeErrorが生成されます。

[NOTE]
====
マネージャとレジストリアダプタサービスのデフォルトタイプが ClusterIP に変更されました。 NodePort が好ましい場合は、`manager.svc.type` と `cve.adapter.svc.type` を上書きすることで、ユーザーが設定を上書きすることは可能です。
====

NeuVector 5.4.2リリースでは、組み込みの内部証明書を使用したデプロイメントのサポートは廃止されました。NeuVector 5.4.2コンテナイメージ内の`/etc/neuvector/certs/internal`にある証明書が削除されます。NeuVectorを使い続けるには、以下のことを行う必要があります。

==== 5.4.2新規インストール:

===== Helmの使用：

- Helmチャートの`internal.autoGenerateCert`フラグと`internal.autoRotateCert`フラグを有効にします（これらは5.4.2リリースからデフォルトで有効になります ） 。あるいは、YAMLメソッドを以下にリンクします。

===== YAMLを使う:

- 既存のxref:internal.adoc#_replacing_certificates_used_in_internal_communications_of_suse_security[方法で内部]証明書を提供します。

==== 以前のバージョンから5.4.2へのアップグレード:

データを損失せずにローリング更新を実現するため、コントローラ、施行者、レジストリアダプタの内部証明書をスキャナから作成および設定してください。アップグレードする前に、設定のバックアップを取ることが推奨されます。

次の手順は、`.yaml`ファイルを使用する配置の場合にのみ必要です。Helmを使用したアップグレードでは、内部証明書がデフォルトで`internal.autoGenerateCert`および`internal.autoRotateCert`フラグを介して作成されるため、これらの追加手順は必要ありません。

[,shell]
----
docker run -it --entrypoint=bash neuvector/scanner:3.654 -c "cat /etc/neuvector/certs/internal/ca.cert" > ca.crt
----

[,shell]
----
docker run -it --entrypoint=bash neuvector/scanner:3.654 -c "cat /etc/neuvector/certs/internal/cert.pem" > tls.crt
----

[,shell]
----
docker run -it --entrypoint=bash neuvector/scanner:3.654 -c "cat /etc/neuvector/certs/internal/cert.key" > tls.key
----

[,shell]
----
kubectl create secret generic internal-cert -n neuvector  --from-file=tls.key --from-file=tls.crt --from-file=ca.crt
----

内部証明書が設定された5.4.2 yamlのサンプル:
*https://github.com/neuvector/manifests/blob/main/kubernetes/5.4.0/neuvector-k8s.yaml*

xref:internal.adoc[内部証明書]に関する追加情報。


PVC 設定の場合、ユーザは新規インストールで既存の PVC を設定して、設定を復元できます。


**スキャナーに関する補足事項:**

現在5.4.2より前のバージョンを使用しているユーザーの場合、証明書は2025年3月31日まで`neuvector/scanner:latest`で利用できます。この日以降は削除されます。ユーザは、スキャナの使用を継続するために、コントローラ、施行者、スキャナ、およびレジストリアダプタに同じ内部証明書を提供するように計画する必要があります。

スタンドアロンスキャナはこれらの変更の影響を受けませんのでご注意ください。

=== 5.4.1 2024年11月

==== 新機能

* **NVSHAS-8583**:ルールセットの細分ポリシーモードの設定、グループレベルでの個別のネットワークポリシーモードとプロファイルモードの設定。
* **NVSHAS-9440**:CRDで個別のネットワークモードとプロセスとファイルモードをサポート。
* **NVSHAS-9369**:コントローラの Helm 展開サポートを介してデバッグログカテゴリを追加します。
* **NVSHAS-9040**:監視モードでアドミッション制御ルールが拒否された場合のsyslogメッセージを改善。

==== バグ修正

* **NVSHAS-9416** : [ Scanner] activemq-all-5.8.0.redhat-60024.jar は、任意の脆弱性で検出できません（ただし、以前のスキャナビルドでは検出できます ） 。
* **NVSHAS-9447**:コントローラ/スキャナポッドがクラッシュする-「サポートされていないシステムを終了します。」
* **NVSHAS-9278**:CVE-2024-41110 は最新のスキャナー画像で発見されています。
* **NVSHAS-9467**:ポッドラベルで定義されたカスタムグループは、子コンテナにプロファイルデータを反映しません。
* **NVSHAS-9442**:ArgoCDでの展開問題。
* **NVSHAS-9436**:CVE-2024-7347に対するCVE偽陰性の可能性。
* **NVSHAS-9468**:jwt-go を jwt:v5 に置き換えて CVE-2020-26160 を修正。
* **NVSHAS-9517**:アドミッションコントロールが一貫しておらず、誤った結果になる。
* **NVSHAS-9532**:イメージスキャンは完了しましたが、展開はまだ許可されていません。
* **NVSHAS-9558**:JWTトークンの有効期限がhttp.StatusRequestTimeout 408と報告される。
* **NVSHAS-9576**:ユーザーがJenkinsでコントローラモードを使用してスキャンする場合、レジストリデータのパスワードフィールドをクリアします。
* **NVSHAS-9425**:コンテナにvxlanがある場合にnfqを作成します。
* **NVSHAS-9571** : [ レジストリ] スキャンしたすべての画像に対するフィルタがうまく機能しない。
* **NVSHAS-9589**:管理対象クラスタが切断されました:プライマリクラスタとのバージョンの不一致です。
* **NVSHAS-8824**:ユーザーが自分のグループを削除できませんでした。名前空間スコープのグループを作成できません。
* **NVSHAS-9605**:ポリシーモードとプロセスプロファイルモードの値が無効なエクスポートグループが誤って許可されます。
* **NVSHAS-9608**:コントローラが最大23MBの巨大なスキャン結果のエラーを報告しても、スキャナはエラーを報告しません。
* **NVSHAS-9534**:アドミッションコントロールの表示エラー。
* **NVSHAS-9600**:コントローラのデバッグを無効にできません。
* **NVSHAS-9631**:いくつかの強制エラーを減らす。
* **NVSHAS-9645**:既存の CRD 処理が失敗する。
* **NVSHAS-9592**:DBのバージョンが新しいにもかかわらず、新しいスキャンは行われません。
* **NVSHAS-9212**:neuvector-binding-secret role(binding) が正しくない場合、GET ( / v1/eula) にアラートメッセージを表示する。
* **NVSHAS-9367**:レジストリの接続に失敗したときのエラーメッセージを強化。
* **NVSHAS-9475**:メニューを折りたたむと、背景グリッド印刷が完全にカバーされない。
* **NVSHAS-9485**:UIの「ネットワークセキュリティポリシーモード」のメッセージが正しくありません。
* **NVSHAS-9480**:RancherダウンストリームクラスタにデプロイされたNV UIが、Rancherログアウト後にHTTP/403をスローする。
* **NVSHAS-9547**:セキュリティリスク-->脆弱性テーブルでソートが壊れています。
* **NVSHAS-9570** : [ 脆弱性] アセット上の異なるステータスの凡例の説明を変更。
* **NVSHAS-9561**:ダッシュボード全体のセキュリティスコアは、実際のスコアと一致する必要があります。
* **NVSHAS-9572** : [ 脆弱性] ユーザーがページを更新または再ログインしても、フィルタリングされたデータが保持されていた。
* **NVSHAS-9597**:コントローラーがPOST(v1/group)に対して403を返してもUIはエラーに応答しない。
* **NVSHAS-8682**:CRD webhookサービスは、crd helmチャートからアプリケーションhelmチャートに移動する必要がある。

==== 既知の問題

* 2.8.3チャートリリースでは、以前に誤って割り当てていたリソースをcrdsからcoreに移動しました。crd とコアチャートの両方を使用する場合、コアを最初にデプロイすると、アップグレード中に問題が発生する可能性があります。これを解決するには、まずcrdsをアップグレードし、次にコアチャートをアップグレードします。

=== 2024年9月5.4日

* **UIの改善**：
** Rancher SSOユーザーを表示します。
** JWTトークンを管理する。
** 画像ナビゲーションの強化、スキャン結果のリンク。
* **セキュリティ拡張**機能:
** 新しいコンプライアンスフィルタ。
** CISベンチマークのサポート、OCIイメージ署名。
* **ネットワーク&モニタリング**:
** 高度な帯域幅とセッション追跡。
** DDoS監視。
** マルチスネットワークのサポート。
* **証明書管理**：
** ローテーション機能を含む、内部証明書の期限切れに関する新しい通知。
* **自動化&統合**:
** フェデレーションの自動化。
** Rancher RBAC の統合。
** アドミッションコントロールの改善。
* **パフォーマンス&効率**:
** メモリ使用量の削減。
** ISPのデータ料金削減。
** スキャナキャッシュは露出を統計します。
* **ユーザビリティの向上**：
** ブートストラップパスワードのサポート。
** クラウド課金データのアーカイブ。
** 名前空間境界の適用。

==== 新機能

* **NVSHAS-9012**:NV UI上で同じユーザー名を持つRancher SSOユーザーを表示する。
* **NVSHAS-8939**:Rancher SSOセッションユーザーが現在のJWTトークンをドロップ（つまりログアウト）できるように、NV UIにオプションを提供する。
* **NVSHAS-7522**:レジストリ内の画像ナビゲーションが簡単。
* **NVSHAS-8148**:コンテナイメージからレジストリイメージのスキャン結果へのリンク。
* **NVSHAS-9258**:証明書および内部証明書の有効期限が切れる新しい通知を追加します。
* **NVSHAS-8915**:新しいコンプライアンスフィルタとコンプライアンスレポートのサポート。
* **NVSHAS-9403**:Filemonitor-UI:ユーザーが事前定義されたファイル監視ルールを削除できるようにします。
* **NVSHAS-8423**:設定されたしきい値に基づいて、グループレベルの帯域幅、アクティブセッション数、およびセッションレート違反を検出します。
* **NVSHAS-9218**:DDoS監視のための連邦およびCRDグループのサポート。
* **NVSHAS-8461**:クラウドで管理されたk8sサービスのCISベンチマークをサポートします。
* **NVSHAS-7664**:レジストリスキャン中のISPデータ料金を削減します。
* **NVSHAS-8868**:スキャナキャッシュの統計情報を公開します。
* **NVSHAS-8676**:NV Protectによるベンチマークスクリプトの改善。
* **NVSHAS-9255**:FQDNを使用しない画像名のアドミッションコントロール検索レジストリをカスタマイズします。
* **NVSHAS-9144**:IDを脆弱性プロファイルに追加し、容易に識別できるようにしました。
* **NVSHAS-7687**:CLIからエンフォースメントとコントローラのログレベル（デバッグ/エラー/情報/警告）の設定をサポート。
* **NVSHAS-7518**:{product-name}コンポーネントの内部証明書を変更する。
* **NVSHAS-9287**:内部証明書ローテーションを有効にします。
* **NVSHAS-8562**:内部証明書の有効期限通知を追加します。
* **NVSHAS-8486**:Multusネットワークインターフェースをサポート。
* **NVSHAS-7447**:Rancher RBACと{product-name}の統合。
* **NVSHAS-7822**:API呼び出しをスクリプト化せずにフェデレーションを自動化。
* **NVSHAS-8799**:コンプライアンステンプレートをインポートするためのコンプライアンスフレームワークを作成します。
* **NVSHAS-8773**:初期導入時のブートストラップパスワードのサポート。
* **NVSHAS-6740**:学習リストを保護モードで強制することにより、ゼロドリフトベースラインプロファイルを改善。
* **NVSHAS-8325**:ネットワークルールにコンテナ名前空間の境界を適用する。
* **NVSHAS-8723**:クラウド課金データをアーカイブします。
* **NVSHAS-9086**:vulTraitのデータ構造を排除することで、コントローラのプロセスメモリ使用量を削減します。
* **NVSHAS-6979**:アラートの内容にレスポンスルールのコメントを含める機能。
* **NVSHAS-8845**:FedReaderとFedAdminのロールでAPIKEYを作成します。
* **NVSHAS-9306**:アドミッションコントロールの設定評価では、導入を許可または拒否するルールIDが示されます。
* **NVSHAS-9078**:OCIイメージのイメージ署名をサポート。
* **NVSHAS-7945**:KubernetesのDISA STIGベンチマークをサポート。
* **NVSHAS-8234**:拒否されるべきイメージを許可するアドミッションコントロールロジック。

==== バグ修正

* **NVSHAS-9005**:Typeレジストリでエラーが発生しました:未定義のプロパティを読み込めません（｀total_records｀を読み込みます）。
* **NVSHAS-9085**:Assets ViewのPDFレポートでは、現在の脆弱性があっても0%の脆弱性が報告されている。
* **NVSHAS-9084**:Assets View PDFレポートで、画像リストが空の場合にNaNが表示される。
* **NVSHAS-9128**:セキュリティイベント：ワークロードのネームスペース値がない場合、コンテナを表示できません。
* **NVSHAS-9025**:コンテナのNeuvector脆弱性受け入れ範囲。
* **NVSHAS-9155**:レジストリスキャンイメージの列名が正しくなく、ファイル名がありません
* **NVSHAS-9122**:Rancher SSOログインで「複数クラスタ」を使用すると、Neuvectorマスターがいつでもログアウトする。
* **NVSHAS-9266**:レジストリスキャン：「レイヤー別にスキャンレポート」ボタンは、脆弱性がないときは非表示または無効にしてください。
* **NVSHAS-9219**:認証サーバのサーバ証明書検証をユーザが有効にできるようにします。
* **NVSHAS-9246**:CSV/PDFエクスポートのフィルタリングが機能しない。
* **NVSHAS-8947**:Rancher SSOで認証された場合、NV設定をインポートできない。
* **NVSHAS-9282**:UI:OpenShiftレジストリエントリの編集がトークンの欠落により失敗する。
* **NVSHAS-9098**:リスクページ読み込みのユーザーエクスペリエンスを強化します。
* **NVSHAS-9267**:REST APIの変更により、5.4マスタークラスタのUIが5.4より前の管理対象クラスタに切り替わらないようにしてください。
* **NVSHAS-9285**:UI:ドロップダウンリストボタンが他の要素と重なっています。
* **NVSHAS-9302**:FedReaderとFedAdminのロールでAPIKEYを作成できません。
* **NVSHAS-8539**:プロキシ設定の再構成でパスワードが失われる。
* **NVSHAS-9293**:脆弱性レポート内の無関係な画像の詳細を削除。
* **NVSHAS-9238**:UIは、表示されているクラスタ名を変更した後も更新されません。
* **NVSHAS-9363**:通知設定＞Webhooksグリッドの位置が正しく揃っていない。
* **NVSHAS-9362**:「セキュリティリスクの脆弱性」フィルタの結果は0です。
* **NVSHAS-8699**:Rancher ADユーザーが同じ場合、ユーザーを区別できません。
* **NVSHAS-9062**:NV UI上で同じユーザー名を持つRancher SSOユーザーを表示する（コントローラー上で変換 ） 。
* **NVSHAS-9071**:コンテナスキャンだけで報告されないモジュールもあります。
* **NVSHAS-8242**：コントローラが重大な重大度を処理するかどうかをテストするためのgRPC呼び出し。
* **NVSHAS-8908**:X-Forwarded-Port をカンマ区切りを考慮して正しくパースする。
* **NVSHAS-9024**:AdmissionControl Risky Role Perf.
* **NVSHAS-9091**:レポ、レジストリ、スタンドアロンスキャンでol:9.1、photon:5.0、rhel:9.1、amzn:2023ソース以下のすべてのモジュールをレポートできません。
* **NVSHAS-8997**:ノードごとのポリシースロット数を大幅に減らしてパフォーマンスを向上。
* **NVSHAS-9059**:K8sからの削除後もNVにCRD基が見える。
* **NVSHAS-9107**:rest.handlerConfigLocalCluster で Goroutine がクラッシュする。
* **NVSHAS-9108**:ポート18500は開いてはいけない。
* **NVSHAS-9119**:probeでGorooutineクラッシュ。(*FileNotificationCtr).AddContainer().
* **NVSHAS-9125**:無効な設定の CRD エントリは作成を許可しないでください。
* **NVSHAS-9124**:Docker：予期せぬヘルスチェック・プロセス・インシデントが多数報告されています。
* **NVSHAS-9111**:NV は `--event-qps> 0` をチェックする必要があります。
* **NVSHAS-9130**:予期しないコンテナ.パッケージ.更新されたインシデントは、特定のコンテナの起動後に見つかります。
* **NVSHAS-9080**:Fedリーダーのユーザーが一部のREST APIにアクセスできない。
* **NVSHAS-9092**:名前付きユーザーにはグローバル資産は表示されません。
* **NVSHAS-9116**:ワーカークラスタは、接続が切断されても脱退できます。
* **NVSHAS-8980**:oc 4.15 でノード上のホストとトンネルのインターフェイスを正常に取得する。
* **NVSHAS-9188**:mgmt-brインタフェースをハーベスタノードのホストインタフェースとして設定します。
* **NVSHAS-4858**:ポリシー展開のパフォーマンスを向上させ、CPUとメモリの使用量を削減するために、コントローラでコンテナグループを展開しない。
* **NVSHAS-8700**:Rancher ADユーザーが{product-name}にログインできないことがある。
* **NVSHAS-9121**:グループのネットワーク監視しきい値の設定は編集できません。
* **NVSHAS-9189**:コントローラをシャットダウンして再起動すると、スキャンがスケジューリングでスタックします。
* **NVSHAS-9019**:ホストインタフェースのリンク状態が同期していないのを修正。
* **NVSHAS-8305**:組み込み証明書を削除します。
* **NVSHAS-9013**:プロセスモニタのBPFフィルタを削除しています。
* **NVSHAS-7853**:TLSハンドシェイクEOF。
* **NVSHAS-9290**:ZDを有効にした状態で、ユーザーが追加したプロセスプロファイルルールが有効になりません。
* **NVSHAS-9301**:「牧場主」に配備されたNVは、それが「牧場主」の味であると判断できない。
* **NVSHAS-9289**:RBACが見つからないときにアップグレードを許可します。
* **NVSHAS-7601**:シナリオ中のPV構成バックアップからの復元を改善。
* **NVSHAS-7687**:施行者のシステムログレベル設定を追加
* **NVSHAS-9292**:Fix Ingress Egress exposure」で「脆弱性」が0と表示される。
* **NVSHAS-9270**:CISベンチマークパイプラインのk3をサポート。
* **NVSHAS-9338**:アラート「管理対象クラスタ[id]がプライマリから切断されました」。
* **NVSHAS-9358**:プロキシを使用したイメージスキャンは失敗します。
* **NVSHAS-9337**:SYNフラッドが検出されたときにログメッセージを送信する。
* **NVSHAS-9209**:k8s から名前空間が削除されたときにドメインキャッシュを削除するようにした。
* **NVSHAS-8985**:コントローラの再起動後、フェデレーションレジストリが消えます。

==== 既知の問題：

* **NVSHAS-9443**:ArgoCD によるアップグレード/インストールは leases.coordination.k8s.io オブジェクトを作成できないため失敗します。
* **回避策**:ARGO CDを使用して5.4.0にアップグレードする前に、指定されたリースオブジェクトを作成します。neuvectorと異なる場合は名前空間を変更する。
+
--
[,bash]
----
cat <<EOF | kubectl apply -f -
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: neuvector-controller
  namespace: neuvector
spec:
  leaseTransitions: 0
---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: neuvector-cert-upgrader
  namespace: neuvector
spec:
  leaseTransitions: 0
EOF
----
--

=== 5.3.4 2024年7月

==== バグ修正

* OpenShift CLI v4.15で`ホスト`と`トンネルインター`フェイスの取得に成功。
* IP範囲169.254.x.xはホストインターフェイスのIPから除外されます。
* エンフォースメント起動1分後にホストインターフェースを再検査。
* OpenID発行者URLのregexが失敗する問題を修正しました。
* 以下のCVEを修正する。
+
|===
| CVE | 適用項目 | 影響

| CVE-2023-42364
| busybox
| {CVE-medium}

| CVE-2023-42365
| busybox
| {CVE-medium}

| CVE-2024-6197
| curl
| {CVE-medium}

| CVE-2024-6874
| curl
| {CVE-medium}

| CVE-2024-5535
| openssl
| {CVE-critical}

| CVE-2024-4741
| openssl
| {CVE-medium}
|===

=== 5.2.4-s5 July 2024

* 以下のCVEを修正する。

|===
| CVE | 適用項目 | 影響

| CVE-2023-42363
| busybox
| {CVE-medium}

| CVE-2023-42364
| busybox
| {CVE-medium}

| CVE-2023-42365
| busybox
| {CVE-medium}

| CVE-2023-42366
| busybox
| {CVE-medium}

| CVE-2024-6197
| curl
| {CVE-medium}

| CVE-2024-6874
| curl
| {CVE-medium}

| CVE-2024-5535
| openssl
| {CVE-critical}

| CVE-2024-4603
| openssl
| {CVE-medium}

| CVE-2024-4741
| openssl
| {CVE-medium}
|===

=== 2024年6月3日

==== 拡張機能

* `［アドミッション制御］`ページから特定のストレージクラスの使用をブロックできるようにします。
* `LDAP 認証`では、`baseDN` と `groupDN` の設定用のフィールドが分離されています。
* ［`Egress and Ingress］ チャート`には、各サービスの脆弱性数が ［`High］` および ［`Medium］` の新しい脆弱性カラムが表示されます。

==== バグ修正

* マルチエントリの`アドミッションコントロールユーザ条件`でカンマ（`，`）を使用した場合の`正規表現`に関する不具合を修正しました。
* `jar`パッケージのCVEスキャンで、同じCVEの影響を受けるすべてのパッケージが表示されないバグを修正。これで、すべての発生が報告されます。
* 以下のCVEを修正する。

|===
| CVE | 適用項目 | 影響

| CVE-2024-35195
| python:requests
| {CVE-medium}

| CVE-2024-21011
| openjdk11
| {CVE-low}

| CVE-2024-21012
| openjdk11
| {CVE-low}

| CVE-2024-21068
| openjdk11
| {CVE-low}

| CVE-2024-21085
| openjdk11
| {CVE-low}

| CVE-2024-21094
| openjdk11
| {CVE-low}
|===

==== その他

* Helmチャートを使用して{product-name}をインストールする際に、`アップデータ-cron-job`のリソースをユーザーが設定できるようにします。
* Prometheusエクスポータコンテナのバージョン管理を見直し、`コントローラ`のバージョン管理に分離しました。
* （スキャナ）UbuntuとRed Hat Enterprise Linuxの`R`パッケージ/モジュールを検出します。
* （スキャナ）PHPコンポーザ検索に対応しました。

=== 5.2.4-s3 2024年4月

* 以下のCVEを修正する。

|===
| CVE | 適用項目 | 影響

| CVE-2021-40633
| giflib
| {CVE-high}

| CVE-2023-48161
| giflib
| {CVE-high}

| CVE-2024-28757
| expat
| {CVE-high}

| CVE-2023-39742
| giflib
| {CVE-medium}

| CVE-2023-45288
| go:golang.org/x/net
| {CVE-medium}

| CVE-2024-25629
| c-ares
| {CVE-medium}

| CVE-2024-3651
| python:idna
| {CVE-medium}

| CVE-2024-2511
| openssl
| {CVE-low}
|===

=== 5.3.2 2024年4月

==== バグ修正

* 以前の{product-name}リリースからv5.3.1にアップグレードした後、既存のNvClusterSecurityRuleカスタムリソースが誤って削除される場合がある。NOTE:5.3.1バージョンは、アップグレードの問題を防ぐため、ドックハブから削除されました。

=== 5.3.1 2024年4月

[IMPORTANT]
====
5.3.2で修正されたアップグレード問題を防ぐため、5.3.1バージョンはドックハブから削除されました。リリース5.3.2を使用してください。
====

==== 拡張機能

* ユーザーがGithubアクションを使用する際に'`受け入れ`'られる脆弱性を定義して、ワークフローに影響を与えないようにします。
* 「資産」>「レジストリ」>「画像の脆弱性」ビューに、重要度、スコアレベル、フィード評価のフィルタを追加します。
* レジストリイメージスキャンに定義済みプロキシを使用する必要がある場合は、レジストリを設定するときに許可します。

==== バグ修正

* セキュリティリスク > 脆弱性 > 高度なフィルタで「修正なしのCVE」がフィルタリングされない
* コンテナからホストモードコンテナへの予期しない違反
* docker api 1.24 に切り替えると OCI 画像形式を受け入れる
* レジストリスキャンは画像以外のアーティファクトをスキャンしない/エラーを記録しない
* インターネットやシグストアに依存することなく、ルートレスな鍵ペアのイメージ署名検証を可能にします。
* セキュリティイベントが特定のノードのネットワークルールで許可されない（「コンテナタスクチャンがいっぱいです」エラーメッセージに関連する）
* コンテナがワークロードに正常に追加できません(頻繁に発生します)。チャネルメッセージからのデッドロックの結果です。

==== その他

* Jenkins、GitHub action、Bambooのスキャナープラグインを更新します。
* （スキャナ）docker api 1.24への切り替え時にOCI画像形式を受け入れるようにしました。
* （スキャナ）レジストリスキャンは画像以外のアーティファクトをスキャンしない/エラーをログに記録しない。
* (スキャナ)phpコンポーザースキャンのサポートを追加しました。

==== {product-name} UI Extension v.ランチア2024年3月1.0

* {product-name}のインストール後、Rancherから{product-name} UI Extensionをxref:rancher.adoc#_suse_security_ui_extension_for_rancher[有効化/インストール]すると、クラスタのダッシュボードが表示されます。ダッシュボードには、完全な{product-name}クラスタへのSSOへのリンクが含まれています。NOTE:拡張機能が「サードパーティ」と表示されることがあります。これは将来のリリースで修正される予定です。また、Rancher 2.7.xのユーザーはインストール後、{product-name} UI Extのアイコンが一覧に2つ表示される場合があります（バグ ） 。1つのアイコンには「アンインストール」と表示され(インストールされていることを意味します)、もう1つのアイコンには「インストール」と表示されます。これはそのままで構いません。つまり、拡張機能が既にインストールされている場合は、再度インストールしないでください。

=== 5.2.4-s2 2024年2月

* 以下のCVEを修正する。
* High cve:CVE-2023-52425 in expat、CVE-2024-20952およびCVE-2024-20918 in openjdk11
* Med cve:expatのCVE-2023-52426、openjdk11のCVE-2024-20926、CVE-2024-20921、CVE-2024-20945、CVE-2024-20919、opensslのCVE-2024-0727、CVE-2023-6237

=== 2024年2月5日

==== 拡張機能

* ダッシュボード（出力 ） 、 PDF、CSVレポート、およびネットワークアクティビティ画面とセキュリティイベント（違反）リストに外部宛先URL（FQDN）を表示する
* ディスカバーモードでは、外部FQDNアドレスグループへの出力を自動的に学習します。外部接続が既存のルールと一致しない限り、新しい外部FQDNカスタムグループが作成されます。
* 新しいController環境変数CTRL_EN_ICMP_POLICY = 1を使用してICMPの学習（Discoverモード）とブロッキング（Protectモード）を有効にする
* CRD を Github にエクスポートして、コンソールまたは REST API を使用してデフォルトのレポジトリに gitop をサポートする。
* ADFS iDPでSAML SSOシングルログアウトをサポート
* ARM64プラットフォームのサポートを追加。ARMベースのプラットフォームからプルすると、適切なARM64{product-name}イメージが自動的にプルされます。
* プロキシ経由のウェブフックをサポート
* アドミッションコントロールの監査機能を改善し、すべてのルールの結果を含める。すべてのルールの結果を一覧表示し、ライブ アドミッション コントロール展開で評価したときに が実行される最後のアクションのエントリをもう 1 つ追加します。
* CRDまたはyaml(kubectl)を介して無効のアドミッションコントロールルールを適用する
* コンソール、CRD、REST APIによる脆弱性プロファイルのエクスポート/インポート。インポートすると、既存のプロファイルが置き換えられます。CRDを削除すると、プロファイルは空になります。
* コンソール、CRD、REST APIによるコンプライアンスプロファイルテンプレートのエクスポート/インポート。インポートすると、既存のテンプレートが置き換えられます。
* CISベンチマークのコンプライアンス・レポートに「手動」ステータスを追加します。このステータスはユーザーが手動で実行する必要があります（{product-name}は実行しません）。
* 脆弱性ページのUI読み込み/パフォーマンスを改善
* ブラウザのセッションログインを統一。これによって、ブラウザのすべてのタブが同じログインセッションを共有し、既存のセッションから新しいタブを開いても認証情報は求められず、1つのタブがログアウトするとすべてのタブがログアウトされます。
* コンソール（UI）のセキュリティ強化：1) 必須のセキュリティヘッダの追加 (X-Content-Type-Options nosniff; X-XSS-Protection 1; mode=block; X-Frame-Options SAMEORIGIN; Cache-Control private, no-cache, no-store, must-revalidate
HTTP Strict Transport Security max-age=15724800, 2) CSPヘッダの追加 (例: '`default-src`' ディレクティブの設定), 3) サーバ名の開示の削除
* 新しいバージョンのCISベンチマークをサポートします。Kubernetes (1.8.0)、Kubernetes V1.24 (1.0.0)、Kubernetes V1.23 (1.0.1)、RedHat OpenShift Container Platform (1.4.0)
* アセットに表示 コンテナを-> -> レジストリとランタイムでスキャンされたコンテナの詳細
* 「セキュリティリスク」の「->の脆弱性->の影響」ポップアップで「グループ」へのリンクを追加し、グループモードを簡単に編集
* URL内の画像やコンテナの脆弱性ページへのディープリンクをサポート
* コンソールの[設定]->の[ユーザー]でユーザーパスワードをリセットするための管理者用パスワードリセットオプションを追加
* 設定->設定->通知でコントローラポッドのログにイベントログを送信できるようにします。送信されたイベントは'通知='で始まり、リーダーコントローラポッドにのみ保存されます。なお、このバージョンにはバグがあり、イベントレベルを変更するにはSYSLOGを有効にする必要がある（レベルを変更した後、必要に応じて無効にすることもできる）。
* コントローラ/エンフォーサが "/host/cgroup" をマウントするための要件を削除。
* Slack、ドキュメント、その他のリソースへのリンクを含む「サポートを受ける」メニューを追加
* /v1/log/activityログにメッセージフィールドを埋める

==== バグ修正

* セキュリティリスクの内部サーバーエラー 多数のCVEで脆弱性を->
* SIGSEGV：コントローラでのセグメンテーション違反
* jarなどの脆弱なファイルを削除しても脆弱性リストから削除されない
* 署名アルゴリズムSHA256withECDSAを使用した無効なSyslog証明書
* {product-name}は、ネットワークルールによって許可されるべきセキュリティイベントを表示する
* 「ゾンビ」強制実行中の非管理ノード
* 「詳細フィルタ」で「修復」フィールドと「影響」フィールドが空白で表示される
* Enforcerの予期しない再起動を防ぐための文字列処理の修正
* 組み込みグループに関する予期しない違反
* Support-bundle enforcer debug RPC call for data returns error
* セキュリティイベントでグループが一致しない
* Slackへのイベント送信が機能しない-プロキシで
* 許可されたネットワークルールのセキュリティイベントの表示

==== その他

* Helmチャートに実行時コンテナエンジン（ソケット）自動検出機能を追加
* Helmチャートの特権モードでコントローラを実行するための設定を削除し、コントローラ/エンフォーサが"/host/cgroup"をマウントするための要件を削除。
* サンプルのkubernetesデプロイメントファイルは{product-name}ドキュメントから削除されました。例についてはリンク先をご参照ください。

==== 強調表示された変更点(手動展開で変更が必要になる場合がある)(5.3.xの最新のヘルムチャートにすべての変更がすでに反映されている)

* コンテナのランタイム(ソケット)の自動検出により、コンテナのランタイムとソケットパスを指定する必要がなくなります。
* コントローラを特権モードで実行するための要件が削除されたことで、ランタイムソケットとマウントされた/host/cgroup/をマウントする必要がなくなった
* yamlのneuvector-binding-secretだけでなくneuvector-binding-secretにもロール/ロールバインディングを追加。
* 5.3に必要な新しいサービスアカウントとロールバインディング
* 参照されるすべてのデプロイメントyamlファイルのパスに/5.3.0/が含まれるようになりました

=== 2024年1月

==== セキュリティパッチのリリース

* opensslのCVE-2023-6129、curlのCVE-2023-46219、CVE-2023-46218を修正。

=== 2023年11月2日

==== バグ修正

* Azure AKS ValidatingWebhook設定変更とエラーログ。

=== 2023年11月23日

==== 拡張機能

* ScannerにNVD API 2.0のサポートを追加。
* スキャナスタンドアロンモードでコンテナホストをスキャンします。

[,shell]
----
docker run --rm --privileged --pid=host neuvector/scanner -n
----

==== バグ修正

* docker cp / grpc のデッドロックの問題により、ノードのスキャンが失敗する。

=== 5.2.2-s1 2023年10月

==== セキュリティアップデート

* High CVE-2023-38545 および CVE-2023-43804 を含む CVE を修正するアップデートパッケージ。

=== 2023年10月5日

==== CVE-2023-32188のセキュリティアドバイザリ

* CVE-2023-32188 "`JWTトークン`"詐欺の修復 導入時およびアップグレード時にJWTトークンの署名に使用される証明書を自動生成し、Helmベースの導入時にManager/RESTful API証明書を自動生成することで、リモートコード実行（RCE）を含む悪意のあるアクションが可能になる。
 ** JWT署名用の証明書は、90日の有効期限を持つコントローラによって自動的に作成され、自動的にローテーションされます。
 ** Manager、REST API、レジストリ・アダプター証明書の自動生成には、{product-name} Helmバージョン2.6.3以降を使用したHelmベースのインストールを使用する必要があります。
 ** yaml ベースの配置では、配置中に置き換えなければ組み込み証明書が引き続き使用されます。ただし、これらの証明書を置き換えることをお勧めします(次行を参照)。
 ** 以前のリリースまたはyamlベースの展開では、手動によるxref:replacecert.adoc[証明書の交換]も引き続きサポートされ、推奨されます。説明については、https://github.com/neuvector/neuvector/security/advisories/GHSA-622h-h2p8-743x[こちら]の{product-name} GitHubセキュリティアドバイザリを参照してください。
 ** ユーザー提供の証明書の使用は、Helmベースとyamlベースの両方のデプロイメントで従来通りサポートされます。
* カスタム・コンプライアンス・スクリプトに対する追加コントロールを追加します。デフォルトでは、ControllerとEnforcerに環境変数CUSTOM_CHECK_CONTROLが追加されていない限り、カスタムスクリプトの追加が許可されるようになりました。値は "disable " （ デフォルト、許可されていない ） 、 "strict " （ 管理者ロールのみ ） 、 "loose " （ 管理者、コンプライアンス、ランタイムポリシーロール）のいずれかです。
* LDAPインジェクションの防止:ユーザー名フィールドはエスケープされます。

==== 拡張機能

* SYSLOGが送信したCVE結果にスキャンデータを追加し、階層型スキャンに対応
* CVEデータベースのスキャンにNVD API 2.0をサポート
* 資産->コンテナの詳細にコンテナイメージのビルド日を記載
* ネットワークルールのソートを調整：ネットワークルールビューではソートを無効にしますが、グループビューではネットワークルールのソートを有効にします。
* Enforcer THRT_SSL_TLS_1DOT0, THRT_SSL_TLS_1DOT1に環境変数を指定してTLS 1.0およびTLS 1.1の検出/アラートを有効/無効にします。デフォルトでは無効になっています。
* ControllerとEnforcerの環境変数AUTO_PROFILE_COLLECTを追加して、メモリプレッシャーイベントの調査時にメモリ使用状況をキャプチャするのを支援します。値=1を設定すると有効になります。
* アドミッションコントロールに対する構成評価では、1回のスキャンですべての違反が表示されるはずです。
* レスポンスルールにCVEレポート基準のオプションを追加。例1 - "cve-high-with-fix:X"の意味は、次のとおりです。の#(修正済みの高脆弱性)>=×のときに、レスポンスルールを発動します。例2 - "cve-high-with-fix:X/Y"の意味は、次のとおりです。の#(Y日前に報告し、修正済みの高脆弱性)>=×のときに、レスポンスルールを発動します。

==== バグ修正

* グループポリシーのエクスポートで実際のYAMLの内容が返されない
* 専用機能で名前空間の剪定を改善
* {product-name}名前空間ユーザーはアセット-->名前空間を参照できない
* CRDの名前空間が既に削除されている場合、CRD CREATE/UPDATEリクエストの処理を省略する
* 名前空間の削除後に正常にプルーニングできない CRD グループの一部に対する回避策を提供する。

=== 5.2.1 August 2023

==== 拡張機能

* SYSLOGメッセージで階層化されたスキャン結果と追加のCVEデータを報告します。これは、[設定]->の[構成]->の[SYSLOG]のチェックボックスで有効にします。
* エクスポートされたcsvコンプライアンスレポートでNIST 800-53マッピング（ドッキングCISベンチマークへの）をエクスポート
* 画像署名検証におけるプロキシ設定に対応
* ダウンロードしたCVEレポートに画像署名のスキャン結果を含める
* アドミッションコントロールポリシーのサポートポッド注釈。カスタム条件から利用できます。
* 脆弱性レポートの印刷をフィルタリングする「最終変更日」フィールドと、「脆弱性」ビューの「高度なフィルタ」を追加

==== バグ修正

* AWS課金(CSPアダプタ)サービスの初期{product-name}展開では、デフォルトパスワードでデフォルト管理者を作成しない。ユーザーは管理者のユーザー名とパスワードを作成するためにシークレットを使用する必要がある
* サイズが大きくなり、Kubernetesノードがクラッシュした.jsonファイルを修正
* SQLインジェクション検出ロジックの改善
* Helmのcrdチャートをインストールしてから{product-name}コアチャートをインストールすると、サービスアカウントが見つからない
* イメージスキャンI.4.1準拠結果が正しくない
* 脆弱性の詳細フィルタレポートで他のすべての名前空間の画像を表示

=== 5.2.0 July 2023

==== 拡張機能

* {product-name} APIアクセス用のトークンをサポートする。新しいAPIキーを作成するには、設定->ユーザー、APIキー...を参照してください。キーはデフォルトまたはカスタムロールに設定できます。
* {product-name}月次サポートサブスクリプションのAWS Marketplace PAYG課金をサポートする。ユーザーは、SUSEサポートによる{product-name}を購読できます。AWSアカウントに毎月課金され、前月の平均ノード数使用量に基づいて課金されます。詳細はhttps://open-docs.neuvector.com/deploying/awsmarketplace[こちら]。
* アドミッションコントロールのイメージ署名をサポートします。ユーザーは、Sigstore/Cosignとの統合により、イメージを本番環境に導入する前に、特定の当事者によって署名されていることを{product-name}に確認させることができます。新しいシグネチャアセットの作成については、「アセット->シグストア検証ツール」を参照してください。ルールは、基準イメージ署名やイメージシグストア検証器、またはその両方を使用して作成できます。
* 各アドミッション制御ルールで、監視または保護の独自のモードを使用できるようにします。監視モードの拒否アクションはアラート、保護モードの拒否アクションはブロックされます。許可アクションは影響を受けません。
* regexをサポートするには、[ポリシー]>[アドミッション制御]>[ユーザーとユーザーグループのルールの追加]で新しいregex演算子を追加します。サポート演算子は "matches ANY regex in" と "matches NONE regex in" です。
* リソース制限などのアドミッション制御基準のサポートを追加します。「リソース制限」に新しい基準が追加され、「カスタム基準」の設定で追加の基準がサポートされます。
* https://github.com/goharbor/pluggable-scanner-spec[プラグ可能スキャナインター]フェイスを介してハーバーレジストリから{product-name}スキャナを呼び出すことをサポートします。これにはコントローラへの接続の設定（APIの公開）が必要です。Harborアダプタはコントローラエンドポイントを呼び出してスキャンをトリガーし、プッシュで自動的にスキャンできます。尋問サービスは、定期的なスキャンに使用できます。フェデレーションプライマリコントローラからのスキャン結果がリモートクラスタに伝播されます。 NOTE:HTTPSベースのアダプタエンドポイントエラーに問題があります。「接続のテスト」エラーは無視してください。エラーが表示されていても動作します(証明書の検証をスキップします)。
* CVEルックアップのための検索可能なSaaSサービス。最新の{product-name}CVEデータベースを検索し、データベースに特定のCVEが存在するかどうかを確認します。このサービスは、{product-name} Prime（有料サポートサブスクリプション）のお客様がご利用いただけます。SCCポータルからサポートに連絡してアクセスしてください。
* ユーザーがネットワーク保護を無効にしても、WAF/DLPは機能したままにできる。「設定」->の「構成」で「ネットワークポリシーの有効化」を設定します。
* {product-name}コンポーネントごとに必要に応じて、特権の少ないサービスアカウントを使用します。変数 "`leastPrivilege`" が導入されました。デフォルトはfalseです。NOTE:5.2.0より前のリリースでこの変数を指定して現在のヘルムチャートを使用すると、正しく機能しません。
* CIS 1.5 5.1.5 勧告を満たすために、デフォルト以外のサービスアカウントにバインドする。
* 管理者が「設定」の「->ユーザー、APIキーとロール」でユーザーデフォルトの「セッションタイムアウト」を設定できるようにします。
* カスタマイズ可能なログインバナーとカスタマイズ可能なUIヘッダーテキストにより、規制や政府機関への導入に対応。設定の要件はxref:customui.adoc[、こちら]をご覧ください。
* TLS暗号化トランスポートのSYSLOGサポート。SYSLOGの設定->構成でTCP/TLSを選択します。
* Rancher Managerから{product-name}モニターヘルムチャートの展開を有効にします。
* レジストリスキャン用のURLバリデータでトップレベルドメインの上限を削除。
* golangの依存関係をスキャンします。実行時スキャンも含まれます。
* Debian 12 (Bookworm) の脆弱性スキャンに対応。
* 選択したレジストリの資産->レジストリで、設定されたレジストリ内のすべてのイメージのCVEをエクスポートするには、レジストリ/詳細のCSVエクスポートを追加します。
* {product-name}がx.509証明書フィールドに複数のADFS証明書を並列で設定できるようにする。
* 応答規則のコメントフィールドを追加して表示します。
* {product-name}がシステムコンテナと見なすものを環境変数で指定する。たとえば、Rancherとデフォルトの名前空間の場合、NV_SYSTEM_GROUPS=*cattle-system;default
* Kubernetes 1.27とOpenShift 4.12のサポートを追加

==== バグ修正

* エンフォーサー/コントローラログの繰り返しログを減らす。
* 複数のクラスタのページはレンダリングされません。
* 空グループの自動削除は、スケジュールに従って1時間ではなく、2時間で削除されます。
* 手動で許可したネットワークルールが適用されず、一時停止イメージに対する違反となる。
* 特定の初期条件でトラフィックを許可するネットワークルールであっても、SSL接続をブロックすること。
* 同期中のポリシー更新の問題により、許可されたネットワークルールでもセキュリティイベントが警告されます。
* カスタムグループトラフィックを外部に誤って関連付けるネットワークアクティビティ。
* 各ポッドにマウントされている名前空間のデフォルトサービスアカウントトークンは、特権が高すぎます。
* ネットワークルールを定義しているにもかかわらず、メモリ不足（OOM）エラーによりコンテナが停止した場合に、セキュリティイベント（誤検知）の下で違反がログに記録される。
* クラスタ内の管理対象外コンテナに対する検出と保護を無効化/有効化できます。ManagerのCLIで設定できます。

[,shell]
----
set system detect_unmanaged_wl status -h
Usage: cli set system detect_unmanaged_wl status [OPTIONS] {true|false}

  Enable/disable detect unmanaged container
----

==== その他

* ヘルムチャートに"leastPrivilege"設定を追加New_Service_Profile_Baselineのhelmオプションを追加。5.2用に新しいヘルムチャート（コア）バージョンが公開されています。
* HelmチャートのAWS Marketplace（課金アダプタ）連携設定を有効にします。
* configmapを更新して新機能をサポート（複数のADFS証明書、ゼロドリフト、New_Service_Profile_Baseline、SYSLOG TLS、ユーザータイムアウト）
* サポートされているKubernetesのバージョンを1.19以上にアップデートし、OpenShift 4.6以上（CRI-Oでは1.19以上）

=== 2023年5月1.3日

==== 拡張機能

* Microsoft .NET Frameworkをスキャンするための新しい脆弱性フィードを追加します。
* Prometheusエクスポータではスケーラビリティ向上のため、エンフォーサーの統計はデフォルトで無効になっています。
* ユーザビリティの向上：スキャナを使用して1枚の画像をスキャンし、結果を印刷します（下の例を参照）。
* アドミッションコントロールルールの基準にimagePullPolicyチェックを追加。
* CRDスキーマが古いときに警告メッセージを表示するようにした。

==== バグ修正

* 「ネットワークアクティビティ」画面でレンダリングされない、または正しくレンダリングされない。
* 空グループの自動削除は、スケジュールに従って1時間ではなく、2時間で削除されます。
* UIコンソールにコンプライアンスプロファイルが表示されない。
* セキュリティイベントの詳細フィルタに「エラー」レベルがありません。
* 特殊文字で保存されたパスワードは、今後の認証試行で失敗します。
* 要求が多い場合、複数のクラスタのページが正しく描画されません。
* レジストリの詳細（下部）ペインが更新されない。

==== スキャナのサンプル出力

[,shell]
----
Image: https://registry.hub.docker.comlibrary/alpine:3.4
Base OS: alpine:3.4.6
TOTAL: 6, HIGH: 1, MEDIUM: 5, LOW: 0, UNKNOWN: 0
┌─────────┬───────────────┬──────────┬───────────┬───────────────┬────────────┐
│ PACKAGE │ VULNERABILITY │ SEVERITY │ VERSION   │ FIXED VERSION │ PUBLISHED  │
├─────────┼───────────────┼──────────┼───────────┼───────────────┼────────────┤
│ openssl │ CVE-2018-0732 │ High     │ 1.0.2n-r0 │ 1.0.2o-r1     │ 2018-06-12 │
│         ├───────────────┼──────────┤           ├───────────────┼────────────┤
│         │ CVE-2018-0733 │ Medium   │           │ 1.0.2o-r0     │ 2018-03-27 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-0734 │          │           │ 1.0.2q-r0     │ 2018-10-30 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-0737 │          │           │ 1.0.2o-r2     │ 2018-04-16 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-0739 │          │           │ 1.0.2o-r0     │ 2018-03-27 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-5407 │          │           │ 1.0.2q-r0     │ 2018-11-15 │
└─────────┴───────────────┴──────────┴───────────┴───────────────┴────────────┘
----

=== 2023年3月12日

==== 拡張機能

* 仮想ホストベースのアドレスグループとポリシーマッチングによるネットワーク保護をサポートします。これにより、2つの異なるFQDNアドレスを同じIPアドレスに解決しても、FQDNごとに異なるルールを適用する必要があるというユースケースが可能になります。'`address=vh:xxx.yyy`' のカスタムグループを '`vh:`' インジケータを使用して新しく作成し、この保護を有効にすることができます。その後、ネットワークルールは、仮想ホスト名に基づいて（解決されたIPアドレスの代わりに）カスタムグループを'`送信元`'として使用し、仮想ホストに異なるルールを適用できます。
* 既存のコンテナを除外するコンプライアンスコンテナリスト。
* パターン内の単純なワイルドカードをサポートするようにDLPルールを強化する。
* cri-o 1.26+とOpenShift 4.11+のサポートを追加。
* gravatarをオプションにしてください。
* クラスタ名前空間リソースをコンソール/UIに表示する。
* ソースの重要度/分類（Red Hat、Ubuntu...など）をNVDの重要度スコアとともにコンソールに表示する。
* RancherとOpenShiftでSSO/RBACの無効化を許可しない。
* configMapに自動スキャンの有効化と未使用グループのエージングの削除を追加。
* csv/pdfに外部ソース/宛先のIPアドレスを含めることで暗黙の拒否違反を防ぐ
* コントローラとエンフォーサーのCPUおよびメモリ使用量に対するさまざまなパフォーマンスとスケーラビリティの最適化。

==== バグ修正

* GKE Container Optimized OS (COS) ノードで保護モードの場合のアプリケーションの速度低下を修正。
* SUSE Linux (SLES) 15.4 CVE がスキャナーで一致していない。今回の修正により、脆弱性の深刻度がフィードで提供されていれば、NVDレコードが欠落していてもデータベースに脆弱性が追加される。CVEスコアのない脆弱性が含まれている可能性があります。

==== その他

* Helmhttps://github.com/neuvector/neuvector-helm/pull/237.のアドミッションコントロールCRDオプションを強化
* Helmチャートに新しい強制環境変数を追加します。

=== 2023年2月1日

==== 拡張機能

* 検出された脆弱性の syslog-event に情報として"`パッケージ`"を追加します。
* Enforcer環境変数ENF_NETPOLICY_PULL_INTERVALを追加 - ネットワークトラフィックとポリシーの更新/再計算によるEnforcerによる結果のリソース消費を減らすための秒単位の値（推奨値60）。（注：これは2023年8月まで文書化されていない追加である）。

[,yaml]
----
           - name: ENF_NETPOLICY_PULL_INTERVAL
             value: "60"   <== regulate the pulling gap by 60 seconds
----

==== バグ修正

* 空のグループ削除エラー「オブジェクトが見つかりません」
* 同じコンテナ内のトラフィックに対するアラート/ブロッキング
* 許可ルールが適用されているシステム出力トラフィックに対する予期しない暗黙的な違反
* {product-name} 4.xリリースからアップグレードする際、ポッドグループメンバシップが正しくないと予期しないポリシー違反が発生する
* 要求に余分なエンコーディング文字が含まれていると、ADFSでOIDC認証が失敗する
* dpによるポッドの作成と削除によるメモリ使用量の増加
* Managerを含むいくつかのCVEを修正するalpineのアップデート:CVE-2022-37454、CVE-2022-42919、CVE-2022-45061、CVE-2021-46848; Enforcer:CVE-2022-43551, CVE-2022-43552
* UIに関する様々なバグを修正

==== その他

* Helmチャートが更新され、社内通信用の証明書の置き換えが可能に

=== 2022年12月5日

==== 拡張機能

* 一元化されたマルチクラスタスキャン（CVE）データベース。プライマリ(マスター)クラスタは、連合レジストリとして指定されたレジストリ/レポジトリをスキャンできます。これらのレジストリからのスキャン結果は、すべての管理対象(リモート)クラスタに同期されます。これにより、管理対象クラスタのコンソールにスキャン結果を表示するだけでなく、管理対象クラスタのアドミッション制御ルールにスキャン結果を使用できます。レジストリは、各クラスタではなく1回スキャンするだけで済み、CPU/メモリとネットワーク帯域幅の使用量を削減できます。
* アドミッションコントロールルールの強化：
 ** アドミッション制御ルールのカスタム基準。ユーザーがポッドに関連するすべてのフィールドでリソース基準を定義し、ルールで使用できるようにします。たとえば、item.metadata.annotationsKeyには'neuvector'、item.metadata.name='xyzzy'などが含まれます。
 ** Podを導入する際に、サービスアカウントの高リスクRBAC設定をチェックする基準を追加します。これらには、基準「ワークロードリソースの任意のアクション」、「RBACに対する任意のアクション」、「ワークロードリソースの作成」、「シークレットの一覧表示」、「コンテナへのexec」が含まれる。
 ** アドミッション制御ルールのモジュールに意味バージョン比較を追加します。これにより、>または<演算子をルール内のバージョン番号に適用できます(例えば、モジュールのcurl<6.2.0の展開を許可しません)。これにより、インストールされているパッケージの特定のバージョンチェックが可能になります。
 ** Kubernetes 1.25以降でサポートされているPod Security Admission（PSA）のアドミッション制御ルールを追加する。
* 新しい環境変数 NO_DEFAULT_ADMIN を追加します。この変数を有効にすると、「admin」ユーザーが作成されません。Rancher SSO連携のデフォルトとして使用されます。有効でない場合、ユーザに永続的に警告し、デフォルトの管理パスワードがデフォルトから変更されていない場合は、変更するようにイベントを記録します。
* ログイン失敗後のログインをブロックする設定がデフォルトになりました。デフォルト値は5回で、[設定]->の[ユーザーと役割->のパスワードプロファイル]で設定できます。
* ENF_NO_SYSTEM_PROFILES パフォーマンスチューニング用の新しい環境変数を追加します。値:"1".有効にすると、プロセスモニタとファイルモニタが無効になります。学習プロセス、プロファイルモード、プロセス/ファイル(パッケージ)インシデント、ファイルアクティビティモニタは実行されません。これにより、CPU/メモリリソースの使用量とファイル操作が削減されます。
* スキャナポッドのカスタム自動スケーリング設定を追加します。値は遅延、即時、無効です。重要:スキャナの自動スケーリングは、スキャナがOpenShiftオペレータで展開されている場合、オペレータは常にポッドの数を設定値に変更するため、サポートされていません。
 ** *_遅延戦略：_*
  *** リードコントローラーが90秒以上"タスクカウント">0を継続的に確認した場合、maxScannerPodsにまだ達していないときは新しいスキャナーポッドが開始される
  *** リードコントローラーが180秒以上「タスクカウント」が0であると継続的に認識した場合、minScannerPodsにまだ達していないと1つのスキャナーポッドを縮小する
 ** *_即時戦略：_*
  *** リードコントローラーが"タスク数">0を確認するたびに、maxScannerPodsにまだ達していない場合は新しいスキャナーポッドが開始される
  *** リードコントローラーが180秒以上「タスクカウント」が0であると継続的に認識した場合、minScannerPodsにまだ達していないと1つのスキャナーポッドを縮小する
* Rancherの名前空間ラベルを含む名前空間ラベルをカスタムグループが使用できるようになりました。一般に、ポッドと名前空間のラベルをカスタムグループに追加できるようになりました。
* 選択した名前空間、グループをネットワークアクティビティビューで非表示にする機能を追加
* Cilium cniをフルサポート。
* OpenShift 4.9と4.10をフルサポート。
* https://github.com/openzerotrust/openzerotrust.io.の{product-name}/オープンゼロトラスト(OZT)プロジェクトでビルドツールが利用可能に
* {product-name}では、https://github.com/neuvector/manifests/tree/main/versions.時にコントローラ、マネージャ、エンフォースメントの各バージョンのバージョンIDとSHA256ダイジェストが一覧表示されるようになりました
* 導入時に匿名のテレメトリデータ（ノード数、グループ数、ルール数）がRancherクラウドサービスに報告されるようになり、プロジェクトチームの利用状況把握を支援する。UI、configMap（No_Telemetry_Report）またはREST APIで無効化（オプトアウト）できます。
* (2023年1月追記)。IstioによるServiceEntryベースのネットワークポリシーのサポート。Istioで宣言されたServiceEntry宛先へのポッドに対して、バージョン5.1.0で出力ネットワークポリシー適用機能が追加されました。通常、ServiceEntryはDNS名で参照される外部サービスが宛先IPにどのように解決されるかを定義する。v5.1より前のバージョンでは、{product-name}はServiceEntryへの接続に関するルールを検出して適用できなかったため、すべての接続がExternalに分類されていました。5.1では、特定のServiceEntryの宛先にルールを適用できます。重要:Istioベースの展開でv5.1にアップグレードする場合は、これらの接続を許可し、違反アラートを回避するために新しいルールを作成する必要があります。アップグレード後、許可ルールが存在しない場合は、新たに表示されるトラフィックに対して暗黙の違反が報告されます。新しい交通ルールは、ディスカバーモードで学習して自動作成できます。このトラフィックを許可するには、グループをディスカバリモードにするか、この宛先へのアドレス（またはDNS名）と新しいネットワークルールを持つカスタムグループを作成してトラフィックを許可します。NOTE:5.1.0には、拒否違反によって報告された宛先にバグがあり、正しい宛先を表していません。 バグ報告では、server_nameとclient_nameの両方が同じです。 この問題は、今後のパッチリリースで対処される予定です。

==== バグ修正

* ローリングアップデート中に作成される不要なシスベンチマークデータからコントローラのメモリ消費量を削減します。この問題は、新規導入では発生しません。
* 設定画面からライセンスを削除（不要）。

=== 5.0.6-s1 March, 2023

==== バグ修正

* curlのCVEを修正するalpineパッケージを更新（CVE-2023-23914、CVE-2023-23915、CVE-2023-23916を含む）

=== 2023年2月5日

==== バグ修正

* dpMsgConnectionでメモリ使用量が多い
* 管理対象外のワークロードを持つ学習済みポリシールールが多数ある場合、エンフォーサーのdpプロセスでメモリ使用量が多くなる(メモリリーク)
* コンテナでトラフィックをスニファリングすると、tcpdumpが正常に起動できない
* Managerを含むいくつかのCVEを修正するalpineのアップデート:CVE-2022-37454、CVE-2022-42919、CVE-2022-45061、CVE-2021-46848; Enforcer:CVE-2022-43551, CVE-2022-43552

=== 2022年11月5日

==== バグ修正

* 5.0.xにアップグレードすると、異なるバージョンを実行しているマネージャ、コントローラ、エンフォーサーに関するエラーメッセージが表示されます。
* dpキルの結果、ゴールーチンパニックを経験している執行者。 WebUI はオンラインとして強制力を反映しません。
* NV.Protectグループで予期しないプロセス.プロファイル.違反インシデントが発生しました。どのコマンドがcoreos上で実行されるか確認してください。

=== 2022年10月5日

==== セキュリティアップデート

* alpine をアップデートし、Manager expat ライブラリの重大な CVE-2022-40674 と、その他のマイナーな CVE を削除。

==== 拡張機能

* Antrea CNIのサポートを追加

==== バグ修正

* NV.Protectグループの予期しないprocess.profile.violationインシデントを修正しました。
* マネージャUIアクセス時にSSLが無効になっている場合、ユーザパスワードがマネージャログに出力されます。

=== 2022年9月0.3日

==== 拡張機能

* 永続ボリュームからの再起動に成功したら、EULAを表示しない。
* コンテナスキャンの結果をスキップするには、脆弱性プロファイル設定の画像フィルタを使用します。
* https://github.com/neuvector/neuvector-image-scan-action.時のGitHubアクションでスキャナをサポート
* シークレットスキャンを無効にしてCISベンチマークを実行するためのEnforcer環境変数を追加する

[,yaml]
----
    env:
      - name: ENF_NO_SECRET_SCANS  (available after v4.4.4)
        value: "1"
      - name: ENF_NO_AUTO_BENCHMARK (after v5.0.3)
        value: "1"
----

==== バグ修正

* Enforcerが時々起動できない。
* マルチクラスタフェデレーション環境での接続リーク。
* セキュリティリスク->コンプライアンスでコンプライアンスページが読み込まれないことがある

=== <1/>2022年7月

==== 拡張機能

* Rancher の強化と SELinux クラスタがサポートされています。

==== バグ修正

* k3sシステムでエージェントがCPU使用率を高く処理する。
* AD LDAP グループが 5.0 へのアップグレード後に正常に動作しない。
* error=開いているファイルが多すぎる(rke2/cilium)ため、Enforcerは再実行を繰り返します。
* サポートログが正常にダウンロードできません。

=== 2022年6月0.1日

==== 拡張機能

* openSUSE Leap OSの脆弱性スキャンをサポート（スキャナイメージ内 ） 。
* スキャナ：イメージレポジトリの再構築中にワイプアウト属性を実装。
* {product-name}の導入とSELinux対応ホストのサポートを確認します。Helmチャートが更新されるまでの間の暫定パッチ適用の詳細については、以下を参照してください。
* Rancher UIでフィーチャーチャートとパートナーチャートをより目立つように区別します。+ Rancher Helmチャートのnginxの入力アノテーションを改善しました。追加/更新
ingress.kubernetes.io/protocol: https to nginx.ingress.kubernetes.io/backend-protocol:"HTTPS".
* 現在のOpenShift Operatorはapiとフェデレーションサービスのパススルールートをサポートしています。エッジ終端タイプと再暗号化ルート終端タイプをサポートするために、追加の Helm Value パラメータが追加されました。

==== バグ修正

* AKSクラスタがアドミッション制御Webhookに予期しないキーを追加する可能性がある。
* Enforcerがコンテナランタイム1.64のk8s 1.24クラスタで動作しなくなります。別に、強制起動に失敗することがある。
* クラスタをフィードマスターに昇格する管理者ロールユーザー(ローカルユーザーまたはSSO)は、自動的にフィード管理者ロールに昇格する必要があります。
* Rancherのデフォルトadminを使用してマスタークラスタの{product-name}にssoすると、{product-name}ログインロールはfeedAdminではなくadminになります。
* いくつかのgoroutineのクラッシュを修正
* ノードに関連付けられていないホストIPからの暗黙の違反。
* ComplianceProfileにPCIタグが表示されない。
* LDAPグループマッピングが表示されないことがあります。
* リスク確認および改善ツールは、エラーメッセージ"システム構成の更新に失敗しました：リクエストの形式が間違っています」と表示されます。
* OKD 3.11 - Clusterrole エラーは存在していても表示する。

==== CVEの対処方法

* すべての画像でncursesパッケージに高いCVE-2022-29458 cveが見つかりました。
* Updater イメージの curl パッケージに高い CVE-2022-27778 と CVE-2022-27782 が見つかりました。

==== SELinuxサポートの詳細

{product-name}は、SELinux対応クラスタを導入して機能させるために、追加の設定は必要ありません。RHEL 8.5ベースのSELinux対応RKE2強化クラスタへの{product-name}の導入をテスト。PSPが有効であれば正常に{product-name}を導入し、マネージャとスキャナの導入にパッチを適用。次のチャートリリースでは、以下の問題が修正される予定です。

Rancherチャートからpspを有効にするための例を添付し、マネージャとスキャナの展開にパッチを適用するためのコマンドの下に示しています。patchコマンドのユーザーIDは任意の数字にすることができます。

[,shell]
----
kubectl patch deploy -ncattle-neuvector-system neuvector-scanner-pod --patch '{"spec":{"template":{"spec":{"securityContext":{"runAsUser": 5400}}}}}'
kubectl patch deploy -ncattle-neuvector-system neuvector-manager-pod --patch '{"spec":{"template":{"spec":{"securityContext":{"runAsUser": 5400}}}}}'
----

PSPを有効にする例：

[,shell]
----
[neuvector@localhost nv]$ getenforce
Enforcing
[neuvector@localhost nv]$ sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      33

[neuvector@localhost nv]$ kk get psp
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
NAME                      PRIV    CAPS                                      SELINUX    RUNASUSER          FSGROUP     SUPGROUP    READONLYROOTFS   VOLUMES
global-restricted-psp     false                                             RunAsAny   MustRunAsNonRoot   MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
neuvector-binding-psp     true    SYS_ADMIN,NET_ADMIN,SYS_PTRACE,IPC_LOCK   RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
system-unrestricted-psp   true    *                                         RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
[neuvector@localhost nv]$ nvpo.sh
NAME                                        READY   STATUS    RESTARTS   AGE     IP           NODE                    NOMINATED NODE   READINESS GATES
neuvector-controller-pod-54f69f7f9c-6h822   1/1     Running   0          5m51s   10.42.0.29   localhost.localdomain   <none>           <none>
neuvector-enforcer-pod-jz77b                1/1     Running   0          5m51s   10.42.0.30   localhost.localdomain   <none>           <none>
neuvector-manager-pod-588488bb78-p6vf9      1/1     Running   0          111s    10.42.0.32   localhost.localdomain   <none>           <none>
neuvector-scanner-pod-87474dcff-s8vgt       1/1     Running   0          114s    10.42.0.31   localhost.localdomain   <none>           <none>
----

=== 5.0.0 一般提供 (GA) リリース 2022年5月

==== 拡張機能

* グループモードの自動昇格。経過時間と基準に基づいて、グループの保護モードに昇格します。CRDで作成したグループには適用されません。この機能により、新しいアプリケーションをDiscoverで一定期間実行し、動作と{product-name}を学習してNetworkとProcessの許可リストルールを作成し、自動的にMonitor、Protectモードに移行します。監視対象として検出する基準：グループ内の少なくとも1つのライブポッドのすべてのネットワークおよびプロセスアクティビティを学習するための経過時間。保護する監視基準:グループに設定された期間のセキュリティイベント（ネットワーク、プロセスなど）はありません。
* Rancher 2.6.5アプリとマーケットプレイスチャートに対応。cattle-neuvector-system名前空間にデプロイし、Rancherから{product-name}へのSSOを有効にします。注意:Rancherからの以前の展開（例：パートナーカタログチャート、バージョン1.9.x以前）を新しいチャートにアップデートするには、完全に削除する必要があります。
* SUSE Linux（SLE、SLES）、Microsoft Marinerのスキャンをサポート
* ゼロドリフトプロセスとファイル保護。プロセスとファイルの保護のための新しいデフォルトモードです。ゼロドリフトは、元のコンテナイメージにある親プロセスから発生したプロセスのみを自動的に許可し、ファイルの更新や新規ファイルのインストールは許可しません。検出モードまたは監視モードの場合、ゼロドリフトは疑わしいプロセスまたはファイルアクティビティを警告します。保護モードでは、そのようなアクティビティをブロックします。ゼロドリフトでは、プロセスを学習したり、許可リストに追加したりする必要はありません。グループに対してゼロドリフトを無効にすると、代わりにグループに対してリストされているプロセスおよびファイルルールが有効になります。
* ネットワーク、プロセス/ファイルに対するポリシーモードの分割保護。「設定」->の「構成」で、ネットワークルールの適用のためにネットワーク保護モードを個別に設定できるグローバル設定が追加されました。これを有効にすると（デフォルトは無効）、すべてのネットワークルールが選択された保護モード（検出、監視、保護）になります。プロセス/ファイルルールは、［ポリシー->グループ］画面に表示されるように、そのグループの保護モードのままになります。このように、ネットワークルールを保護（ブロッキング）に設定し、プロセス/ファイルポリシーを監視に設定したり、その逆を行うことも可能です。
* WAFルール検出、強化されたDLPルール（ヘッダー、URL、フルパケット）。Webアプリケーションポッドへの入力接続だけでなく、apiセキュリティを強制するためのapiサービスへの送信接続にも使用されます。
* WAF、DLP、アドミッションコントロール用のCRD。注:追加のクラスタの役割バインディング/権限が必要になりました。KubernetesとOpenShiftの導入セクションを参照してください。CRDによるアドミッションコントロールのCRDインポート/エクスポートとバージョン管理をサポート。
* Rancher Managerを通じて{product-name}コンソールを起動するRancher SSO統合。この機能は、{product-name}コンテナが Rancher を通じてデプロイされている場合にのみ使用できます。このデプロイメントは、ミラー化された Rancher リポジトリ (例: rancher/mirrored-neuvector-controller:5.0.0) から取得し、 cattle-neuvector-system 名前空間にデプロイします。NOTE:Rancherリリース2.6.5以降（2022年5月）の更新が必要で、現時点では管理者ロールとクラスタ所有者ロールのみがサポートされています。
* RKE2への展開をサポート。
* プロキシを介したクラスタのフェデレーション(マルチクラスタマネージャ)のサポート。[設定]->の[構成]でプロキシを構成し、フェデレーション接続を構成するときにプロキシを有効にします。
* 必要なrbacのclusterrole/bindingsを監視し、不足している場合はイベントやUIでアラートを出す。
* アドミッション制御ルールにおけるリソース制限のサポート基準。
* WebhookのMicrosoft Teamsフォーマットに対応。
* マップされたロールグループの下でAD/LDAPネストグループをサポート。
* Openshift の IDP でグループ情報を持つ clusterrolebindings または rolebindings をサポートする。
* ネットワークルールとアドミッションコントロールルールをフェデレーションルールに昇格できるようにします。

==== バグ修正

* ワーカーフェデレーションロールのバックアップが非フェデレーションクラスタに復元される問題を修正
* セキュリティリスク->の脆弱性における多数のCVEのページ読み込み時間を改善
* ユーザーが[ポリシー->グループ]メニューですべてのグループを選択したときにモードを切り替えることを許可する。Nodesグループも選択されている場合に警告する。
* 同じ名前のコンプライアンスチェック項目を折りたたみ、展開可能にします。
* gRPC通信のセキュリティを強化する。
* 修正: rke2セットアップで正しいワークロード特権情報を取得できませんでした。
* openSUSE Leap 15.3 (k8s/crio) のサポートに関する問題を修正

==== その他のアップデート

* ヘルムチャート appVersionを5.0.0に、チャートバージョンを2.2.0にアップデート
* サーバーレススキャン機能/メニューを削除。
* Jfrog Xrayのスキャン結果統合のサポートを削除（工場レジストリスキャンは引き続きサポート）。
* ECSへの導入のサポートは終了しました。allinoneはECS上でも展開できるはずですが、手順や設定のドキュメントはサポートされなくなりました。

=== {product-name}4.xから5.xへのアップグレード(5.2.xより前)

[NOTE]
====
以下の手順は、5.0.xおよび5.1.xへのアップグレードに適用されます。5.2.x では、サービスアカウントとバインディングが変更されています。アップグレードを計画するには、xref:kubernetes.adoc#_deploy_suse_security[確認]する必要があります。
====


Helmをお使いの場合は、{product-name} Helmチャート2.0.0以降にアップデートしてください。OpenShiftでOperatorまたはHelmのインストールを更新する場合は、以下の注を参照してください。

. 古いneuvector-binding-customresourcedefinitionクラスタロールを削除

[,shell]
----
kubectl delete clusterrole neuvector-binding-customresourcedefinition
----

. neuvector-binding-customresourcedefinition clusterrole に新しい更新動詞を適用する

[,shell]
----
kubectl create clusterrole neuvector-binding-customresourcedefinition --verb=watch,create,get,update --resource=customresourcedefinitions
----

. Kubernetes 1.19+の古いcrdスキーマを削除

[,shell]
----
kubectl delete -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/crd-k8s-1.19.yaml
----

. Kubernetes 1.19+用の新しいcrdスキーマを作成する

[,shell]
----
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/crd-k8s-1.19.yaml
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/waf-crd-k8s-1.19.yaml
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/dlp-crd-k8s-1.19.yaml
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/admission-crd-k8s-1.19.yaml
----

. Admission、DLP、WAFのクラスタロールとクラスタロールバインディングを新規作成する

[,shell]
----
kubectl create clusterrole neuvector-binding-nvwafsecurityrules --verb=list,delete --resource=nvwafsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvwafsecurityrules --clusterrole=neuvector-binding-nvwafsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvadmissioncontrolsecurityrules --verb=list,delete --resource=nvadmissioncontrolsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvadmissioncontrolsecurityrules --clusterrole=neuvector-binding-nvadmissioncontrolsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvdlpsecurityrules --verb=list,delete --resource=nvdlpsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvdlpsecurityrules --clusterrole=neuvector-binding-nvdlpsecurityrules --serviceaccount=neuvector:default
----

. Dockerハブ(docker.io)から{product-name}イメージを引き出すためのイメージ名とパスを更新します。例:

* neuvector/manager:5.0.0
* neuvector/controller:5.0.0
* neuvector/enforcer:5.0.0
* neuvector/scanner:latest
* neuvector/updater:latest

オプションで、Helmチャート、デプロイメントyaml、configmap、スクリプトなどで{product-name}ライセンスとレジストリシークレットへの参照を削除します。これらの参照は、イメージのプルや{product-name}の使用を開始するために不要になります。

*SCCとオペレータ/ヘルム経由のアップグレードに関する注意*

新規導入では、Operatorバージョン1.3.4以降により、特権SCCが導入yamlで指定されたサービスアカウントに追加されます。{product-name} Operatorを以前のバージョンから1.3.4へ、またはHelmを2.0.0へアップグレードする場合は、特権SCCを削除してからアップグレードしてください。

[,shell]
----
oc delete rolebinding -n neuvector system:openshift:scc:privileged
----

==== 2022年4月にベータ版1をリリース

* グループモードの自動昇格など、機能を完備。経過時間と基準に基づいて、グループの保護モードに昇格します。CRDで作成したグループには適用されません。この機能により、新しいアプリケーションをDiscoverで一定期間実行し、動作と{product-name}を学習してNetworkとProcessの許可リストルールを作成し、自動的にMonitor、Protectモードに移行します。監視対象として検出する基準：グループ内の少なくとも1つのライブポッドのすべてのネットワークおよびプロセスアクティビティを学習するための経過時間。保護する監視基準:グループに設定された期間のセキュリティイベント（ネットワーク、プロセスなど）はありません。
* Rancher 2.6.5アプリとマーケットプレイスチャートに対応。cattle-neuvector-system名前空間にデプロイし、Rancherから{product-name}へのSSOを有効にします。注意:Rancherからの以前の展開（例：パートナーカタログチャート、バージョン1.9.x以前）を新しいチャートにアップデートするには、完全に削除する必要があります。
* エンフォーサー、マネージャー、コントローラーのタグ：5.0.0-b1（例：ニューベクタ/コントローラ：5.0.0-b1）

==== Preview.3版を2022年3月にリリース

[CAUTION]
.重要
====

CRD WAF、DLP、アドミッションコントロールの新機能の以前のプレビュー展開を更新するには、CRD yamlを更新し、新しいrbac/ロールバインディングを追加してください。

[,shell]
----
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/latest/crd-k8s-1.19.yaml
kubectl create clusterrole neuvector-binding-nvwafsecurityrules --verb=list,delete --resource=nvwafsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvwafsecurityrules --clusterrole=neuvector-binding-nvwafsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvadmissioncontrolsecurityrules --verb=list,delete --resource=nvadmissioncontrolsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvadmissioncontrolsecurityrules --clusterrole=neuvector-binding-nvadmissioncontrolsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvdlpsecurityrules --verb=list,delete --resource=nvdlpsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvdlpsecurityrules --clusterrole=neuvector-binding-nvdlpsecurityrules --serviceaccount=neuvector:default
----
====


==== 拡張機能

* SUSE Linux（SLE、SLES）、Microsoft Marinerのスキャンをサポート
* ゼロドリフトプロセスとファイル保護。プロセスとファイルの保護のための新しいデフォルトモードです。ゼロドリフトは、元のコンテナイメージにある親プロセスから発生したプロセスのみを自動的に許可し、ファイルの更新や新規ファイルのインストールは許可しません。検出モードまたは監視モードの場合、ゼロドリフトは疑わしいプロセスまたはファイルアクティビティを警告します。保護モードでは、そのようなアクティビティをブロックします。ゼロドリフトでは、プロセスを学習したり、許可リストに追加したりする必要はありません。グループに対してゼロドリフトを無効にすると、代わりにグループに対してリストされているプロセスおよびファイルルールが有効になります。
* ネットワーク、プロセス/ファイルに対するポリシーモードの分割保護。「設定」->の「構成」で、ネットワークルールの適用のためにネットワーク保護モードを個別に設定できるグローバル設定が追加されました。これを有効にすると（デフォルトは無効）、すべてのネットワークルールが選択された保護モード（検出、監視、保護）になります。プロセス/ファイルルールは、［ポリシー->グループ］画面に表示されるように、そのグループの保護モードのままになります。このように、ネットワークルールを保護（ブロッキング）に設定し、プロセス/ファイルポリシーを監視に設定したり、その逆を行うことも可能です。
* WAFルール検出、強化されたDLPルール（ヘッダー、URL、フルパケット）
* WAF、DLP、アドミッションコントロール用のCRD。注:追加のクラスタの役割バインディング/権限が必要になりました。KubernetesとOpenShiftの導入セクションを参照してください。CRDによるアドミッションコントロールのCRDインポート/エクスポートとバージョン管理をサポート。
* Rancher Managerを通じて{product-name}コンソールを起動するRancher SSO統合。この機能は、{product-name}コンテナが Rancher を通じてデプロイされている場合にのみ使用できます。NOTE:Rancherのアップデート版が必要です(日付/バージョン未定)。
* RKE2への展開をサポート。
* プロキシを介したクラスタのフェデレーション(マルチクラスタマネージャ)のサポート。
* 必要なrbacのclusterrole/bindingsを監視し、不足している場合はイベントやUIでアラートを出す。
* アドミッション制御ルールにおけるリソース制限のサポート基準。

==== バグ修正

* ワーカーフェデレーションロールのバックアップが非フェデレーションクラスタに復元される問題を修正

==== Preview.2版をリリース 2022年2月

* ソースのファイルとライセンスが若干変更されました。機能の追加はありません。

==== AWS ECSへのデプロイのサポートは非推奨

ECSへの導入のサポートは終了しました。allinoneはECS上でも展開できるはずですが、手順や設定のドキュメントはサポートされなくなりました。

=== 5.0 'Tech Preview' 2022年1月

==== 拡張機能

* {product-name} 5.0オープンソース版のサポートされていない「テクニカルプレビュー」バージョンの最初のリリース。
* OWASP Top-10、ヘッダーまたはボディ内のネットワーク攻撃を検出するためのWAFに似たルールのサポートを追加します。シグネチャの CRD 定義や適切なグループへの適用のサポートが含まれる。
* サーバレススキャン機能を削除します。

==== バグ修正

* TBD

==== その他

* ヘルムチャートv1.8.9は、5.0.0導入用に公開されています。これを5.0.0のプレビューバージョンで使用する場合は、values.ymlに以下の変更を加える必要があります。
 ** docker.ioにレジストリを更新
 ** Dockerハブで画像名/タグをプレビュー版に更新
 ** imagePullSecretsを空のままにする
