= Restauration de la configuration de {product-name} 
:revdate1: 2024-09-27
:page-revdate: {revdate}
:page-opendocs-origin: /02.deploying/11.restore/11.restore.md
:page-opendocs-slug: /déploiement/restauration

== Restauration de la configuration de {product-name} 

Une sauvegarde de la configuration de {product-name} peut être appliquée pour restaurer une configuration antérieure de {product-name}. Le fichier de sauvegarde peut être généré manuellement ou importé à partir de la console dans Paramètres -> Configuration, en choisissant toute la configuration (par exemple, les configurations de registre, les intégrations, les autres paramètres et la politique) ou la politique uniquement (par exemple, les règles/la politique de sécurité). L'API rest peut également être utilisée pour sauvegarder automatiquement la configuration, comme le montre cet xref:automation.adoc#_exportimport_configuration_file[exemple.]

Les événements de grappes où tous les contrôleurs cessent de fonctionner, perdant ainsi l'état de la configuration en temps réel, peuvent être automatiquement restaurés lorsque le xref:production.adoc#_backups_and_persistent_data[stockage persistant] a été correctement configuré.

[NOTE]
====
{product-name} ne prend pas en charge la restauration partielle des objets (par exemple, les règles de réseau uniquement) ni la restauration horodatée (par exemple, la restauration à partir d'instantanés de la date et de l'heure). Veuillez utiliser des xref:automation.adoc#_exportimport_configuration_file[scripts d'automatisation] pour sauvegarder régulièrement les fichiers de configuration et gérer les horodatages.
====

[CAUTION]
====
Les fichiers de configuration de sauvegarde ne doivent en aucun cas être modifiés. Toute modification de ceux-ci par rapport à leur état exporté pourrait entraîner des erreurs de restauration et un résultat imprévisible.
====

[IMPORTANT]
====
Les fichiers de configuration sauvegardés doivent être utilisés pour restaurer l'état de {product-name} sur le même cluster que celui à partir duquel ils ont été exportés. L'application d'un fichier de configuration de sauvegarde provenant d'un autre cluster peut donner des résultats imprévisibles.
====

=== Paramètres de haute disponibilité recommandés

La sauvegarde et la restauration manuelles de la configuration ne doivent être envisagées qu'en dernier recours. Les étapes suivantes sont recommandées pour la haute disponibilité.

. Utiliser Helm avec un ConfigMap pour le déploiement et la configuration initiaux.
. Utiliser les CRD pour définir des politiques telles que le réseau/processus, le contrôle d'admission et d'autres règles.
. Exécutez plusieurs contrôleurs (au moins 3) pour synchroniser automatiquement la configuration entre les pods en cours d'exécution, et assurez-vous qu'ils s'exécutent sur des hôtes différents.
. Configurer le stockage persistant (dans le cadre de l'étape 1) pour récupérer les défaillances de l'ensemble de la grappe où tous les contrôleurs cessent de fonctionner.
. Sauvegarder régulièrement la configuration dans des fichiers de sauvegarde horodatés.
. Restaurer en dernier recours la configuration {product-name} d'un cluster à partir d'un fichier de sauvegarde, en appliquant après la restauration tous les CRD nouveaux ou modifiés depuis la sauvegarde précédente.
