= Notas de la versión 5.x
:revdate: 2025-08-26
:page-revdate: {revdate}
:page-opendocs-origin: /14.releasenotes/01.5x/01.5x.md
:page-opendocs-slug:  /releasenotes/5x

== Notas de la versión 5.x

[NOTE]
====
Para recibir notificaciones por correo electrónico sobre nuevos lanzamientos, suscríbase a esta lista de correo de SUSE: https://lists.suse.com/mailman/listinfo/neuvector-updates
====

=== 5.4.6 Agosto de 2025

==== Nuevas funciones

* *NVSHAS-6733*: Exportar reglas de respuesta como CRD.
* *NVSHAS-9899*: Las alertas de perfil de proceso de NeuVector para servicios Java contienen datos confidenciales.
* *NVSHAS-9990*: Adoptar un nuevo algoritmo hash para las contraseñas de los usuarios.
* *NVSHAS-9968*: Admite la configuración de la contraseña predeterminada de la cuenta de administrador.

==== Errores corregidos

* *NVSHAS-10062*: El administrador no muestra ERROR cuando no se puede crear una contraseña de administrador durante el primer inicio de sesión.
* *NVSHAS-10041*: La operación de federación falló debido a "datos inválidos" al configurar la federación a través de ConfigMap.
* *NVSHAS-10018*: Neuvector no está escaneando todas las imágenes en el Registro de GitLab.
* *NVSHAS-10017*: Alerta de seguridad de falso positivo relacionada con el proceso permitido.
* *NVSHAS-10001*: Las medidas de protección y monitorización “permanecen” después de la eliminación del grupo.
* *NVSHAS-9985*:	NeuVector (Fed Master) crea un problema para todas las solicitudes que vienen del exterior.
* *NVSHAS-9981*:	El evento de seguridad se activa cada vez que se agrega o cambia una nueva "Regla de perfil de proceso" en un grupo.

==== Avisos de seguridad

* https://github.com/neuvector/neuvector/security/advisories/GHSA-8pxw-9c75-6w56[La cuenta de administrador tiene una contraseña predeterminada insegura]
* https://github.com/neuvector/neuvector/security/advisories/GHSA-8ff6-pc43-jwv3[La gestión insegura de contraseñas es vulnerable a ataques arcoíris]
* https://github.com/neuvector/neuvector/security/advisories/GHSA-w54x-xfxg-4gxq[Un proceso con argumentos sensibles puede generar fugas]

Consulte el xref:cve.adoc[Aviso de seguridad y la documentación CVE] para obtener más información.

=== 5.4.5 Julio de 2025

==== Nuevas funciones

* *NVSHAS-9776*: Añadir tolerancia etcd en la tabla de Helm.

==== Correcciones de errores de programas

* *NVSHAS-9507*: El contenedor OCI no se escanea.
* *NVSHAS-9787*: Eliminar el registro del administrador innecesario.
* *NVSHAS-9788*: Refinar algoritmo para generar certificado.
* *NVSHAS-9789*: Eliminar el registro del administrador innecesario en la configuración del registro remoto.
* *NVSHAS-9867*: NeuVector muestra que `.NET Library System.Formats.Asn1 v8.013` está afectado por CVE 2024-38095.
* *NVSHAS-9883*: [quay.io] Los filtros comodín no funcionan para el registro de Docker.
* *NVSHAS-9911*: Escanear el repositorio mediante la API REST da como resultado un "mensaje" incorrecto.
* *NVSHAS-9930*: CVE-2018-20796 para `glibc/libc-bin: 2.36-9+deb12u10` – Falso positivo.
* *NVSHAS-9933*: La función de adaptador de registro (Harbor) muestra errores en el registro de destino durante el escaneo.
* *NVSHAS-9934*: Se sospecha que hay un mal funcionamiento de la función de deriva cero.
* *NVSHAS-9940*: Problema con el modo de subdominio JFrog en el escaneo NV.
* *NVSHAS-9942*: Los escaneos de imágenes de clientes están fallando.
* *NVSHAS-9945*: Cuando el nombre del proceso es demasiado largo, es difícil determinar cómo crear la regla de perfil de proceso adecuada.
* *NVSHAS-9946*: Problema de visualización con la alerta de control de admisión para el tipo de credencial.
* *NVSHAS-9947*: [UI-ext] Falta el estado "Manual" en el cuadro de cumplimiento en Rancher NeuVector.
* *NVSHAS-9948*: Después de actualizar a `5.4.3`, se perdió la configuración de NeuVector.
* *NVSHAS-9949*: [Harbor][Usuario/contraseña incorrectos] Aún escanea imágenes incluso con una entrada de usuario/contraseña incorrecta.
* *NVSHAS-9952*: Eliminar 'firma' del informe de uso porque NV ya no emite/verifica la clave de licencia.
* *NVSHAS-9953*: Pods Enforcer sigue reiniciándose.
* *NVSHAS-9954*: Exportador NeuVector Prometheus que genera métricas duplicadas.
* *NVSHAS-9958*: La aplicación de las reglas de la red lleva mucho tiempo.
* *NVSHAS-9960*: Los escáneres no funcionan.
* *NVSHAS-9969*: Error fatal: las escrituras de mapas simultáneas dan como resultado el reinicio del componente Enforcer.
* *NVSHAS-9971*: NV UI sobre `cómo obtener la contraseña de Bootstrap`.
* *NVSHAS-9975*: [Administrador] TypeError: `this.mousemoveListener` no es una función observada en NV GUI.
* *NVSHAS-9986*: Las reglas de acceso a procesos y archivos no se pueden editar ni eliminar en la vista del grupo de políticas federadas.
* *NVSHAS-9988*: UI: Las páginas de grupo no muestran todos los grupos cuando hay más de 2000 grupos presentes.
* *NVSHAS-9991*: Falta el grupo `nv.gatekeeper-controller-manager.openshift-azure-guardrails` en la interfaz de usuario.
* *NVSHAS-9993*: Reemplace MD5 con SHA256.
* *NVSHAS-9994*: El pod Enforcer sigue reiniciándose.
* *NVSHAS-9996*: El gráfico de Helm debe permitir el modo sin privilegios de los pods Enforcer.
* *NVSHAS-9998*: No se puede exportar el grupo desde el maestro federado de NeuVector.
* *NVSHAS-10000*: Actualice NV a BCI 15.7.
* *NVSHAS-10003*: Recargar página no funciona en la página NV independiente mientras la interfaz de usuario de Rancher está abierta.
* *NVSHAS-10008*: Escaneo de registro: el menú Ver no funciona para la imagen escaneada.
* *NVSHAS-10010*: La inundación TCP SYN bloquea el ingreso, lo que da como resultado un bloqueo total del tráfico de ingreso.

=== 5.4.4 Mayo de 2025

==== Nuevas funciones

* **NVSHAS-9915**: Mostrar los resultados del escaneo del módulo del escáner Harbor en la interfaz de usuario de NeuVector.
* **NVSHAS-9904**: Exponer `imagePullPolicy` a `values.yaml` para cada componente.
* **NVSHAS-9869**: UI: Mueva los controles DDoS al panel de grupo.
* **NVSHAS-9840**: [GCP] Compatibilidad del piloto automático NeuVector con GCP.
* **NVSHAS-9248**: Muestra reglas de red/proceso no utilizadas con contadores y marca de tiempo `del último uso` .
* **NVSHAS-8160**: [Controlador] Ajustar algunos elementos para el cálculo del puntaje de riesgo de seguridad.
* **NVSHAS-4673**: Sugerencia para agregar mensaje antes de exportar grupos.

==== Correcciones de errores de programas

* **NVSHAS-9931**: Agregue una advertencia si hay versiones inconsistentes de productos NeuVector en varios clústeres.
* **NVSHAS-9925**: La API `/v1/scan/asset/images` en la página de registro falla.
* **NVSHAS-9913**: Problema con la eliminación de varias reglas de red relacionadas con los grupos Workload:XYZ.
* **NVSHAS-9912**: Actualizar Helm sobre algunos permisos RBAC de K8 que necesita la cuenta de servicio del controlador.
* **NVSHAS-9909**: Se muestra el mensaje "Cerrar sesión - Ir a la página de carga" al usar NeuVector Rancher NavLink.
* **NVSHAS-9898**: En un entorno federado, modificar los criterios de un grupo fed.* creado por el cliente (por ejemplo, fed.core-systems) no funciona.
* **NVSHAS-9894**: [Enforcer] `Nv.protect` niega el comando de sondeo de preparación del controlador `cat /tmp/ready`.
* **NVSHAS-9886**: La actividad de la red no resuelve los nombres de dominio para las conexiones de grupo externo personalizadas.
* **NVSHAS-9884**: [Escaneo de nodo][Escaneo de contenedor] El escaneo fallará.
* **NVSHAS-9873**: Problema de búsqueda del filtro avanzado de UI en NeuVector 5.4.2.
* **NVSHAS-9865**: Las políticas de red exportadas difieren según el orden de selección (los mismos grupos seleccionados).
* **NVSHAS-9828**: [Enforcer: proceso] NeuVector Enforcer no puede detectar pods de corta duración (menos de 5 segundos).
* **NVSHAS-9783**: Después de agregar la política de red para denegar paquetes ICMP, NeuVector no ve ninguna alerta en `Eventos de seguridad`.
* **NVSHAS-9176**: Mostrar un error de script en la página **Riesgos de seguridad > Vulnerabilidades** si un usuario con permiso de espacio de nombres `rt_scan:w` inicia sesión.

=== 5.4.3 March 2025

==== Nuevas funciones

* **NVSHAS-9793**: Permitir roles globales federales en LDAP/userinitcfg al implementar NeuVector a través de ConfigMap y Secret.
* **NVSHAS-9764**: [RFE] Agregar compatibilidad con Azure para "Configuración de repositorio remoto".
* **NVSHAS-9759**: Agregue detalles de fecha en el Informe de ingreso-exposición.
* **NVSHAS-9755**: Solicitud para mostrar los nombres de las variables de entorno junto con los valores en las alertas de secretos.
* **NVSHAS-9748**: [Helm] Actualización de NeuVector Helm para soportar la referencia de nombres para grupos comunes en CRD (NVSHAS0-4717).
* **NVSHAS-9426**: Agregue hostPath para el escáner al gráfico Helm.
* **NVSHAS-9326**: NeuVector - Módulo de escáner conectable Harbor.
* **NVSHAS-9835**: Interfaz de usuario para deshabilitar el escaneo automático del nodo.
* **NVSHAS-7997**: Conector de escáner para ghcr.io.
* **NVSHAS-7982**: Asignar sensores WAF desde el Maestro de la Federación.

==== Correcciones de errores de programas

* **NVSHAS-9849**: Los ejecutores no se registran con los controladores.
* **NVSHAS-9847**: Los filtros comodín no funcionan para el registro de Docker.
* **NVSHAS-9833**: La restauración de la configuración falla en las implementaciones de Rancher.
* **NVSHAS-9832**: Problema con la creación de reglas de red utilizando el grupo de carga de trabajo.
* **NVSHAS-9821**: El nombre del proceso no coincide con la línea de comando para la alerta de regla de ganancias del proceso.
* **NVSHAS-9817**: La creación de NvClusterSecurityRule CRD muestra una creación exitosa, pero en realidad no se creó debido a entradas de reglas de proceso duplicadas.
* **NVSHAS-9812**: NeuVector prometheus-exporter métricas erróneas.
* **NVSHAS-9811**: [Administrador] No se puede acceder a la GUI cuando se usa un certificado personalizado (CA) con CA raíz y CA intermedia en el secreto.
* **NVSHAS-9801**: El modo FIPS + `manager.env.ssl=false` provoca que Manager genere un error.
* **NVSHAS-9792**: La sincronización de la política de la federación falla debido a que el tamaño del cuerpo excede el máximo del Cónsul.
* **NVSHAS-9784**: NeuVector devuelve 404 durante el escaneo del repositorio de imágenes Jfrog.
* **NVSHAS-9783**: Después de agregar la política de red para denegar paquetes ICMP, el usuario no ve ninguna alerta en "Eventos de seguridad".
* **NVSHAS-9780**: El inicio de sesión único de NeuVector no funciona con Rancher NavLink.
* **NVSHAS-9777**: Webhook JSON con claves de "nivel" duplicadas.
* **NVSHAS-9770**: Cambio automático después de que el modo Deriva cero cambie a una política incorrecta.
* **NVSHAS-9765**: El acceso a los archivos no se bloquea completamente en el modo de protección.
* **NVSHAS-9756**: Enforcer alcanzó el máximo de CPU y tiene varias alertas de presión de memoria.
* **NVSHAS-9668**: Prueba de cumplimiento fallida en RKE2.
* **NVSHAS-9265**: Resultados de análisis de vulnerabilidad incompletos e incorrectos en el entorno PRE PCI.
* **NVSHAS-9227**: El escaneo del registro se bloquea en medio del proceso y pasa al estado "Inactivo".
* **NVSHAS-9729**: Se observa un recuento incorrecto de vulnerabilidades cuando se implementan varios conjuntos de estado con el "mismo nombre" en espacios de nombres en un proyecto.
* **NVSHAS-9810**: El controlador NeuVector no responde y la interfaz de usuario no es accesible.

=== 5.4.2 Enero de 2025

==== Nuevas funciones

* **NVSHAS-9726**: El monitor ahora pasa la URL del proxy.
* **NVSHAS-9719**: Anuncia el retiro de los certificados integrados.
* **NVSHAS-9715**: Soporte de valores del gráfico de Helm para configurar el puerto de nodo en el controlador y el administrador.
* **NVSHAS-9710**: Incluya una columna `feed_rating` ordenable en la pestaña **Vulnerabilidades** .
* **NVSHAS-9669**: Puntuación de seguridad general a través de API REST.
* **NVSHAS-9590**: Capacidad de elegir qué puntuación de vulnerabilidad aplicar a todos los activos.
* **NVSHAS-7555**: Incluya la opción "Actualización automática" en Eventos de seguridad.

==== Correcciones de errores de programas

* **NVSHAS-9662**: Lógica de rol/vinculación de roles inconsistente en el gráfico de Helm 2.8.2.
* **NVSHAS-9652**: Diferencia observada en el formato syslog en Splunk.
* **NVSHAS-9649**: El enlace del contenedor produce un código de respuesta 404 en el evento de seguridad.
* **NVSHAS-9613**: Error de pod de NeuVector Manager / Interfaz web de NeuVector no disponible.
* **NVSHAS-9507**: El contenedor OCI no se escanea.
* **NVSHAS-9443**: La actualización/instalación a través de ArgoCD falla porque no puede crear el objeto leases.coordination.k8s.io.
* **NVSHAS-9436**: Posible falso negativo de CVE contra CVE-2024-7347.
* **NVSHAS-8386**: Las claves privadas y los certificados autofirmados aún se envían en múltiples imágenes.
* **NVSHAS-9754**: [UI] Evita que Rancher relacione la deshabilitación del usuario SSO con la autenticación de OpenShift o el RBAC de Rancher.
* **NVSHAS-9751**: [Protección en tiempo de ejecución] El modo de monitorización + deriva cero no genera ninguna alerta cuando se ejecuta un proceso secundario.
* **NVSHAS-9721**: La interfaz de usuario debería mostrar un mensaje de error apropiado cuando el usuario ingresa un nombre de registro incorrecto.
* **NVSHAS-9696**: Indicación de color inconsistente de los activos en la página de vulnerabilidad.
* **NVSHAS-9686**: Espacio de nombres codificado para el certificado del adaptador de registro en el gráfico Helm de Neuvector.
* **NVSHAS-9678**: Excesivos rastros de errores después de los cambios del linter.
* **NVSHAS-9670**: Gerente: Problema de comillas dobles en la respuesta de texto simple y problema de biblioteca sin nombre de Java en la ejecución de sbt.
* **NVSHAS-9667**: La configuración de la variable de entorno `CTRL_PATH_DEBUG` como error en la implementación del controlador no funciona.
* **NVSHAS-9665**: Regla de acceso a archivos: Eliminar reglas predefinidas produce el error "setRowData".
* **NVSHAS-9664**: Grupo de directivas: Eliminar script personalizado produce el error de tipo "setRowData".

[NOTE]
====
Los tipos predeterminados de servicio de adaptador de registro y administrador se han cambiado a ClusterIP.  Los usuarios aún pueden anular la configuración anulando `manager.svc.type` y `cve.adapter.svc.type` si prefieren NodePort.
====

En la versión NeuVector 5.4.2, se suspende el soporte para implementaciones que utilizan el certificado interno incorporado. Se eliminará el certificado que se encuentra en `/etc/neuvector/certs/internal` dentro de las imágenes de contenedor de NeuVector 5.4.2. Para continuar utilizando NeuVector, los usuarios deben:

==== 5.4.2 Nueva instalación:

===== Usando Helm:

- Habilite los indicadores `internal.autoGenerateCert` e `internal.autoRotateCert` en los gráficos de Helm (se habilitarán de manera predeterminada a partir de la versión 5.4.2). Alternativamente, a continuación se incluye un enlace a un método YAML.

===== Usando YAML:

- Proporcionar un xref:internal.adoc#_replacing_certificates_used_in_internal_communications_of_suse_security[certificado interno utilizando los métodos existentes].

==== Actualización desde versiones anteriores a 5.4.2:

Cree y configure certificados internos desde el escáner para el controlador, el ejecutor y el adaptador de registro para lograr una actualización continua sin perder datos. Aún se recomienda realizar una copia de seguridad de su configuración antes de actualizar. 

Los siguientes pasos solo son necesarios si su implementación utiliza un archivo `.yaml` . La actualización mediante Helm no necesita estos pasos adicionales debido a que los certificados internos se crean de manera predeterminada a través de los siguientes indicadores: `internal.autoGenerateCert` y `internal.autoRotateCert`.

[,shell]
----
docker run -it --entrypoint=bash neuvector/scanner:3.654 -c "cat /etc/neuvector/certs/internal/ca.cert" > ca.crt
----

[,shell]
----
docker run -it --entrypoint=bash neuvector/scanner:3.654 -c "cat /etc/neuvector/certs/internal/cert.pem" > tls.crt
----

[,shell]
----
docker run -it --entrypoint=bash neuvector/scanner:3.654 -c "cat /etc/neuvector/certs/internal/cert.key" > tls.key
----

[,shell]
----
kubectl create secret generic internal-cert -n neuvector  --from-file=tls.key --from-file=tls.crt --from-file=ca.crt
----

Ejemplo 5.4.2 yaml con certificado interno configurado: *https://github.com/neuvector/manifests/blob/main/kubernetes/5.4.0/neuvector-k8s.yaml* 

Información adicional sobre xref:internal.adoc[los certificados internos].


En el caso de una configuración de PVC, los usuarios pueden configurar un PVC existente en la nueva instalación para restaurar una configuración.


**Nota adicional para el escáner:**

Para los usuarios actuales con versiones anteriores a la 5.4.2, el certificado permanecerá disponible en `neuvector/scanner:latest` hasta el 31 de marzo de 2025. Después de esta fecha, será eliminado. Los usuarios deben planificar proporcionar el mismo certificado interno al controlador, al ejecutor, al escáner y al adaptador de registro para continuar usando el escáner.

Tenga en cuenta que el escáner independiente no se verá afectado por estos cambios.

=== 5.4.1 Noviembre de 2024

==== Nuevas funciones

* **NVSHAS-8583**: Establecer modos de política granulares para conjuntos de reglas, modo de política de red independiente y modo de perfil a nivel de grupo.
* **NVSHAS-9440**: Admite modo de red separado y modo de proceso y archivo en CRD.
* **NVSHAS-9369**: Agregue la categoría de registro de depuración a través del soporte de implementación de Helm para el controlador.
* **NVSHAS-9040**: Mejorar el mensaje de syslog cuando se niega la regla de control de admisión en el modo de monitor.

==== Correcciones de errores de programas

* **NVSHAS-9416**: [Scanner] activemq-all-5.8.0.redhat-60024.jar NO se puede detectar con ninguna vulnerabilidad (pero las compilaciones anteriores del escáner sí pueden).
* **NVSHAS-9447**: Los pods del controlador/escáner fallan: "Salida del sistema no compatible".
* **NVSHAS-9278**: CVE-2024-41110 se encuentra en la última imagen del escáner.
* **NVSHAS-9467**: El grupo personalizado definido por la etiqueta del pod no propaga sus datos de perfil en los contenedores secundarios.
* **NVSHAS-9442**: Problema de implementación en ArgoCD.
* **NVSHAS-9436**: Posible falso negativo de CVE contra CVE-2024-7347.
* **NVSHAS-9468**: Corrija CVE-2020-26160 para reemplazar jwt-go con jwt:v5.
* **NVSHAS-9517**: El control de admisión no es consistente, obteniendo resultados erróneos.
* **NVSHAS-9532**: Se completó el escaneo de la imagen, pero aún no se permite la implementación.
* **NVSHAS-9558**: JWT token expire reports http.StatusRequestTimeout 408.
* **NVSHAS-9576**: Borre el campo de contraseña de los datos de registro cuando el usuario usa el modo controlador con Jenkins para escanear.
* **NVSHAS-9425**: Crear nfq cuando el contenedor tenga vxlan.
* **NVSHAS-9571**: [Registros] El filtro para todas las imágenes escaneadas no funciona bien.
* **NVSHAS-9589**: Clústeres administrados desconectados: falta de coincidencia de versión con el clúster principal.
* **NVSHAS-8824**: El usuario no puede eliminar sus propios grupos y no puede crear grupos con alcance de espacio de nombres.
* **NVSHAS-9605**: Se permite por error la exportación de un grupo con valores de modo de política y modo de perfil de proceso no válidos.
* **NVSHAS-9608**: El escáner no informa ningún error cuando el controlador informa un error para resultados de escaneo grandes ~23 MB.
* **NVSHAS-9534**: Error de visualización en los controles de admisión.
* **NVSHAS-9600**: No se puede deshabilitar la depuración del controlador.
* **NVSHAS-9631**: Reducir algunos errores del ejecutor.
* **NVSHAS-9645**: El procesamiento de CRD preexistente falla.
* **NVSHAS-9592**: No hay ningún nuevo escaneo a pesar de la nueva versión de la base de datos.
* **NVSHAS-9212**: Muestra un mensaje de alerta en GET(/v1/eula) si el rol neuvector-binding-secret(binding) es incorrecto.
* **NVSHAS-9367**: Mejorar los mensajes de error cuando el registro no puede conectarse.
* **NVSHAS-9475**: La impresión de la cuadrícula de fondo no cubre completamente cuando el menú está contraído.
* **NVSHAS-9485**: Mensaje incorrecto para 'Modo de política de seguridad de red' en la interfaz de usuario.
* **NVSHAS-9480**: La interfaz de usuario NV implementada en el clúster descendente de Rancher genera HTTP/403 después del cierre de sesión de Rancher.
* **NVSHAS-9547**: La clasificación está rota por los riesgos de seguridad --> tabla de vulnerabilidades.
* **NVSHAS-9570**: [Vulnerabilidades] Cambiar la descripción de la leyenda para diferentes estados de los activos.
* **NVSHAS-9561**: La puntuación de seguridad general del tablero de instrumentos debe coincidir con la puntuación real.
* **NVSHAS-9572**: [Vulnerabilidades] Los datos filtrados se conservaban independientemente de que el usuario actualizara o volviera a iniciar sesión en la página.
* **NVSHAS-9597**: La interfaz de usuario no responde a ningún error cuando el controlador devuelve 403 para POST(v1/grupo).
* **NVSHAS-8682**: El servicio webhook CRD debe trasladarse del gráfico de Helm de CRD al gráfico de Helm de la aplicación.

==== Problemas conocidos

* En la versión 2.8.3 del gráfico, hemos movido un recurso previamente mal asignado de crds a core. Si usa tanto crds como gráficos de núcleo, es posible que experimente problemas durante la actualización si implementa primero el núcleo. Para resolver esto, actualice primero los crds y luego los gráficos centrales.

=== 5.4 de septiembre de 2024

* **Mejoras en la interfaz de usuario**: 
** Mostrar usuarios de SSO de Rancher.
** Administrar tokens JWT.
** Navegación de imágenes mejorada y enlaces a resultados de escaneo.
* **Mejoras de seguridad**: 
** Nuevos filtros de cumplimiento.
** Soporte para puntos de referencia CIS y firma de imágenes OCI.
* **Red y Monitoreo**: 
** Seguimiento avanzado de ancho de banda y sesiones.
** Monitoreo de DDoS.
** Soporte para múltiples redes.
* **Gestión de certificados**: 
** Nuevas notificaciones de certificados internos que vencen, incluidas capacidades de rotación.
* **Automatización e integración**: 
** Automatización de la federación.
** Integración de Rancher RBAC.
** Control de admisión mejorado.
* **Rendimiento y eficiencia**: 
** Uso reducido de memoria.
** Reducción de la tarifa de datos del ISP.
** Exposición de estadísticas de caché del escáner.
* **Mejoras de usabilidad**: 
** Compatibilidad con contraseña de Bootstrap.
** Archivado de datos de facturación en la nube.
** Aplicación de límites en espacios de nombres.

==== Nuevas funciones

* **NVSHAS-9012**: Visualización de usuarios de Rancher SSO en NV UI que tienen el mismo nombre de usuario.
* **NVSHAS-8939**: Proporcionar una opción en NV UI para que los usuarios de la sesión SSO de Rancher puedan eliminar el token JWT actual (es decir, cerrar sesión).
* **NVSHAS-7522**: Fácil navegación de imágenes a través de los registros.
* **NVSHAS-8148**: Enlace desde la imagen del contenedor a los resultados del escaneo de la imagen del registro.
* **NVSHAS-9258**: Agregar una nueva notificación para certificados que vencen y certificados internos.
* **NVSHAS-8915**: Soporte para nuevos filtros de cumplimiento e informes de cumplimiento.
* **NVSHAS-9403**: Interfaz de usuario del monitor de archivos: Permitir al usuario eliminar reglas de monitorización de archivos predefinidas.
* **NVSHAS-8423**: Detecta el ancho de banda a nivel de grupo, el recuento de sesiones activas y la violación de la tasa de sesiones según los umbrales configurados.
* **NVSHAS-9218**: Apoyo a grupos federales y CRD para monitoreo de DDoS.
* **NVSHAS-8461**: Apoye los puntos de referencia CIS para servicios k8s administrados en la nube.
* **NVSHAS-7664**: Reducir los cargos por datos del ISP durante el escaneo del registro.
* **NVSHAS-8868**: Exponer las estadísticas de caché del escáner.
* **NVSHAS-8676**: Mejora de NV Protect para scripts de referencia.
* **NVSHAS-9255**: Personalice los registros de búsqueda de control de admisión para nombres de imágenes sin FQDN.
* **NVSHAS-9144**: Se agregó ID para el perfil de vulnerabilidad para una fácil identificación.
* **NVSHAS-7687**: Admite la configuración del nivel de registro (depuración/error/información/advertencia) para el ejecutor y el controlador desde la CLI.
* **NVSHAS-7518**: Cambiar los certificados internos para {product-name} componentes.
* **NVSHAS-9287**: Habilitar la rotación interna de certificados.
* **NVSHAS-8562**: Agregar notificación de vencimiento de certificado interno.
* **NVSHAS-8486**: Admite interfaz de red Multus.
* **NVSHAS-7447**: Integración de Rancher RBAC con {product-name}.
* **NVSHAS-7822**: Automatización de la federación sin necesidad de scripts de llamadas API.
* **NVSHAS-8799**: Cree un marco de cumplimiento para importar plantillas de cumplimiento.
* **NVSHAS-8773**: Compatibilidad con contraseña de Bootstrap durante la implementación inicial.
* **NVSHAS-6740**: Mejora del perfil de línea base de deriva cero mediante la aplicación de la lista aprendida en modo de protección.
* **NVSHAS-8325**: Aplicar el límite del espacio de nombres del contenedor para la regla de red.
* **NVSHAS-8723**: Archivar datos de facturación en la nube.
* **NVSHAS-9086**: Reduzca el uso de memoria del proceso del controlador eliminando la estructura de datos vulnerable.
* **NVSHAS-6979**: Capacidad de incluir comentarios de la regla de respuesta en el contenido de la alerta.
* **NVSHAS-8845**: Crear APIKEY con rol FedReader y FedAdmin.
* **NVSHAS-9306**: La evaluación de la configuración de control de admisión muestra el ID de la regla responsable de las implementaciones permitidas o denegadas.
* **NVSHAS-9078**: Soporte para firma de imágenes para imágenes OCI.
* **NVSHAS-7945**: Admite el punto de referencia DISA STIG para Kubernetes.
* **NVSHAS-8234**: Lógica de control de admisión que permite imágenes que deberían ser denegadas.

==== Correcciones de errores de programas

* **NVSHAS-9005**: Error de tipo en los registros: No se pueden leer las propiedades de undefined (lectura 'total_records').
* **NVSHAS-9085**: El informe en PDF de Assets View muestra un 0 % de vulnerabilidad incluso con las vulnerabilidades presentes.
* **NVSHAS-9084**: El informe en PDF de Vista de activos muestra NaN cuando la lista de imágenes está vacía.
* **NVSHAS-9128**: Eventos de seguridad: No se puede mostrar el contenedor si no hay ningún valor de espacio de nombres de la carga de trabajo.
* **NVSHAS-9025**: Ámbito de aceptación de vulnerabilidad de Neuvector para contenedores.
* **NVSHAS-9155**: Nombre de columna incorrecto en la imagen de escaneo del registro y nombre de archivo faltante
* **NVSHAS-9122**: El maestro de Neuvector cierra la sesión en cualquier momento cuando se utiliza "Clúster múltiple" con el inicio de sesión SSO de Rancher.
* **NVSHAS-9266**: Escaneo del registro: El botón Informe de escaneo por capa debe estar oculto o deshabilitado cuando no haya ninguna vulnerabilidad.
* **NVSHAS-9219**: Permitir a los usuarios habilitar la validación de certificados de servidor para servidores de autenticación.
* **NVSHAS-9246**: El filtrado para la exportación CSV/PDF no funciona.
* **NVSHAS-8947**: No se puede importar la configuración NV cuando se autentica a través de Rancher SSO.
* **NVSHAS-9282**: UI: La edición de la entrada de registro de OpenShift falla debido a que falta un token.
* **NVSHAS-9098**: Mejorar la experiencia del usuario al cargar la página de riesgo.
* **NVSHAS-9267**: No permita que la interfaz de usuario del clúster maestro 5.4 cambie a clústeres administrados anteriores a 5.4 debido a cambios en la API REST.
* **NVSHAS-9285**: UI: El botón de lista desplegable se superpone con otros elementos.
* **NVSHAS-9302**: No se puede crear APIKEY con el rol FedReader y FedAdmin.
* **NVSHAS-8539**: Al reconfigurar la configuración del proxy se pierde la contraseña.
* **NVSHAS-9293**: Eliminación de detalles de imágenes no relacionados en los informes de vulnerabilidad.
* **NVSHAS-9238**: La interfaz de usuario no actualiza el nombre del clúster mostrado después de cambiarlo.
* **NVSHAS-9363**: Configuración de notificaciones > La cuadrícula de webhooks no está alineada correctamente.
* **NVSHAS-9362**: El filtro de vulnerabilidades de riesgo de seguridad devuelve 0 resultados.
* **NVSHAS-8699**: No se puede distinguir al usuario si el usuario de Rancher AD es el mismo.
* **NVSHAS-9062**: Visualización de usuarios de Rancher SSO en NV UI que tienen el mismo nombre de usuario (conversión en el controlador).
* **NVSHAS-9071**: Algunos módulos no se informan únicamente en el escaneo del contenedor.
* **NVSHAS-8242**: llamada gRPC para probar si el controlador maneja la severidad crítica.
* **NVSHAS-8908**: Analizar X-Forwarded-Port correctamente considerando el separador de coma.
* **NVSHAS-9024**: Control de Admisión Rol Riesgoso Perf.
* **NVSHAS-9091**: No se pueden informar todos los módulos bajo las fuentes ol:9.1, photon:5.0, rhel:9.1 y amzn:2023 en el repositorio, el registro y el análisis independiente.
* **NVSHAS-8997**: Reducir en gran medida el número de ranuras de política por nodo para mejorar el rendimiento.
* **NVSHAS-9059**: Grupos CRD visibles en NV incluso después de la eliminación de K8s.
* **NVSHAS-9107**: Fallo de goroutine en rest.handlerConfigLocalCluster.
* **NVSHAS-9108**: El puerto 18500 no debería estar abierto.
* **NVSHAS-9119**: La goroutine se bloquea durante la sonda.(*FileNotificationCtr).AddContainer().
* **NVSHAS-9125**: No se debe permitir la creación de entradas CRD con configuraciones no válidas.
* **NVSHAS-9124**: Docker: se informan muchos incidentes inesperados en el proceso de verificación de estado.
* **NVSHAS-9111**: NV debería comprobar `--evento-qps > 0`.
* **NVSHAS-9130**: Se encuentran incidentes inesperados de Container.Package.Updated después de que se inicia un contenedor específico.
* **NVSHAS-9080**: El usuario lector de Fed no puede acceder a algunas API REST.
* **NVSHAS-9092**: Los usuarios con espacio de nombres no deberían ver los activos globales.
* **NVSHAS-9116**: El clúster de trabajadores puede abandonarlo si se interrumpe la conexión.
* **NVSHAS-8980**: Obtenga la interfaz de host y túnel en el nodo con éxito en oc 4.15.
* **NVSHAS-9188**: Establezca la interfaz mgmt-br como interfaz de host para el nodo recolector.
* **NVSHAS-4858**: No expanda el grupo de contenedores en el controlador para mejorar el rendimiento de implementación de políticas y reducir el uso de CPU y memoria.
* **NVSHAS-8700**: El usuario de Rancher AD no puede iniciar sesión {product-name} a veces.
* **NVSHAS-9121**: La configuración del umbral de monitoreo de red del grupo no se puede editar.
* **NVSHAS-9189**: El escaneo quedará bloqueado en la programación después de que el controlador se apague y reinicie.
* **NVSHAS-9019**: Corregir el estado del enlace no sincronizado para la interfaz del host.
* **NVSHAS-8305**: Eliminar el certificado incorporado.
* **NVSHAS-9013**: Quitar el filtro BPF del monitor de proceso.
* **NVSHAS-7853**: Protocolo de enlace TLS EOF.
* **NVSHAS-9290**: La regla de perfil de proceso agregada por el usuario no tiene efecto con ZD habilitado.
* **NVSHAS-9301**: El NV implementado en Rancher Prime no puede distinguir su sabor Rancher.
* **NVSHAS-9289**: Permitir actualización cuando falte RBAC.
* **NVSHAS-7601**: Mejorar la restauración desde la copia de seguridad de la configuración de PV durante los escenarios.
* **NVSHAS-7687**: Agregar configuración de nivel de syslog para el ejecutor.
* **NVSHAS-9292**: Reparar la exposición de ingreso y egreso muestra 0 vulnerabilidades.
* **NVSHAS-9270**: Admite k3s para la canalización de referencia CIS.
* **NVSHAS-9338**: Alerta 'El clúster administrado [id] está desconectado del principal'.
* **NVSHAS-9358**: El escaneo de imágenes mediante proxy fallaría.
* **NVSHAS-9337**: Envía un mensaje de registro cuando se detecta una inundación SYN.
* **NVSHAS-9209**: Eliminar la caché del dominio cuando se elimina el espacio de nombres de k8s.
* **NVSHAS-8985**: Los registros federados desaparecen después de reiniciar el controlador.

==== Problema conocido:

* **NVSHAS-9443**: La actualización/instalación a través de ArgoCD falla porque no puede crear el objeto leases.coordination.k8s.io.
* **Solución alternativa**: Cree los objetos de arrendamiento indicados antes de actualizar a 5.4.0 utilizando ARGO CD. Cambie el espacio de nombres si es diferente de neuvector.
+
--
[,bash]
----
cat <<EOF | kubectl apply -f -
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: neuvector-controller
  namespace: neuvector
spec:
  leaseTransitions: 0
---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: neuvector-cert-upgrader
  namespace: neuvector
spec:
  leaseTransitions: 0
EOF
----
--

=== 5.3.4 Julio de 2024

==== Correcciones de errores de programas

* La interfaz `del host` y `del túnel` se recuperan correctamente con OpenShift CLI v4.15.
* El rango de IP 169.254.xx está excluido de las IP de la interfaz del host.
* Vuelva a examinar la interfaz del host después de 1 minuto de iniciar el ejecutor.
* Se solucionó un problema por el cual la expresión regular de la URL del emisor de OpenID fallaba.
* Remedia los siguientes CVE:
+
|===
| CVE | Se aplica a | Impacto

| CVE-2023-42364
| busybox
| {CVE-medium}

| CVE-2023-42365
| busybox
| {CVE-medium}

| CVE-2024-6197
| curl
| {CVE-medium}

| CVE-2024-6874
| curl
| {CVE-medium}

| CVE-2024-5535
| openssl
| {CVE-critical}

| CVE-2024-4741
| openssl
| {CVE-medium}
|===

=== 5.2.4-s5 Julio de 2024

* Remedia los siguientes CVE:

|===
| CVE | Se aplica a | Impacto

| CVE-2023-42363
| busybox
| {CVE-medium}

| CVE-2023-42364
| busybox
| {CVE-medium}

| CVE-2023-42365
| busybox
| {CVE-medium}

| CVE-2023-42366
| busybox
| {CVE-medium}

| CVE-2024-6197
| curl
| {CVE-medium}

| CVE-2024-6874
| curl
| {CVE-medium}

| CVE-2024-5535
| openssl
| {CVE-critical}

| CVE-2024-4603
| openssl
| {CVE-medium}

| CVE-2024-4741
| openssl
| {CVE-medium}
|===

=== 5.3.3 Junio de 2024

==== Mejoras

* Permitir a los usuarios bloquear el uso de clases de almacenamiento específicas desde la página `Controles de admisión` .
* La `autenticación LDAP` tiene campos separados para la configuración `de baseDN` y `groupDN` .
* El `gráfico de entrada y salida` tiene una nueva columna de vulnerabilidad que contiene el recuento de vulnerabilidad `alta` y `media` para cada servicio.

==== Correcciones de errores de programas

* Se corrigió un error relacionado con `la expresión regular` al usar una coma (`,`) en un `criterio de usuario de control de admisión`de múltiples entradas.
* Se corrigió un error donde el escaneo CVE de paquetes `jar` no mostraba todos los paquetes afectados por el mismo CVE. Ahora se informan todas las ocurrencias.
* Remedia los siguientes CVE:

|===
| CVE | Se aplica a | Impacto

| CVE-2024-35195
| python:requests
| {CVE-medium}

| CVE-2024-21011
| openjdk11
| {CVE-low}

| CVE-2024-21012
| openjdk11
| {CVE-low}

| CVE-2024-21068
| openjdk11
| {CVE-low}

| CVE-2024-21085
| openjdk11
| {CVE-low}

| CVE-2024-21094
| openjdk11
| {CVE-low}
|===

==== Otros

* Permitir a los usuarios configurar recursos para `el trabajo cron de actualización` durante la instalación {product-name} con el gráfico de Helm.
* Se revisó la versión del contenedor exportador de Prometheus y se disoció de la versión `del controlador` .
* (Escáner) Detecta el paquete/módulo `R` en Ubuntu y Red Hat Enterprise Linux.
* (Escáner) Se agregó soporte para el escaneo de PHP Composer.

=== 5.2.4-s3 Abril de 2024

* Remedia los siguientes CVE:

|===
| CVE | Se aplica a | Impacto

| CVE-2021-40633
| giflib
| {CVE-high}

| CVE-2023-48161
| giflib
| {CVE-high}

| CVE-2024-28757
| expat
| {CVE-high}

| CVE-2023-39742
| giflib
| {CVE-medium}

| CVE-2023-45288
| go:golang.org/x/net
| {CVE-medium}

| CVE-2024-25629
| c-ares
| {CVE-medium}

| CVE-2024-3651
| python:idna
| {CVE-medium}

| CVE-2024-2511
| openssl
| {CVE-low}
|===

=== 5.3.2 Abril de 2024

==== Correcciones de errores de programas

* Después de actualizar a v5.3.1 desde una versión anterior {product-name} versión, los recursos personalizados NvClusterSecurityRule preexistentes pueden eliminarse inadvertidamente. NOTA: La versión 5.3.1 se ha eliminado de Docker Hub para evitar el problema de actualización.

=== 5.3.1 Abril de 2024

[IMPORTANT]
====
La versión 5.3.1 se ha eliminado de Docker Hub para evitar el problema de actualización solucionado en la versión 5.3.2. Utilice la versión 5.3.2.
====

==== Mejoras

* Permitir a los usuarios definir vulnerabilidades '`aceptadas`' al usar acciones de Github para que no afecten los flujos de trabajo.
* Agregue filtros de Gravedad, Nivel de puntuación y Calificación de feed a la vista Activos > Registro > Vulnerabilidades de imagen.
* Permitir al configurar un registro si debe utilizar el proxy definido para los escaneos de imágenes de registro.

==== Correcciones de errores de programas

* Riesgos de seguridad > Vulnerabilidades > El filtro avanzado no filtra "CVE sin corrección"
* Violación inesperada del contenedor al contenedor en modo host
* Aceptar el formato de imagen OCI al cambiar a la API de Docker 1.24
* El análisis del registro no debe analizar artefactos que no sean imágenes/no debe registrar un error
* Permite la verificación de la firma de imágenes de pares de claves sin raíz y sin dependencia de Internet o sigstore.
* Eventos de seguridad que no están permitidos por las reglas de red en un nodo específico (relacionados con los mensajes de error "Container Task chan full")
* El contenedor no puede agregarse a la carga de trabajo correctamente (ocurrencia frecuente). Resultante de un bloqueo de los mensajes del canal.

==== Otros

* Actualice los complementos del escáner para Jenkins, la acción de GitHub y Bamboo.
* (Escáner) Acepte el formato de imagen OCI al cambiar a la API de Docker 1.24.
* (Escáner) El escaneo de registro no debe escanear artefactos que no sean imágenes/no registrar un error.
* (Escáner) Agregar soporte para escaneo de compositor php.

==== {product-name} Extensión de UI v. 1.0 para Rancher Marzo 2024

* Después de la instalación de {product-name}, xref:rancher.adoc#_suse_security_ui_extension_for_rancher[habilitando/instalando] el {product-name} La extensión de UI de Rancher mostrará un panel para el clúster, incluidos enlaces a SSO para el clúster completo. {product-name} grupo. NOTA: La extensión puede aparecer como de Terceros, lo que se solucionará en una versión futura. Además, después de la instalación, los usuarios de Rancher 2.7.x pueden ver dos {product-name} Iconos de UI Ext en la lista (error). Un ícono dirá Desinstalar (lo que significa que está instalado) y el otro debería decir Instalar. Esto se puede dejar como está, es decir, no instalar nuevamente si la extensión ya está instalada.

=== 5.2.4-s2 Febrero de 2024

* Remedia los siguientes CVE:
* Alto cve: CVE-2023-52425 en expat, CVE-2024-20952 y CVE-2024-20918 en openjdk11
* CVE médico: CVE-2023-52426 en expat, CVE-2024-20926, CVE-2024-20921, CVE-2024-20945 y CVE-2024-20919 en openjdk11, CVE-2024-0727 y CVE-2023-6237 en openssl

=== 5.3.0 Febrero de 2024

==== Mejoras

* Mostrar las URL de destino externas (FQDN) en el Panel de control (salida), informes PDF y CSV, así como en la pantalla Actividad de red y las listas de Eventos de seguridad (infracciones).
* En el modo Descubrir, aprende automáticamente las salidas a grupos de direcciones FQDN externas. Se creará un nuevo grupo personalizado de FQDN externo a menos que la conexión externa coincida con una regla existente.
* Habilite el aprendizaje de ICMP (modo Descubrir) y el bloqueo (modo Proteger) a través de la nueva variable de entorno del controlador CTRL_EN_ICMP_POLICY = 1
* Exporte CRD a Github para admitir gitops en un repositorio predeterminado mediante la consola o la API REST.
* Admite cierre de sesión único SAML SSO con ADFS iDP
* Añadir soporte para la plataforma ARM64. Al extraer desde plataformas basadas en ARM se extraerá automáticamente el ARM64 apropiado. {product-name} imágenes.
* Admite webhooks a través de un proxy
* Mejorar la función de auditoría de control de admisión para incluir los resultados de todas las reglas. Enumere el resultado de cada regla y agregue otra entrada para la acción final que ocurriría cuando se evalúa en una implementación de control de admisión en vivo.
* Aplicar reglas de control de admisión deshabilitadas mediante CRD o yaml (kubectl)
* Exportación/importación de perfil de vulnerabilidad a través de consola, CRD o API REST. La importación reemplazará el perfil existente. Eliminar el CRD dará como resultado un perfil vacío.
* Exportación/importación de plantillas de perfil de cumplimiento a través de consola, CRD o API REST. La importación reemplazará la plantilla existente.
* Agregue un estado 'Manual' en los informes de cumplimiento para los puntos de referencia de CIS que los usuarios deben ejecutar manualmente (no ejecutar por {product-name}).
* Mejorar la carga y el rendimiento de la interfaz de usuario de la página de vulnerabilidades
* Unificar el inicio de sesión del navegador. Con esto, todas las pestañas del navegador comparten la misma sesión de inicio de sesión, abrir una nueva pestaña desde una sesión existente no solicita credenciales y cuando una pestaña cierra sesión, se cierran todas las pestañas.
* Mejoras en la seguridad de la consola (IU): 1) agregar encabezados de seguridad obligatorios (X-Content-Type-Options nosniff; X-XSS-Protection 1; mode=block; X-Frame-Options SAMEORIGIN; Cache-Control private, no-cache, no-store, must-revalidate HTTP Strict Transport Security max-age=15724800, 2) agregar encabezado CSP (por ejemplo, establecer una directiva '`default-src`' ), 3) eliminar la divulgación del nombre del servidor
* Admite versiones más nuevas de los puntos de referencia del CIS. Kubernetes (1.8.0), Kubernetes V1.24 (1.0.0), Kubernetes V1.23 (1.0.1), RedHat OpenShift Container Platform (1.4.0)
* Mostrar en Activos -> Contenedores -> Detalles de los contenedores: contenedores que se escanearon en registros versus tiempo de ejecución
* Agregar enlace al Grupo en Riesgos de Seguridad -> Vulnerabilidades -> Ventana emergente de impacto para editar fácilmente el modo de grupo
* Admite enlaces profundos en URL a páginas de vulnerabilidad de imágenes y/o contenedores
* Agregue la opción de restablecimiento de contraseña para que el administrador restablezca la contraseña del usuario en la configuración de la consola -> Usuarios
* Permitir el envío de registros de eventos a los registros del pod del controlador en Configuración -> Configuración -> Notificación. Los eventos enviados comenzarán con 'notification=' y se guardarán solo en el pod del controlador líder. Tenga en cuenta que hay un error en esta versión donde, para cambiar el nivel de evento, SYSLOG debe estar habilitado (y se puede deshabilitar si se desea después de cambiar el nivel).
* Eliminar el requisito de que el controlador/ejecutor monte "/host/cgroup".
* Agregue el menú Obtener soporte con enlaces a Slack, documentación y otros recursos
* Rellene el campo de mensaje en /v1/log/activity logs

==== Correcciones de errores de programas

* Error interno del servidor en Riesgos de seguridad -> Vulnerabilidades con un elevado número de CVE
* SIGSEGV: violación de segmentación en el controlador
* Eliminar archivos vulnerables (por ejemplo, jar) no elimina el archivo de la lista de vulnerabilidades
* Certificado Syslog no válido que utiliza el algoritmo de firma SHA256withECDSA
* {product-name} muestra eventos de seguridad que deben ser permitidos por una regla de red
* Nodo no administrado con ejecutor "zombie" ejecutándose
* El filtro avanzado muestra los campos Remediación e Impacto en blanco
* Corregir el manejo de cadenas para evitar reinicios inesperados de Enforcer
* Violaciones inesperadas relacionadas con grupos integrados
* La llamada RPC de depuración del ejecutor del paquete de soporte para datos devuelve un error
* El grupo no coincide en los eventos de seguridad
* Enviar eventos a Slack no funciona (con proxy)
* Mostrar eventos de seguridad para reglas de red permitidas

==== Otros

* Agregue la detección automática del motor de contenedor (socket) en tiempo de ejecución al gráfico de Helm
* Eliminar la configuración para ejecutar el controlador en modo privilegiado en el gráfico de Helm y el requisito de que el controlador/ejecutor monte "/host/cgroup".
* Los archivos de implementación de muestra de Kubernetes se han eliminado de {product-name} documentos. Consulte el enlace para ver ejemplos.

==== Cambios destacados que pueden requerir cambios para implementaciones manuales (todos los cambios ya se reflejan en el último gráfico de Helm para 5.3.x)

* La detección automática del tiempo de ejecución del contenedor (socket) elimina la necesidad de especificar el tiempo de ejecución del contenedor y la ruta del socket.
* La eliminación del requisito de ejecutar el controlador en modo privilegiado elimina la necesidad de montar el socket de tiempo de ejecución y el grupo /host/cgroup/ montado.
* Se agregó enlace de rol/rol para neuvector-binding-secret así como para neuvector-secret en yaml.
* Se requieren nuevas cuentas de servicio y vinculaciones de roles para 5.3
* Todos los archivos yaml de implementación referenciados ahora tienen /5.3.0/ en sus rutas

=== 5.2.4-s1 Enero de 2024

==== Lanzamiento de parche de seguridad

* Remedia CVE-2023-6129 en openssl y CVE-2023-46219, CVE-2023-46218 en curl.

=== 5.2.4 Noviembre de 2023

==== Correcciones de errores de programas

* Validación de webhook de Azure AKSCambios de configuración y registro de errores.

=== 5.2.3 Noviembre de 2023

==== Mejoras

* Añadir soporte para NVD API 2.0 en Scanner.
* Escanee el host del contenedor en el modo independiente del escáner.

[,shell]
----
docker run --rm --privileged --pid=host neuvector/scanner -n
----

==== Correcciones de errores de programas

* El escaneo en un nodo falla debido a un problema de bloqueo en docker cp/grpc.

=== 5.2.2-s1 Octubre de 2023

==== Actualización de seguridad

* Actualice los paquetes para remediar los CVE, incluidos High CVE-2023-38545 y CVE-2023-43804.

=== 5.2.2 Octubre de 2023

==== Aviso de seguridad para CVE-2023-32188

* Remediar CVE-2023-32188 "`La vulneración del token JWT puede permitir acciones maliciosas, incluida la ejecución remota de código (RCE)`" mediante la generación automática de un certificado utilizado para firmar el token JWT durante la implementación y la actualización, y la generación automática de un certificado de API RESTful/Manager durante las implementaciones basadas en Helm.
 ** El certificado para firma JWT es creado automáticamente por el controlador con una validez de 90 días y rota automáticamente.
 ** La generación automática de certificados de administrador, API REST y adaptador de registro requiere el uso de una instalación basada en Helm. {product-name} Helm versión 2.6.3 o posterior.
 ** El certificado incorporado aún se usa para implementaciones basadas en yaml si no se reemplaza durante la implementación; sin embargo, se recomienda reemplazarlos (ver la siguiente línea).
 ** xref:replacecert.adoc[El reemplazo manual del certificado] aún se admite y se recomienda para versiones anteriores o implementaciones basadas en yaml. Ver el {product-name} Aviso de seguridad de GitHub https://github.com/neuvector/neuvector/security/advisories/GHSA-622h-h2p8-743x[Aquí] para una descripción.
 ** El uso de certificados proporcionados por el usuario todavía se admite como antes para las implementaciones basadas en Helm y yaml.
* Agregue controles adicionales en scripts de cumplimiento personalizados. De forma predeterminada, ahora no se permite agregar scripts personalizados, a menos que se agregue la variable de entorno CUSTOM_CHECK_CONTROL a Controller y Enforcer. Los valores son "deshabilitar" (predeterminado, no permitido), "estricto" (solo rol de administrador) o "flexible" (roles de administrador, cumplimiento y política de tiempo de ejecución).
* Prevenir inyección LDAP: el campo de nombre de usuario está escapado.

==== Mejoras

* Agregar datos de escaneo adicionales a los resultados de CVE enviados por SYSLOG para escaneos en capas
* Admite NVD API 2.0 para escanear la base de datos CVE
* Proporcionar la fecha de creación de la imagen del contenedor en Activos -> Detalles del contenedor
* Ajustar la clasificación de las reglas de red: deshabilite la clasificación en la vista de reglas de red, pero habilite la clasificación de las reglas de red en la vista de grupo.
* Habilitar/deshabilitar la detección/alerta de TLS 1.0 y TLS 1.1 con variables de entorno para Enforcer THRT_SSL_TLS_1DOT0, THRT_SSL_TLS_1DOT1. Deshabilitado por defecto.
* Agregue la variable de entorno AUTO_PROFILE_COLLECT para Controller y Enforcer para ayudar a capturar el uso de memoria al investigar eventos de presión de memoria. Establezca el valor = 1 para habilitar.
* Las evaluaciones de configuración contra el Control de admisión deben mostrar todas las violaciones con un solo escaneo.
* Agregue más opciones para los criterios del informe CVE en las reglas de respuesta. Ejemplo 1: "cve-high-with-fix:X" significa: Cuando el número de (vulnerabilidades altas que se han corregido) >= X, se activa la regla de respuesta. Ejemplo 2: "cve-high-with-fix:X/Y" significa: Cuando el número de (vulnerabilidades altas que se informaron hace Y días y se han solucionado) >= X, se activa la regla de respuesta.

==== Correcciones de errores de programas

* La exportación de la política de grupo no devuelve ningún contenido YAML real
* Mejore la poda de espacios de nombres con una función dedicada
* {product-name} El usuario del espacio de nombres no puede ver los activos-->espacios de nombres
* Omitir el manejo de las solicitudes CRD CREATE/UPDATE si el espacio de nombres del CR ya está eliminado
* Proporcionar una solución alternativa para parte de los grupos CRD que no se pueden podar exitosamente luego de eliminar los espacios de nombres.

=== 5.2.1 Agosto de 2023

==== Mejoras

* Informar resultados de análisis en capas y datos CVE adicionales en mensajes SYSLOG. Esto se habilita a través de una casilla de verificación en Configuración -> Configuración -> SYSLOG
* Exportar asignaciones NIST 800-53 (a puntos de referencia de Docker CIS) en el informe de cumplimiento csv exportado
* Admite configuración de proxy en la verificación de firma de imagen
* Incluir el resultado del escaneo de la firma de la imagen en el informe CVE descargado
* Anotaciones de pod de soporte para políticas de control de admisión, disponibles a través de los criterios personalizados
* Agregue el campo Última modificación para filtrar la impresión de informes de vulnerabilidades, así como el Filtro avanzado en la vista de vulnerabilidades

==== Correcciones de errores

* No cree un administrador predeterminado con la contraseña predeterminada en la inicial {product-name} Implementación para la oferta de facturación de AWS (adaptador CSP), que requiere que el usuario use un secreto para crear un nombre de usuario y una contraseña de administrador.
* Se corrigió el archivo .json que aumentó de tamaño y bloqueó un nodo de Kubernetes
* Mejorar la lógica de detección de inyección SQL
* Al instalar el gráfico de Helm CRD, primero antes de instalar el {product-name} Diagrama central, faltan cuentas de servicio
* El resultado de cumplimiento del escaneo de imagen I.4.1 es incorrecto
* Informe de filtro avanzado de vulnerabilidad que muestra imágenes de todos los demás espacios de nombres

=== 5.2.0 Julio de 2023

==== Mejoras

* Tokens de soporte para {product-name} Acceso API. Ver configuración -> Usuario, claves API... para crear una nueva clave API. Las claves se pueden configurar con roles predeterminados o personalizados.
* Admite la facturación PAYG de AWS Marketplace para {product-name} suscripciones de soporte mensuales. Los usuarios pueden suscribirse a {product-name} por soporte de SUSE, facturado mensualmente a su cuenta de AWS según el uso promedio del recuento de nodos del mes anterior. Detalles https://open-docs.neuvector.com/deploying/awsmarketplace[aquí].
* Admite firma de imágenes para controles de admisión. Los usuarios pueden requerir {product-name} para verificar que las imágenes estén firmadas por partes específicas antes de que puedan implementarse en el entorno de producción, a través de una integración con Sigstore/Cosign. Ver activos -> Verificadores Sigstore para crear nuevos activos de firma. Luego se pueden crear reglas con criterios de firma de imágenes y/o verificadores de Image Sigstore.
* Habilite cada regla de control de admisión para que tenga su propio modo de Monitorear o Proteger. Una acción Denegar en el modo Monitor alertará, y una acción Denegar en el modo Proteger bloqueará. Las acciones permitidas no se ven afectadas.
* Agregue un nuevo operador de expresiones regulares en Política > Control de admisión > Agregar regla para usuarios y grupos de usuarios para admitir expresiones regulares. Operadores de soporte "coincide con CUALQUIER expresión regular en" y "coincide con NINGUNA expresión regular en".
* Agregue soporte para criterios de control de admisión, como límites de recursos. Se agrega un nuevo criterio para Límites de recursos y se admiten criterios adicionales a través de la configuración de Criterios personalizados.
* Apoyo invocando {product-name} escáner de los registros del puerto a través del https://github.com/goharbor/pluggable-scanner-spec[de escáner enchufable]Interfaz . Esto requiere la configuración de la conexión al controlador (API expuesta). El adaptador Harbor llama al punto final del controlador para activar un escaneo, que puede escanear automáticamente al enviarlo. Los servicios de interrogatorio se pueden utilizar para realizar exploraciones periódicas. Los resultados del escaneo de los controladores primarios de la federación se propagan a clústeres remotos.  NOTA: Hay un problema con el error del punto final del adaptador basado en HTTPS: ignore el error de conexión de prueba, funciona aunque se muestre un error (omitir la validación del certificado).
* Servicio SaaS de búsqueda para búsquedas de CVE. Busque lo último {product-name} Base de datos CVE para ver si existe un CVE específico en la base de datos. Este servicio está disponible para {product-name} Clientes Prime (suscripción de soporte de pago). Comuníquese con el soporte técnico a través de su portal SCC para acceder.
* Permitir al usuario deshabilitar la protección de la red pero mantener WAF/DLP funcionando. Configurar la habilitación de la política de red en Configuración -> Configuración.
* Utilice cuentas de servicios con menos privilegios según sea necesario para cada caso. {product-name} componente. Se introduce una variable "`leastPrivilege`" . El valor predeterminado es falso. NOTA: El uso del gráfico de timón actual con esta variable en una versión anterior a 5.2.0 no funcionará correctamente.
* Vincular a una cuenta de servicio no predeterminada para cumplir con la recomendación CIS 1.5 5.1.5.
* Permitir que el administrador configure el tiempo de espera de sesión predeterminado del usuario en Configuración -> Usuarios, claves API y roles.
* Banner de inicio de sesión personalizable y texto de encabezado de interfaz de usuario personalizable para implementaciones reguladas y gubernamentales. Los requisitos para la configuración se pueden encontrar xref:customui.adoc[aquí].
* Soporte de SYSLOG para transporte cifrado TLS. Seleccione TCP/TLS en Configuración -> Configuración para SYSLOG.
* Habilitar la implementación de la {product-name} Monitorear el gráfico del timón desde Rancher Manager.
* Eliminar el límite superior para el dominio de nivel superior en el validador de URL para el escaneo de registro.
* Escanee las dependencias de Golang, incluidos los escaneos en tiempo de ejecución.
* Admite análisis de vulnerabilidades de Debian 12 (Bookworm).
* Agregar exportación CSV para Registro/Detalles para exportar CVE para todas las imágenes en el registro configurado en Activos -> Registros para un registro seleccionado.
* Permitir {product-name} para configurar varios certificados ADFS en paralelo en el campo de certificado x.509.
* Agregue y muestre el campo de comentarios para las reglas de respuesta.
* Especificar qué {product-name} considera contenedores del sistema a través de variables de entorno. Por ejemplo, para Rancher y los espacios de nombres predeterminados: NV_SYSTEM_GROUPS=*cattle-system;default
* Agregar soporte para Kubernetes 1.27 y OpenShift 4.12

==== Correcciones de errores de programas

* Reducir los registros repetidos en los registros del controlador/ejecutor.
* La página de clústeres múltiples no se representa.
* La eliminación automática de un grupo vacío demora 2 horas en lugar de 1 hora según lo programado.
* La regla de red permitida manualmente no se aplica y da como resultado una violación de la imagen en pausa.
* Bloquear conexiones SSL incluso si una regla de red permite el tráfico bajo ciertas condiciones iniciales.
* Advertencia de eventos de seguridad incluso con reglas de red permitidas debido a un problema de actualización de políticas en la sincronización.
* Actividades de red que asocian incorrectamente el tráfico de grupos personalizados al externo.
* El token de cuenta de servicio predeterminado del espacio de nombres montado en cada pod tiene demasiados privilegios.
* A pesar de definir las reglas de la red, las violaciones se registran en eventos de seguridad (falsos positivos) cuando el contenedor se detiene debido a un error de falta de memoria (OOM).
* Permitir al usuario deshabilitar/habilitar la detección y protección contra contenedores no administrados en el clúster. Esto se puede configurar a través de la CLI del Administrador:

[,shell]
----
set system detect_unmanaged_wl status -h
Usage: cli set system detect_unmanaged_wl status [OPTIONS] {true|false}

  Enable/disable detect unmanaged container
----

==== Otros

* Agregue la configuración "leastPrivilege" en el gráfico de Helm. Agregue la opción de timón para New_Service_Profile_Baseline. Se publica una nueva versión (núcleo) del gráfico Helm para 5.2.
* Habilite la configuración de integración de AWS Marketplace (adaptador de facturación) en el gráfico de Helm.
* Actualizar el mapa de configuración para admitir nuevas funciones (varios certificados ADFS, desviación cero, New_Service_Profile_Baseline, SYSLOG TLS, tiempo de espera del usuario)
* Actualice las versiones compatibles de Kubernetes a 1.19+ y OpenShift 4.6+ (1.19+ con CRI-O)

=== 5.1.3 Mayo de 2023

==== Mejoras

* Agregar nueva fuente de vulnerabilidades para escanear Microsoft .NET Framework.
* Las estadísticas del ejecutor están deshabilitadas de forma predeterminada en el exportador Prometheus para mejorar la escalabilidad.
* Mejora de usabilidad: Usar un escáner para escanear una sola imagen e imprimir el resultado (ver ejemplo a continuación).
* Agregar la comprobación de imagePullPolicy en los criterios de reglas de control de admisión.
* Mostrar un mensaje de advertencia cuando el esquema CRD esté desactualizado.

==== Correcciones de errores de programas

* La pantalla Actividad de red no se representa o se representa incorrectamente.
* La eliminación automática de un grupo vacío demora 2 horas en lugar de 1 hora según lo programado.
* El perfil de cumplimiento no se muestra en la consola de interfaz de usuario.
* Filtro avanzado en eventos de seguridad sin nivel de "Error".
* La contraseña guardada con un carácter especial falla en futuros intentos de autenticación.
* La página de múltiples clústeres no se procesa correctamente cuando las solicitudes son altas.
* El panel de detalles del registro (inferior) no se actualiza.

==== Salida de muestra del escáner

[,shell]
----
Image: https://registry.hub.docker.comlibrary/alpine:3.4
Base OS: alpine:3.4.6
TOTAL: 6, HIGH: 1, MEDIUM: 5, LOW: 0, UNKNOWN: 0
┌─────────┬───────────────┬──────────┬───────────┬───────────────┬────────────┐
│ PACKAGE │ VULNERABILITY │ SEVERITY │ VERSION   │ FIXED VERSION │ PUBLISHED  │
├─────────┼───────────────┼──────────┼───────────┼───────────────┼────────────┤
│ openssl │ CVE-2018-0732 │ High     │ 1.0.2n-r0 │ 1.0.2o-r1     │ 2018-06-12 │
│         ├───────────────┼──────────┤           ├───────────────┼────────────┤
│         │ CVE-2018-0733 │ Medium   │           │ 1.0.2o-r0     │ 2018-03-27 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-0734 │          │           │ 1.0.2q-r0     │ 2018-10-30 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-0737 │          │           │ 1.0.2o-r2     │ 2018-04-16 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-0739 │          │           │ 1.0.2o-r0     │ 2018-03-27 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-5407 │          │           │ 1.0.2q-r0     │ 2018-11-15 │
└─────────┴───────────────┴──────────┴───────────┴───────────────┴────────────┘
----

=== 5.1.2 March 2023

==== Mejoras

* Admite protecciones de red que coinciden con políticas y grupos de direcciones basados en host virtuales. Esto permite un caso de uso donde dos direcciones FQDN diferentes se resuelven en la misma dirección IP, pero se deben aplicar reglas diferentes para cada FQDN. Se puede crear un nuevo grupo personalizado con '`dirección=vh:xxx.yyy`' utilizando el indicador '`vh:`' para habilitar esta protección. Luego, una regla de red puede usar el grupo personalizado como '`origen`' según el nombre de host virtual (en lugar de la dirección IP resuelta) para aplicar diferentes reglas para los hosts virtuales.
* Lista de contenedores de cumplimiento para excluir los contenedores salidos.
* Mejorar las reglas DLP para admitir comodines simples en el patrón.
* Agregue soporte para cri-o 1.26+ y OpenShift 4.11+.
* Hacer que Gravatar sea opcional.
* Mostrar el recurso del espacio de nombres del clúster en la consola/IU.
* Mostrar la gravedad/clasificación de la fuente (por ejemplo, Red Hat, Ubuntu)...) junto con la puntuación de gravedad de NVD en la consola.
* No permita la deshabilitación de SSO/RBAC para Rancher y OpenShift si el usuario está autenticado a través de SSO.
* Agregue la habilitación del escaneo automático y la eliminación del envejecimiento de grupos no utilizados a configMap.
* Incluir dirección IP para origen/destino externo en csv/pdf para violaciones de denegación implícita
* Varias optimizaciones de rendimiento y escalabilidad para el uso de CPU y memoria del controlador y del ejecutor.

==== Correcciones de errores de programas

* Corrige la lentitud de la aplicación en los nodos del sistema operativo optimizado para contenedores (COS) de GKE cuando está en modo de protección.
* SUSE Linux (SLES) 15.4 CVE no coincide con el escáner. Con esta solución, si se proporciona la gravedad en el feed, la vulnerabilidad se agregará a la base de datos, incluso si falta el registro NVD. Es posible que el informe incluya vulnerabilidades sin puntuaciones CVE.

==== Otros

* Mejorar las opciones de control de admisión CRD en Helm https://github.com/neuvector/neuvector-helm/pull/237.
* Agregue nuevas variables de entorno de cumplimiento al gráfico de Helm.

=== 5.1.1 Febrero de 2023

==== Mejoras

* Agregue "`un paquete`" como información al evento syslog para una vulnerabilidad detectada.
* Agregue la variable de entorno de Enforcer ENF_NETPOLICY_PULL_INTERVAL: valor en segundos (valor recomendado 60) para reducir el tráfico de red y el consumo de recursos resultante por parte de Enforcer debido a actualizaciones/recálculos de políticas. (Nota: esta fue una adición no documentada hasta agosto de 2023).

[,yaml]
----
           - name: ENF_NETPOLICY_PULL_INTERVAL
             value: "60"   <== regulate the pulling gap by 60 seconds
----

==== Correcciones de errores de programas

* Errores de eliminación de grupo vacío "Objeto no encontrado"
* Alerta/bloqueo de tráfico dentro del mismo contenedor
* Violaciones implícitas inesperadas para el tráfico de salida de istio con una regla de permiso implementada
* Al actualizar desde {product-name} Versión 4.x: la membresía incorrecta del grupo de pods provoca una violación inesperada de la política
* La autenticación OIDC falló con ADFS cuando aparecen caracteres de codificación adicionales en la solicitud
* Alto uso de memoria por parte de dp al crear y eliminar pods
* Actualización de Alpine para remediar varios CVE, incluido Manager: CVE-2022-37454, CVE-2022-42919, CVE-2022-45061, CVE-2021-46848; Enforcer: CVE-2022-43551, CVE-2022-43552
* Se han corregido varios errores de interfaz de usuario.

==== Otros

* Se actualizó el gráfico de Helm para permitir el reemplazo del certificado para comunicaciones internas

=== 5.1.0 Diciembre de 2022

==== Mejoras

* Base de datos centralizada de escaneo de múltiples clústeres (CVE). El clúster principal (maestro) puede escanear un registro/repositorio designado como registro federado. Los resultados del escaneo de estos registros se sincronizarán con todos los clústeres administrados (remotos). Esto permite la visualización de los resultados del escaneo en la consola del clúster administrado, así como el uso de los resultados en las reglas de control de admisión del clúster administrado. Los registros solo necesitan escanearse una vez en lugar de por cada clúster, lo que reduce el uso de CPU/memoria y ancho de banda de red.
* Mejorar las reglas de control de admisión:
 ** Criterios personalizados para reglas de control de admisión. Permitir a los usuarios definir criterios de recursos en todos los campos relacionados con el pod y usarlos en reglas, por ejemplo, item.metadata.annotationsKey contiene 'neuvector', item.metadata.name='xyzzy', etc.
 ** Agregue criterios para verificar configuraciones RBAC de alto riesgo para cuentas de servicio al implementar pods. Estos incluyen los criterios "cualquier acción de recursos de carga de trabajo", "cualquier acción en RBAC", "crear recursos de carga de trabajo", "enumerar secretos" y "ejecutar en un contenedor".
 ** Agregar comparación de versiones semánticas a los módulos para las reglas de control de admisión. Esto permite que los operadores > o < se apliquen a los números de versión en las reglas (por ejemplo, no permitir que se implemente el módulo curl<6.2.0). Esto permite realizar comprobaciones de versiones específicas en paquetes instalados.
 ** Agregue una regla de control de admisión para la admisión de seguridad de pods (PSA) compatible con Kubernetes 1.25+.
* Agregue la nueva variable de entorno NO_DEFAULT_ADMIN que, cuando está habilitada, no crea un usuario 'admin'. Esto se utiliza para la integración de SSO de Rancher como predeterminado. Si no está habilitado, advierte de forma persistente al usuario y registra eventos para cambiar la contraseña de administrador predeterminada si no se cambia la predeterminada.
* Bloquear el inicio de sesión después de intentos fallidos ahora se convierte en la opción predeterminada. El valor predeterminado es 5 intentos y se puede configurar en Configuración. -> Usuarios y roles-> Perfil de contraseña.
* Agregar nueva variable env para ajustar el rendimiento ENF_NO_SYSTEM_PROFILES, valor: "1". Cuando está habilitado, deshabilitará los monitores de procesos y archivos. No se realizarán procesos de aprendizaje, ni modos de perfil, ni incidentes de procesos/archivos (paquetes), ni tampoco se realizará ningún monitoreo de actividad de archivos. Esto reducirá el uso de recursos de CPU/memoria y las operaciones de archivos.
* Agregue una configuración de escalamiento automático personalizada para los módulos del escáner, con los valores Retrasado, Inmediato y Deshabilitado. Importante: El escalamiento automático del escáner no es compatible cuando el escáner se implementa con un operador de OpenShift, ya que el operador siempre cambiará la cantidad de pods a su valor configurado.
 ** *_Estrategia retrasada:_*
  *** Cuando el controlador principal ve continuamente un "conteo de tareas" > 0 durante > 90 segundos, se inicia un nuevo pod de escáner si aún no se alcanza el número máximo de Pods de escáner.
  *** Cuando el controlador principal ve continuamente que el "conteo de tareas" es 0 durante > 180 segundos, reduce la escala de un pod de escáner si aún no se alcanza minScannerPods.
 ** *_Estrategia inmediata:_*
  *** Cada vez que el controlador principal ve que "conteo de tareas" > 0, se inicia un nuevo pod de escáner si aún no se alcanza el número máximo de Pods de escáner.
  *** Cuando el controlador principal ve continuamente que el "conteo de tareas" es 0 durante > 180 segundos, reduce la escala de un pod de escáner si aún no se alcanza minScannerPods.
* Los grupos personalizados ahora pueden usar etiquetas de espacio de nombres, incluidas las etiquetas de espacio de nombres de Rancher. En general, ahora se pueden agregar etiquetas de pod y espacio de nombres a grupos personalizados.
* Agregue la capacidad de ocultar espacios de nombres y grupos seleccionados en la vista Actividad de red.
* Soporte completo para Cilium cni.
* Soporte completo de OpenShift 4.9 y 4.10.
* Las herramientas de compilación ahora están disponibles para {product-name}/Proyecto Open Zero Trust (OZT) en https://github.com/openzerotrust/openzerotrust.io.
* {product-name} Ahora enumera el ID de la versión y el resumen SHA256 para cada versión del controlador, administrador y ejecutor en https://github.com/neuvector/manifests/tree/main/versions.
* Los datos de telemetría anónimos (cantidad de nodos, grupos, reglas) ahora se informan a un servicio en la nube de Rancher durante la implementación para ayudar al equipo del proyecto a comprender el comportamiento de uso. Esto se puede desactivar (optar por no participar) en la interfaz de usuario o con configMap (No_Telemetry_Report) o API REST.
* (Adenda enero 2023). Compatibilidad con políticas de red basadas en ServiceEntry con Istio. La funcionalidad de cumplimiento de políticas de red de salida se agregó en la versión 5.1.0 para pods en destinos ServiceEntry declarados con Istio. Normalmente, una ServiceEntry define cómo se resuelve un servicio externo referido por un nombre DNS a una IP de destino. Antes de la versión v5.1, {product-name} No se pudieron detectar ni aplicar reglas para las conexiones a un ServiceEntry, por lo que todas las conexiones se clasificaron como externas. Con 5.1, se pueden aplicar reglas para destinos de ServiceEntry específicos. IMPORTANTE: Si está actualizando a v5.1 con una implementación basada en Istio, se deben crear nuevas reglas para permitir estas conexiones y evitar alertas de violación. Después de la actualización, se informarán violaciones implícitas para el tráfico recientemente visible si no existen reglas de autorización. Se pueden aprender y crear automáticamente nuevas reglas de tráfico en el modo Descubrir. Para permitir este tráfico, puede poner el grupo en modo de descubrimiento o crear un grupo personalizado con direcciones (o nombre DNS) y una nueva regla de red para este destino para permitir el tráfico. NOTA: Hay un error en 5.1.0 en el destino informado por las violaciones de denegación que no representan el destino correcto.  Los informes de errores tanto de server_name como de client_name son los mismos.  Este problema se solucionará en una próxima versión del parche.

==== Correcciones de errores de programas

* Reduce el consumo de memoria del controlador a partir de datos de referencia cis innecesarios creados durante actualizaciones continuas. Este problema no ocurre en implementaciones nuevas.
* Eliminar la licencia de la pantalla de configuración (ya no es necesario).

=== 5.0.6-s1 March, 2023

==== Correcciones de errores de programas

* Actualizar los paquetes alpinos para remediar los CVE en curl, incluidos CVE-2023-23914, CVE-2023-23915 y CVE-2023-23916

=== 5.0.6 February, 2023

==== Correcciones de errores de programas

* Alto uso de memoria en dpMsgConnection
* Alto uso de memoria en el proceso dp en Enforcer si hay muchas reglas de política aprendidas con una carga de trabajo no administrada (pérdida de memoria)
* tcpdump no puede iniciarse correctamente al rastrear el tráfico en un contenedor
* Actualización de Alpine para remediar varios CVE, incluido Manager: CVE-2022-37454, CVE-2022-42919, CVE-2022-45061, CVE-2021-46848; Enforcer: CVE-2022-43551, CVE-2022-43552

=== 5.0.5 Noviembre de 2022

==== Correcciones de errores de programas

* La actualización a 5.0.x genera un mensaje de error sobre Manager, Controller y Enforcer que ejecutan versiones diferentes.
* Los ejecutores experimentan pánico rutinario que resulta en la muerte de DP.  La interfaz web no refleja al ejecutor como en línea.
* Incidente inesperado de Process.Profile.Violation en el grupo NV.Protect en el que se ejecuta el comando en coreos.

=== 5.0.4 October, 2022

==== Actualizaciones de seguridad

* Actualice Alpine para eliminar CVE-2022-40674 crítico en la biblioteca del administrador expat, así como otros CVE menores.

==== Mejoras

* Añadir soporte para Antrea CNI

==== Correcciones de errores de programas

* Solucione el incidente inesperado process.profile.violation en el grupo NV.Protect.
* Cuando SSL está deshabilitado en el acceso a la interfaz de usuario del administrador, la contraseña del usuario se imprime en el registro del administrador.

=== 5.0.3 Septiembre de 2022

==== Mejoras

* No mostrar el EULA después de un reinicio exitoso desde un volumen persistente.
* Utilice el filtro de imagen en la configuración del perfil de vulnerabilidad para omitir los resultados del análisis del contenedor.
* Escáner de soporte en acciones de GitHub en https://github.com/neuvector/neuvector-image-scan-action.
* Agregue variables de entorno de Enforcer para deshabilitar el escaneo de secretos y la ejecución de puntos de referencia de CIS

[,yaml]
----
    env:
      - name: ENF_NO_SECRET_SCANS  (available after v4.4.4)
        value: "1"
      - name: ENF_NO_AUTO_BENCHMARK (after v5.0.3)
        value: "1"
----

==== Correcciones de errores de programas

* Enforcer no puede iniciarse ocasionalmente.
* Fuga de conexión en entornos de federación de múltiples clústeres.
* La página de Cumplimiento no se carga a veces en Riesgos de Seguridad -> Cumplimiento

=== 5.0.2 Julio de 2022

==== Mejoras

* Se admiten clústeres SELinux y reforzados con Rancher.

==== Correcciones de errores de programas

* El proceso del agente hace un alto uso de la CPU en los sistemas k3s.
* Los grupos LDAP de AD no funcionan correctamente después de la actualización a 5.0.
* Enforcer sigue reiniciándose debido a un error = demasiados archivos abiertos (rke2/cilium).
* No se puede descargar correctamente el registro de soporte.

=== 5.0.1 Junio de 2022

==== Mejoras

* Admite el análisis de vulnerabilidades del sistema operativo openSUSE Leap (en la imagen del escáner).
* Escáner: implementar atributos de borrado durante la reconstrucción del repositorio de imágenes.
* Verificar {product-name} Implementación y soporte para hosts habilitados para SELinux. Consulte a continuación los detalles sobre la aplicación de parches provisionales hasta que se actualice el gráfico del timón.
* Distinga entre el gráfico de características y los gráficos de socios en la interfaz de usuario de Rancher de forma más destacada. + Mejore la anotación de ingreso para nginx en el gráfico de Helm de Rancher. Agregar/actualizar ingress.kubernetes.io/protocol: https a nginx.ingress.kubernetes.io/backend-protocol: "HTTPS".
* El operador OpenShift actual admite rutas de paso para servicios de API y federación. Se agregan parámetros de valor de Helm adicionales para admitir tipos de terminación de ruta de borde y reencriptación.

==== Correcciones de errores de programas

* El clúster AKS podría agregar una clave inesperada en el webhook de control de admisión.
* Enforcer no está operativo en el clúster k8s 1.24 con el entorno de ejecución containerd 1.64. Por otra parte, a veces el ejecutor no logra iniciarse.
* Cualquier usuario con rol de administrador (usuario local o SSO) que promueva un clúster a maestro federal debe ser promovido automáticamente al rol de fedAdmin.
* Al iniciar sesión con SSO y usar Rancher, el administrador predeterminado ingresa {product-name} En el grupo maestro, el {product-name} El rol de inicio de sesión es admin, no fedAdmin.
* Corrige varios fallos de goroutine.
* Violación implícita de IP de host no asociada con el nodo.
* ComplianceProfile no muestra la etiqueta PCI.
* A veces no se muestra la asignación de grupos LDAP.
* La herramienta de revisión y mejora de riesgos generará el mensaje de error "Error al actualizar la configuración del sistema: "Solicitud en formato incorrecto".
* OKD 3.11 - El error de Clusterrole se muestra incluso si existe.

==== Remediaciones de CVE

* Se encontró un alto cve CVE-2022-29458 en el paquete ncurses en todas las imágenes.
* Se encontraron CVE-2022-27778 y CVE-2022-27782 de alto nivel en el paquete curl en la imagen del actualizador.

==== Detalles sobre la compatibilidad con SELinux

{product-name} no necesita ninguna configuración adicional para que los clústeres habilitados para SELinux se implementen y funcionen. Implementación probada {product-name} en un clúster reforzado con RKE2 habilitado con SELinux basado en RHEL 8.5. {product-name} Se implementó exitosamente si PSP está habilitado y se aplican parches al Administrador y a la implementación del escáner. La próxima versión del gráfico debería solucionar el problema siguiente.

Se adjunta un ejemplo para habilitar psp desde el gráfico de Rancher y a continuación se proporcionan los comandos para parchar la implementación del Administrador y del Escáner. El ID de usuario en el comando de parche puede ser cualquier número.

[,shell]
----
kubectl patch deploy -ncattle-neuvector-system neuvector-scanner-pod --patch '{"spec":{"template":{"spec":{"securityContext":{"runAsUser": 5400}}}}}'
kubectl patch deploy -ncattle-neuvector-system neuvector-manager-pod --patch '{"spec":{"template":{"spec":{"securityContext":{"runAsUser": 5400}}}}}'
----

Ejemplo para habilitar PSP:

[,shell]
----
[neuvector@localhost nv]$ getenforce
Enforcing
[neuvector@localhost nv]$ sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      33

[neuvector@localhost nv]$ kk get psp
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
NAME                      PRIV    CAPS                                      SELINUX    RUNASUSER          FSGROUP     SUPGROUP    READONLYROOTFS   VOLUMES
global-restricted-psp     false                                             RunAsAny   MustRunAsNonRoot   MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
neuvector-binding-psp     true    SYS_ADMIN,NET_ADMIN,SYS_PTRACE,IPC_LOCK   RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
system-unrestricted-psp   true    *                                         RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
[neuvector@localhost nv]$ nvpo.sh
NAME                                        READY   STATUS    RESTARTS   AGE     IP           NODE                    NOMINATED NODE   READINESS GATES
neuvector-controller-pod-54f69f7f9c-6h822   1/1     Running   0          5m51s   10.42.0.29   localhost.localdomain   <none>           <none>
neuvector-enforcer-pod-jz77b                1/1     Running   0          5m51s   10.42.0.30   localhost.localdomain   <none>           <none>
neuvector-manager-pod-588488bb78-p6vf9      1/1     Running   0          111s    10.42.0.32   localhost.localdomain   <none>           <none>
neuvector-scanner-pod-87474dcff-s8vgt       1/1     Running   0          114s    10.42.0.31   localhost.localdomain   <none>           <none>
----

=== Versión 5.0.0 de disponibilidad general (GA) de mayo de 2022

==== Mejoras

* Promoción automatizada de modos de grupo. Promueve el modo de protección de un grupo en función del tiempo transcurrido y criterios. No se aplica a grupos creados por CRD. Esta función permite que una nueva aplicación se ejecute en Discover durante un período de tiempo, aprendiendo el comportamiento y {product-name} creando reglas de lista blanca para red y proceso, luego pasando automáticamente al modo Monitor y luego al modo Proteger. Criterio de Descubrir para Monitorear: Tiempo transcurrido para aprender toda la actividad de la red y del proceso de al menos un pod activo en el grupo. Criterio de Monitoreo para Proteger: No existen eventos de seguridad (red, proceso, etc.) para el período de tiempo establecido para el Grupo.
* Soporte para aplicaciones Rancher 2.6.5 y gráficos de Marketplace. Se implementa en el espacio de nombres cattle-neuvector-system y permite el inicio de sesión único (SSO) desde Rancher a {product-name}. Nota: Las implementaciones anteriores de Rancher (por ejemplo, gráficos del catálogo de socios, versión 1.9.x y anteriores) deben eliminarse por completo para poder actualizar al nuevo gráfico.
* Admite escaneo de SUSE Linux (SLE, SLES) y Microsoft Mariner
* Proceso de deriva cero y protección de archivos. Este es el nuevo modo predeterminado para la protección de procesos y archivos. Zero-drift permite automáticamente solo procesos que se originan en el proceso principal que está en la imagen del contenedor original y no permite actualizaciones de archivos ni la instalación de archivos nuevos. Cuando esté en modo Descubrir o Monitorear, Zero-Drift alertará sobre cualquier proceso o actividad de archivo sospechosa. En el modo de protección, bloqueará dicha actividad. La deriva cero no requiere que se aprendan procesos ni que se los agregue a una lista de permitidos. Al deshabilitar la desviación cero para un grupo, se aplicarán las reglas de proceso y archivo enumeradas para ese grupo.
* Protección en modo de política dividida para red, proceso/archivo. Ahora hay una configuración global disponible en Configuración -> Configuración para establecer por separado el modo de protección de red para la aplicación de las reglas de red. Al habilitar esta opción (el valor predeterminado está deshabilitado), todas las reglas de red estarán en el modo de protección seleccionado (Descubrir, Monitorear, Proteger), mientras que las reglas de proceso/archivo permanecerán en el modo de protección para ese grupo, como se muestra en la Política. -> Pantalla de grupos. De esta manera, las reglas de red se pueden configurar para Proteger (bloquear), mientras que la política de proceso/archivo se puede configurar para Monitorear, o viceversa.
* Detección de reglas WAF, reglas DLP mejoradas (encabezado, URL, paquete completo). Se utiliza para conexiones de ingreso a pods de aplicaciones web, así como conexiones de salida a servicios de API para reforzar la seguridad de la API.
* CRD para WAF, DLP y controles de admisión. NOTA: se requieren enlaces y permisos de roles de clúster adicionales. Consulte las secciones de implementación de Kubernetes y OpenShift. Importación/exportación de CRD y control de versiones para controles de admisión compatibles con CRD.
* Lanzamiento de la integración SSO de Rancher {product-name} consola a través de Rancher Manager. Esta función solo está disponible si el {product-name} Los contenedores se implementan a través de Rancher. Esta implementación se extrae del repositorio reflejado de Rancher (por ejemplo, rancher/mirrored-neuvector-controller:5.0.0) y se implementa en el espacio de nombres cattle-neuvector-system. NOTA: Requiere la versión actualizada de Rancher 2.6.5 de mayo de 2022 o posterior, y solo se admiten los roles de administrador y propietario del clúster en este momento.
* Admite implementación en RKE2.
* Soporte para federación de clústeres (administrador de múltiples clústeres) a través de un proxy. Configurar el proxy en Configuración -> Configuración y habilitación de proxy al configurar conexiones de federación.
* Supervise los roles y enlaces de clúster de rbac requeridos y genere alertas en eventos y en la interfaz de usuario si falta alguno.
* Criterios de apoyo de limitaciones de recursos en las reglas de control de admisión.
* Admite el formato de Microsoft Teams para webhooks.
* Admite grupos anidados de AD/LDAP bajo un grupo de roles asignado.
* Admite enlaces de roles de clúster o enlaces de roles con información de grupo en IDP para Openshift.
* Permitir que las reglas de red y las reglas de control de admisión se promuevan a una regla federada.

==== Correcciones de errores de programas

* Se soluciona el problema de la copia de seguridad del rol de federación de trabajadores que se debe restaurar en clústeres no federados.
* Mejorar los tiempos de carga de páginas para una gran cantidad de CVE en Riesgos de Seguridad -> Vulnerabilidades
* Permitir que el usuario cambie de modo cuando selecciona todos los grupos en la Política -> Menú de grupos. Avisar si el grupo Nodos también está seleccionado.
* Contraer los elementos de verificación de cumplimiento del mismo nombre y hacerlos expandibles.
* Mejorar la seguridad de las comunicaciones gRPC.
* Corregido: no se puede obtener información privilegiada de carga de trabajo correcta en la configuración de rke2.
* Solucionar el problema con el soporte de openSUSE Leap 15.3 (k8s/crio).

==== Otras actualizaciones

* Actualización de la aplicación de cartas Helm a la versión 5.0.0 y de la versión de cartas a la 2.2.0
* Se eliminó la función/menú de escaneo sin servidor.
* Se eliminó el soporte para la integración de resultados de escaneo de rayos X de Jfrog (el escaneo de registro de Artifactory aún es compatible).
* Ya no se proporciona soporte para la implementación en ECS. Aún debería ser posible implementar el todo en uno en ECS, sin embargo, la documentación de los pasos y las configuraciones ya no es compatible.

=== Actualización desde {product-name} 4.x a 5.x (antes de 5.2.x)

[NOTE]
====
Las instrucciones a continuación se aplican a las actualizaciones a 5.0.x y 5.1.x. Para 5.2.x, las cuentas de servicio y los enlaces han cambiado y se deben xref:kubernetes.adoc#_deploy_suse_security[revisar] para planificar actualizaciones.
====


Para los usuarios de Helm, actualice a {product-name} Carta de timón 2.0.0 o posterior. Si actualiza una instalación de Operator o Helm en OpenShift, consulte la nota a continuación.

. Eliminar el antiguo rol de clúster neuvector-binding-customresourcedefinition

[,shell]
----
kubectl delete clusterrole neuvector-binding-customresourcedefinition
----

. Aplicar nuevo verbo de actualización para neuvector-binding-customresourcedefinition clusterrole

[,shell]
----
kubectl create clusterrole neuvector-binding-customresourcedefinition --verb=watch,create,get,update --resource=customresourcedefinitions
----

. Eliminar el antiguo esquema crd para Kubernetes 1.19+

[,shell]
----
kubectl delete -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/crd-k8s-1.19.yaml
----

. Crear un nuevo esquema crd para Kubernetes 1.19+

[,shell]
----
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/crd-k8s-1.19.yaml
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/waf-crd-k8s-1.19.yaml
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/dlp-crd-k8s-1.19.yaml
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/admission-crd-k8s-1.19.yaml
----

. Crear un nuevo rol de clúster de admisión, DLP y WAF y un enlace de rol de clúster

[,shell]
----
kubectl create clusterrole neuvector-binding-nvwafsecurityrules --verb=list,delete --resource=nvwafsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvwafsecurityrules --clusterrole=neuvector-binding-nvwafsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvadmissioncontrolsecurityrules --verb=list,delete --resource=nvadmissioncontrolsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvadmissioncontrolsecurityrules --clusterrole=neuvector-binding-nvadmissioncontrolsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvdlpsecurityrules --verb=list,delete --resource=nvdlpsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvdlpsecurityrules --clusterrole=neuvector-binding-nvdlpsecurityrules --serviceaccount=neuvector:default
----

. Actualizar los nombres y rutas de las imágenes para extraerlas {product-name} imágenes de Docker Hub (docker.io), por ejemplo

* neuvector/manager:5.0.0
* neuvector/controller:5.0.0
* neuvector/enforcer:5.0.0
* neuvector/scanner:último
* neuvector/actualizador:último

Opcionalmente, elimine cualquier referencia a la {product-name} licencia y secreto de registro en gráficos de Helm, yaml de implementación, mapa de configuración, scripts, etc., ya que ya no son necesarios para extraer las imágenes o comenzar a usar {product-name}.

*Nota sobre SCC y actualización mediante operador/timonel*

El SCC privilegiado se agrega a la cuenta de servicio especificada en el yaml de implementación por el operador versión 1.3.4 y superiores en nuevas implementaciones. En el caso de actualizar el {product-name} Operador de una versión anterior a 1.3.4 o Helm a 2.0.0, elimine el SCC privilegiado antes de actualizar.

[,shell]
----
oc delete rolebinding -n neuvector system:openshift:scc:privileged
----

==== Versión Beta 1 lanzada en abril de 2022

* Funciones completas, incluida la promoción automatizada de modos de grupo. Promueve el modo de protección de un grupo en función del tiempo transcurrido y criterios. No se aplica a grupos creados por CRD. Esta función permite que una nueva aplicación se ejecute en Discover durante un período de tiempo, aprendiendo el comportamiento y {product-name} creando reglas de lista blanca para red y proceso, luego pasando automáticamente al modo Monitor y luego al modo Proteger. Criterio de Descubrir para Monitorear: Tiempo transcurrido para aprender toda la actividad de la red y del proceso de al menos un pod activo en el grupo. Criterio de Monitoreo para Proteger: No existen eventos de seguridad (red, proceso, etc.) para el período de tiempo establecido para el Grupo.
* Soporte para aplicaciones Rancher 2.6.5 y gráficos de Marketplace. Se implementa en el espacio de nombres cattle-neuvector-system y permite el inicio de sesión único (SSO) desde Rancher a {product-name}. Nota: Las implementaciones anteriores de Rancher (por ejemplo, gráficos del catálogo de socios, versión 1.9.x y anteriores) deben eliminarse por completo para poder actualizar al nuevo gráfico.
* Etiquetas para Enforcer, Manager, Controller: 5.0.0-b1 (por ejemplo, neuvector/controlador:5.0.0-b1)

==== Versión Preview.3 lanzada en marzo de 2022

[CAUTION]
.importante
====

Para actualizar las implementaciones de vista previa anteriores para las nuevas funciones de CRD WAF, DLP y control de admisión, actualice el CRD yaml y agregue nuevos enlaces rbac/role:

[,shell]
----
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/latest/crd-k8s-1.19.yaml
kubectl create clusterrole neuvector-binding-nvwafsecurityrules --verb=list,delete --resource=nvwafsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvwafsecurityrules --clusterrole=neuvector-binding-nvwafsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvadmissioncontrolsecurityrules --verb=list,delete --resource=nvadmissioncontrolsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvadmissioncontrolsecurityrules --clusterrole=neuvector-binding-nvadmissioncontrolsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvdlpsecurityrules --verb=list,delete --resource=nvdlpsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvdlpsecurityrules --clusterrole=neuvector-binding-nvdlpsecurityrules --serviceaccount=neuvector:default
----
====


==== Mejoras

* Admite escaneo de SUSE Linux (SLE, SLES) y Microsoft Mariner
* Proceso de deriva cero y protección de archivos. Este es el nuevo modo predeterminado para la protección de procesos y archivos. Zero-drift permite automáticamente solo procesos que se originan en el proceso principal que está en la imagen del contenedor original y no permite actualizaciones de archivos ni la instalación de archivos nuevos. Cuando esté en modo Descubrir o Monitorear, Zero-Drift alertará sobre cualquier proceso o actividad de archivo sospechosa. En el modo de protección, bloqueará dicha actividad. La deriva cero no requiere que se aprendan procesos ni que se los agregue a una lista de permitidos. Al deshabilitar la desviación cero para un grupo, se aplicarán las reglas de proceso y archivo enumeradas para ese grupo.
* Protección en modo de política dividida para red, proceso/archivo. Ahora hay una configuración global disponible en Configuración -> Configuración para establecer por separado el modo de protección de red para la aplicación de las reglas de red. Al habilitar esta opción (el valor predeterminado está deshabilitado), todas las reglas de red estarán en el modo de protección seleccionado (Descubrir, Monitorear, Proteger), mientras que las reglas de proceso/archivo permanecerán en el modo de protección para ese grupo, como se muestra en la Política. -> Pantalla de grupos. De esta manera, las reglas de red se pueden configurar para Proteger (bloquear), mientras que la política de proceso/archivo se puede configurar para Monitorear, o viceversa.
* Detección de reglas WAF, reglas DLP mejoradas (encabezado, URL, paquete completo)
* CRD para WAF, DLP y controles de admisión. NOTA: se requieren enlaces y permisos de roles de clúster adicionales. Consulte las secciones de implementación de Kubernetes y OpenShift. Importación/exportación de CRD y control de versiones para controles de admisión compatibles con CRD.
* Lanzamiento de la integración SSO de Rancher {product-name} consola a través de Rancher Manager. Esta función solo está disponible si el {product-name} Los contenedores se implementan a través de Rancher. NOTA: Requiere versión actualizada de Rancher (fecha/versión a determinar).
* Admite implementación en RKE2.
* Soporte para federación de clústeres (administrador de múltiples clústeres) a través de un proxy.
* Supervise los roles y enlaces de clúster de rbac requeridos y genere alertas en eventos y en la interfaz de usuario si falta alguno.
* Criterios de apoyo de limitaciones de recursos en las reglas de control de admisión.

==== Correcciones de errores de programas

* Se soluciona el problema de la copia de seguridad del rol de federación de trabajadores que se debe restaurar en clústeres no federados.

==== Versión Preview.2 lanzada en febrero de 2022

* Cambios menores en el archivo y la licencia del código fuente, no se agregaron funciones.

==== Compatibilidad con la implementación en AWS ECS Obsoleto

Ya no se proporciona soporte para la implementación en ECS. Aún debería ser posible implementar el todo en uno en ECS, sin embargo, la documentación de los pasos y las configuraciones ya no es compatible.

=== 5.0 'Tech Preview' de enero de 2022

==== Mejoras

* Primer lanzamiento de una versión de "vista previa técnica" sin soporte de {product-name} Versión de código abierto 5.0.
* Agregue soporte para OWASP Top-10, reglas similares a WAF para detectar ataques de red en encabezados o cuerpo. Incluye soporte para definiciones CRD de firmas y aplicación a grupos apropiados.
* Elimina las funciones de escaneo sin servidor.

==== Correcciones de errores de programas

* aún por decidir.

==== Otros

* El gráfico Helm v1.8.9 se publica para las implementaciones 5.0.0. Si se utiliza con la versión de vista previa de 5.0.0, se deben realizar los siguientes cambios en values.yml:
 ** Actualizar el registro a docker.io
 ** Actualizar los nombres/etiquetas de las imágenes a la versión de vista previa en Docker Hub
 ** Deje la imagenPullSecrets vacía
